### ISSUE TITLE
Problem with calling getStart repeatedly

### ISSUE THREAD

**Issue by fyem** [microsoftgraph/msgraph-sdk-php#10]
Calling getStart() on the Event Model repeatedly will lead to nested DateTimeTimeZone Objects

Calling print_r($event->getStart()) three times in a row will lead to this result:
![screenshot_032417_012748_am](https://cloud.githubusercontent.com/assets/1120134/24275638/36fcdd56-1031-11e7-95a4-e4ccd0ea882a.jpg)

Changing
`if (is_a($this->_propDict["start"], "DateTimeTimeZone")) {`

Into

`if (is_a($this->_propDict["start"], "Microsoft\Graph\Model\DateTimeTimeZone")) {`

solved this problem for me.

(It is likely that the same issue occures for other methods returning objects, e.g. getLocation(), getBody() etc.)

**Comment by cbales** [comment]
Thanks for reporting this. I'll push a fix for all the models shortly!
