### ISSUE TITLE
How to get the Date of an email

### ISSUE THREAD

**Issue by basementmedia2** [microsoftgraph/msgraph-sdk-php#1028]
Hi,

is use your great library as replacement of the old EWS.

In the EWS-Library there was a function, which returned the date of an email.

$datum=$email->getDateTimeSent();

Is there a similar function to get the date of the email-object returned by your library?

I tried "$datum=$email->getDate();" but that doesn't work.

All other things (e.g. $email->getSubject();) work perfectly.

Thank you for your help in advance ;-)

Best regards 
Daniel

**Comment by basementmedia2** [comment]
Yes, i found out:

```
$email = $graph->createRequest("GET", "my@email.de/mailfolders/inbox/messages/".$email_id."?\$select=internetMessageHeaders")
->setReturnType(Model\Message::class)
->execute();
$mailHeaders = $email->getInternetMessageHeaders();

if (is_array($mailHeaders)) {
	for ($i=0; $i<count($mailHeaders); $i++) {
		$headerName=$mailHeaders[$i]["name"];
                if ($headerName=="Date") { 
                    $datum=$mailHeaders[$i]["value"];
                }    
	}
}
```

Maybe there is a better solution? 
But it works ;-)

**Comment by SilasKenneth** [comment]
Hi @basementmedia2,
Thanks for taking your time to try out the PHP SDK. To get the sentDateTime use
```php
$sentDate = $email->getSentDateTime();
```
Feel free to close the issue if that works for you.

Regards,
@SilasKenneth
