### ISSUE TITLE
Support for AD Graph API (graph.windows.net)

### ISSUE THREAD

**Issue by aeimer** [microsoftgraph/msgraph-sdk-php#103]
Hi there,

we want to use this package for the AD Graph API => graph.windows.net (not the normal Graph API => graph.microsoft.com).

The main problem I currently see, is how the version is passed in the URL (URL-Path vs GET-Param).

Is there another PHP Package which supports the AD Graph API?
Do you plan to support the AD Graph API in future?

Best regards

Alex 
[AB#7574](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7574)

**Comment by psignoret** [comment]
Could you share some more details on the reasons you prefer to use the Azure AD Graph API for, rather than Microsoft Graph? Which feature from Azure AD Graph are  you missing in Microsoft Graph?

**Comment by aeimer** [comment]
@psignoret We are using the Azure AD with the B2C option. We only were able to add user over the AD Azure Graph API, but not over the normal Graph API. So we had to use Guzzle directly and could not use this package. The main problem seems to be, how the version is transmitted. `/v1.6/users` vs `/users?api-version=1.6`.

Reffering to https://docs.microsoft.com/de-de/azure/active-directory-b2c/active-directory-b2c-devquickstarts-graph-dotnet#get-an-azure-ad-b2c-tenant

**Comment by psignoret** [comment]
That's a good reason. Your best bet is to continue using Guzzle (or any other client) directly, until B2C is supported by Microsoft Graph. (I promise, it's coming.)

I would not suggest trying to use this library for the Azure AD Graph API, because there are several other differences (in addition to the version) you'll need to deal with (including the object model and the paging mechanism), so even if you hack it together to work, in end it'll just end up doing the same amount of effort as using Guzzle directly.

**Comment by aeimer** [comment]
@psignoret Alright, thank you very much for the fast response :)

I'll leave this ticket open as reminder for you guys.

**Comment by sven5** [comment]
Hi @psignoret 

I came across a similar requirement and found this issue. In the [docs](https://docs.microsoft.com/en-US/azure/active-directory-b2c/active-directory-b2c-devquickstarts-graph-dotnet?tabs=applications) we currently still read that we must use the AD Graph API (graph.windows.net). Is there any update on when can we expect to query B2C data with standard MS graph API?

Thanks

**Comment by tlpetrova4** [comment]
Hi @sven5 ,

I am in the same situation as you. And also waiting for the B2C to be implemented. As of now, it is implemented only in Beta version as I saw from the MS Graph API [Change Log](https://docs.microsoft.com/en-us/graph/changelog). The new resource type is called [trustframeworkpolicy](https://docs.microsoft.com/en-us/graph/changelog#identity-and-access-azure-ad-11). Hope it gets to v1.0 soon.

**Comment by sven5** [comment]
Hi @tlpetrova4,
Yes, I already switched to the beta endpoint and updated my code to use MS Graph API. By now, this is working ok for us.

**Comment by MIchaelMainer** [comment]
AD Graph API has been deemphasized in favor of Microsoft Graph. This client library is intended to only be used with Microsoft Graph API endpoints.
