### ISSUE TITLE
Send attachment bigger then 4MB - 413 Request Entity Too Large

### ISSUE THREAD

**Issue by KodaCHC** [microsoftgraph/msgraph-sdk-php#1047]
Microsoft specifies a maximum size of 4MB for the request: https://learn.microsoft.com/de-de/graph/api/user-post-messages?view=graph-rest-1.0&tabs=http

Is there any way to still send an email with multiple file attachments over 4 MB?

**Comment by Ndiritu** [comment]
@KodaCHC please see https://learn.microsoft.com/en-us/graph/outlook-large-attachments?tabs=http

**Comment by KodaCHC** [comment]
@Ndiritu thank you, and sorry for my late answer.

Have you me an example? 

My mailbody currently has the following structure for the file attachments
```
$attachmentList[] = [
    "@odata.type" => "#microsoft.graph.fileAttachment",
    "name" => $attachment->getTitle(),
    "contentType" => $attachment->fileType,
    "contentBytes" => \base64_encode(\file_get_contents($attachment->getLocation()))
];
```

And send the email after that:

```
$graph->createRequest("POST", "/users/" . $user . "/sendMail")
     ->attachBody($mailBody)
     ->execute();
```

But for "attachments/createUploadSession" I need a messageId. But before I send my message I don't have a messageId?

**Comment by Ndiritu** [comment]
@KodaCHC you can create the message as a [draft](https://learn.microsoft.com/de-de/graph/api/user-post-messages?view=graph-rest-1.0&tabs=http) first then create an upload session using the returned `id`.

Unfortunately the SDK doesn't yet have functionality to help you partially upload the attachment bytes yet. 
This is in progress for our v2.x release candidate. You could take a look at `LargeFileUploadTask` [in progress implementation](https://github.com/microsoftgraph/msgraph-sdk-php-core/pull/76/files) for a hint on how to implement it for yourself.

**Comment by Ndiritu** [comment]
v2.0 of this SDK provides a [LargeFileUploadTask](https://github.com/microsoftgraph/msgraph-sdk-php/blob/dev/docs/Examples.md#uploading-large-files) to handle this.
