### ISSUE TITLE
Code undefined in $_GET ,getting this issue

### ISSUE THREAD

**Issue by kishanappringer** [microsoftgraph/msgraph-sdk-php#1054]
Hi Team, 

I'm getting error  "code undefined in $_GET" this issue when I try to create access token

![Screenshot from 2022-11-03 10-38-04](https://user-images.githubusercontent.com/107383884/199651414-229979b1-e2ea-47bd-b1de-941cdf0e6f3a.png)

Please help to solve this issue

Thanks 
Kishan

**Comment by Ndiritu** [comment]
duplicate of #1057
