### ISSUE TITLE
Hash (#) in filename 

### ISSUE THREAD

**Issue by craigwillis85** [microsoftgraph/msgraph-sdk-php#106]
Hi

I'm attempting to send a file to OneDrive using the following code:

        $uri = "/me/drive/items/$folderId/children('{$fileName}')/content";

        $graph = $this->graph->create($user);
        $client = $this->graph->createClient();

        $item = $graph->createRequest("PUT", $uri)
            ->attachBody($fileContent)
            ->setReturnType(Model\DriveItem::class)
            ->execute($client);

This works great if `$fileName` is something like `Test.doc`

But for some reason, when the filename has a hash (#) in the filename, then I get an error:

    object(Microsoft\Graph\Model\DriveItem)#1509 (1) {
      ["_propDict":protected]=>
      array(1) {
        ["error"]=>
        array(3) {
          ["code"]=>
          string(10) "BadRequest"
          ["message"]=>
          string(36) "Bad Request - Error in query syntax."
          ["innerError"]=>
          array(2) {
            ["request-id"]=>
            string(36) "ff3fe15f-b1ee-4e92-8abd-2400b1c1b5cf"
            ["date"]=>
            string(19) "2018-10-04T14:30:51"
          }
        }
      }

Can someone possibly clarify if this is a bug or actual behaviour (i.e. you cannot have a # in a filename)

Thanks

EDIT:

StackOverflow question: https://stackoverflow.com/questions/40914114/how-to-install-a-specific-version-of-package-using-composer

**Comment by MIchaelMainer** [comment]
This should be expected behavior. I don't know if it is okay or not in this context to have a hashtag in a URL, but I do know that it can't be in the URL as you have issued it.

You should URL encode it so it doesn't get processed as a URL fragment.

# = %23
