### ISSUE TITLE
Upload file to Microsoft One Drive directly without login

### ISSUE THREAD

**Issue by usamamashkoor** [microsoftgraph/msgraph-sdk-php#107]
Hi i have a website and on the website i have my employees and i want my employees to upload their documents to my Microsoft one drive directly without any login.

is their a way i can do this because i want my users to feel like they are just uploading a file without any Microsoft login but in the back end i want the files to be uploaded to my Microsoft One drive is their a way i can achieve this using PHP  ...?

I have search the google but in the stack over flow i can only find the examples which require user login.

any help would be great.

Thanks & Regards

**Comment by psignoret** [comment]
How do you plan to ensure that the people uploading files to your OneDrive are actually your employees?

**Comment by MIchaelMainer** [comment]
Here's an example using the client credential flow:
https://github.com/cbales/oauth-client-credential-flow.

What you want to do won't feasible in a secure manner from the client (browser). 

I'm curious, is your backend Node or PHP as you have this duplicate question? 
https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/123

Upload an item
https://github.com/microsoftgraph/msgraph-sdk-php/wiki/Example-calls#upload-an-item

**Comment by MIchaelMainer** [comment]
Closing as no response in 12 days.
