### ISSUE TITLE
How to change access token expiration time

### ISSUE THREAD

**Issue by kishanappringer** [microsoftgraph/msgraph-sdk-php#1083]
Hi Team, 

I need to help you, I want to change the access token expiration time using the code please send me to reference of the code as soon as possible.
Currently, I'm using follow the code to get an access token, It's working fine 
 $oauthClient = new \League\OAuth2\Client\Provider\GenericProvider([
            'clientId'                => env('OAUTH_APP_ID', ''),
            'clientSecret'            => env('OAUTH_APP_SECRET', ''),
            'redirectUri'             => env('OAUTH_REDIRECT_URI', ''),
            'urlAuthorize'            => env('OAUTH_AUTHORITY', 'https://login.microsoftonline.com/common') . env('OAUTH_AUTHORIZE_ENDPOINT', '/oauth2/v2.0/authorize'),
            'urlAccessToken'          => env('OAUTH_AUTHORITY', 'https://login.microsoftonline.com/common') . env('OAUTH_TOKEN_ENDPOINT', '/oauth2/v2.0/token'),
            'urlResourceOwnerDetails' => '',
            'scopes'                  => env('OAUTH_SCOPES', '')
        ]);

        $accessToken = $oauthClient->getAccessToken('authorization_code', [
            'code' => $_GET['code']
        ]);
But the access token expires after some time so please help me.

Thanks
Kishan

**Comment by Ndiritu** [comment]
@kishanappringer please refer to the PHP League OAuth2 client docs section titled [`Refreshing a Token`](https://oauth2-client.thephpleague.com/usage/)

**Comment by kishanappringer** [comment]
@Ndiritu Ok Thanks.
