### ISSUE TITLE
showInAddressList returning 'null'

### ISSUE THREAD

**Issue by ryanfurtner** [microsoftgraph/msgraph-sdk-php#109]
Hey,

I am working on a project where I am pulling in a few of the standard Graph fields like 'mobilePhone', 'officeLocation' etc. I have set 'Show in global address list' to Yes or No (https://i.imgur.com/Goci5Kd.png) but still get 'null', where all other fields work fine.

Any clues?

**Comment by MIchaelMainer** [comment]
I don't have an idea about the interaction between the Show in global address list setting and the Graph service API. Your best bet is StackOverflow.
