### ISSUE TITLE
How to add header in my code

### ISSUE THREAD

**Issue by dream811** [microsoftgraph/msgraph-sdk-php#1104]
This is my result data
` resulted in a `403 Forbidden` response: {"error":{"code":"Forbidden","message":"{\"error\":{\"code\":\"Forbidden\",\"message\":\"MS-APP-ACTS-AS header needs to be set for application context requests.\",\"details\":[],\"innererror\":{\"code\":\"MissingUserIdHeaderInAppContext\"}}}","innerError":{"date":"2023-01-06T06:06:51","request-id":"108646c7-080b-4be9-be93-b6fd83aa81b6","client-request-id":"108646c7-080b-4be9-be93-b6fd83aa81b6"}}} in

''''

    $guzzle = new \GuzzleHttp\Client();
    $tenantId = '*******4f9010';
    $url = 'https://login.microsoftonline.com/' . $tenantId . '/oauth2/v2.0/token';
    $token = json_decode($guzzle->post($url, [
        'form_params' => [
            'client_id' => '*****',//clientid
            'client_secret' => '*****',//clientsecret
            'scope' => 'https://graph.microsoft.com/.default',
            'grant_type' => 'client_credentials',
        ],
    ])->getBody()->getContents());
    echo $accessToken = $token->access_token;
    echo "<br>";
    $graph = new Graph();
    $graph->setAccessToken($accessToken);
    $docGrabber = $graph->createCollectionRequest("GET", '/teams/[teamid]/schedule/shifts?$filter=sharedShift/startDateTime ge 2023-01-05T06:00:00.000Z and sharedShift/endDateTime le 2023-01-06T06:00:00.000Z');
    $docs = $docGrabber->getPage();
''''

Please let me know how to add MS-APP-ACTS-AS

**Comment by dream811** [comment]
I found the solution.

**Comment by mnissen1337** [comment]
Hi @dream811. What was your solution? I am doing it through Python but I get the same error. I guess the same solution as in JS might work for Python. Thanks.
