### ISSUE TITLE
Broken link in Docs.  

### ISSUE THREAD

**Issue by devmikromike** [microsoftgraph/msgraph-sdk-php#1128]
Hello

Please update this page:
https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-php-sdk-2-0-0-rc5-is-now-available/

Link for See an [example](https://github.com/microsoftgraph/msgraph-sdk-php/blob/docs/kiota-preview/docs/Examples.md#customizing-middleware-configuration) on how to customize middleware.

is broken.

Thanks MikroMike.

**Comment by Ndiritu** [comment]
@isvargasmsft could we update the blog? Correct URL is https://github.com/microsoftgraph/msgraph-sdk-php/blob/feat/kiota-preview/docs/Examples.md#customizing-middleware-configuration

**Comment by isvargasmsft** [comment]
On this now.

**Comment by isvargasmsft** [comment]
Updated, thank you very much.
