### ISSUE TITLE
Where to access the docs (msgraph-sdk-php/docs/index.html)

### ISSUE THREAD

**Issue by jozeflambrecht** [microsoftgraph/msgraph-sdk-php#113]
Hi there,

A simple question, but how can I access the docs (msgraph-sdk-php/docs/index.html), without downloading every single file? I tried downloading the entire repository, but the docs are not included. Are they hosted somewhere?

Thank you!

**Comment by MIchaelMainer** [comment]
The docs are accessible through the wiki.

https://github.com/microsoftgraph/msgraph-sdk-php/wiki

**Comment by jozeflambrecht** [comment]
My question is how I can access msgraph-sdk-php/docs/index.html from my browser. The wiki provides the link to the source code of the docs.
