### ISSUE TITLE
Return for \Microsoft\Graph\Model\StaffAvailabilityItem::getAvailabilityItems should be an array

### ISSUE THREAD

**Issue by skeemer** [microsoftgraph/msgraph-sdk-php#1134]
I believe this should be an array according to what I see from usage and the docs.

https://github.com/microsoftgraph/msgraph-sdk-php/blob/1c922e9699ef86b43fa661b7808031711e014218/src/Model/StaffAvailabilityItem.php#L31

```
  * @return AvailabilityItem[]|null The availabilityItems 
```

https://learn.microsoft.com/en-us/graph/api/resources/staffavailabilityitem?view=graph-rest-1.0

**Comment by skeemer** [comment]
On a further look, this doesn't seem to even be mapping correctly because the $_propDict contains the whole array.

**Comment by Ndiritu** [comment]
@skeemer  unfortunately this is a currently known issue with v1.x of our SDK - where an array of objects should be returned instead. Fixing this required a breaking change that is available in our current v2.x Release Candidates.

If you'd prefer to stick to v1, here's a hacky workaround:
```php
$availabilityItems = array_map(fn ($item) => new AvailabilityItem($item), $staffAvailabilityItem->getAvailabilityItems()->getProperties()['availabilityItems']);
```

**Comment by Ndiritu** [comment]
@skeemer  unfortunately this is a currently known issue with v1.x of our SDK - where an array of objects should be returned instead. Fixing this required a breaking change that is available in our current v2.x Release Candidates.

If you'd prefer to stick to v1, here's a hacky workaround:
```php
$availabilityItems = array_map(fn ($item) => new AvailabilityItem($item), $staffAvailabilityItem->getAvailabilityItems()->getProperties()['availabilityItems']);
```

**Comment by skeemer** [comment]
That's exactly what I did so my code wouldn't break when it was fixed.

**Comment by skeemer** [comment]
As I side note, I'm not sure where this is breaking, but it's always UTC timezone even though the times don't match that.
