### ISSUE TITLE
[2.0.0-RC13] Wrong Request builders for Calendar delta

### ISSUE THREAD

**Issue by Robertbaelde** [microsoftgraph/msgraph-sdk-php#1152]
Hi, 

It looks like something goes wrong with the generation of `DeltaRequestBuilder` classes for the CalendarView/Delta endpoints. For example the required startdatetime & enddatetime parameters are missing from the urlTemplate and `CalendarDeltaRequestQueryParams` classes. 

I guess that this is an issue with the openAPI spec that the SDK is generated on. (If I understand the new Kiota flow correctly). What is the best workflow to resolve this issue?

**Comment by Ndiritu** [comment]
@Robertbaelde thanks for raising this. Yes, this is an issue with our OpenAPI spec. Will link the relevant tracking issue.
