### ISSUE TITLE
Update public handwritten docs and tutorials to use Kiota version of SDK

### ISSUE THREAD

**Issue by Ndiritu** [microsoftgraph/msgraph-sdk-php#1158]
Tracking documentation artifacts that need updating before/once we go GA with the Kiota SDK:
- [x] [Use SDKs](https://learn.microsoft.com/en-us/graph/sdks/sdks-overview?context=graph%2Fapi%2F1.0&view=graph-rest-1.0)
- [x] [Build PHP apps with Microsoft Graph](https://learn.microsoft.com/en-us/graph/tutorials/php?tabs=aad)

Feel free to add more @isvargasmsft

**Comment by Ndiritu** [comment]
@isvargasmsft should we reach out to Jason to update [this tutorial](https://learn.microsoft.com/en-us/graph/tutorials/php?tabs=aad)?

**Comment by isvargasmsft** [comment]
> @isvargasmsft should we reach out to Jason to update [this tutorial](https://learn.microsoft.com/en-us/graph/tutorials/php?tabs=aad)?

Yes, please. 

CC: @jasonjoh

**Comment by isvargasmsft** [comment]
https://github.com/microsoftgraph/microsoft-graph-docs/pull/20527

**Comment by jasonjoh** [comment]
https://github.com/microsoftgraph/microsoft-graph-training/issues/153
