### ISSUE TITLE
/me request is only valid with delegated authentication flow.

### ISSUE THREAD

**Issue by oussamamadjmaa** [microsoftgraph/msgraph-sdk-php#1163]
Can you help me with this error, what did i do wrong or what i didn't setup correctly

Client error: `GET https://graph.microsoft.com/v1.0/me` resulted in a `400 Bad Request` response: {"error":{"code":"BadRequest","message":"/me request is only valid with delegated authentication flow.","innerError":..

**Comment by MahaEast** [comment]
Same here

**Comment by Ndiritu** [comment]
Hi @oussamamadjmaa, @MahaEast 

To use `/me` your application will require a user to sign in and grant your app permission to do various operations. This means having a front-end client to redirect to the Microsoft Identity page for the user to sign in and consent to permissions.

If you your application is a daemon/server application, you should enable "application permissions" on Azure AD when registering your app, and you can only call URLs with the `/users/[your user email/user ID]/...`  prefix e.g. `/me/messages` becomes `/users/[user ID]/messages`

See these for more on how to fetch a valid access token for the two scenarios above:
- [Delegated Permissions](https://learn.microsoft.com/en-us/graph/auth-v2-user)
- [Application permissions](https://learn.microsoft.com/en-us/graph/auth-v2-service)

Also, we're getting close to releasing a new version of the SDK. If your scenario, permits, kindly consider using the[ `2.0.0-RC13` release](https://packagist.org/packages/microsoft/microsoft-graph#2.0.0-RC13). It handles authentication for you and provides a fluent experience e.g. `$graphClient->usersById('userID')->messages()->get()`. Setup instructions and some samples can be found [here](https://github.com/microsoftgraph/msgraph-sdk-php/tree/feat/kiota-preview)
