### ISSUE TITLE
Model\Message::class isRemoved() Incremental changes

### ISSUE THREAD

**Issue by jozeflambrecht** [microsoftgraph/msgraph-sdk-php#118]
To get incremental changes to messages in a folder, would it be easy to implement `$message->isRemoved()` on the Message model? What would be the best way to determine if the message was removed?

**Comment by MIchaelMainer** [comment]
If you intend to do a polling client, yes, implementing `$message->isRemoved()` and calling `GET /me/messages/messageId` and checking whether the response is a 404 would be a straightforward way to do that. 

You can also subscribe for changes to messages by using the notification API. https://docs.microsoft.com/en-us/graph/webhooks?toc=./ref/toc.json&view=graph-rest-1.0
