### ISSUE TITLE
How to get ID from /me/mailFolders or /me/mailFolders/folder_id/messages API

### ISSUE THREAD

**Issue by vasim-seta** [microsoftgraph/msgraph-sdk-php#1186]
I want to get emails from inbox and for that I will need inbox folder id, so how can I get folder id ? 

If I want to call this API /me/mailFolders/$folder_id/messages, I will need folder id.

I have checked Microsoft\Graph\Model\MailFolder::class for a method if any to return ID but I can't see any. I can see it is coming in response but as all fields returned are Private part of that class I'm not able to directly retrieve it.

Here is my example code:

$result = $this->graph->createRequest("GET", '/me/mailFolders')
                ->setReturnType(Microsoft\Graph\Model\MailFolder::class)
                ->execute();

foreach ($folders as $folder) {
      if($folder->getDisplayName() == "Inbox") {
              $folder_id = ?
      }
}

Echoed response:
[0] => Microsoft\Graph\Model\MailFolder Object
        (
            [_propDict:protected] => Array
                (
                    [id] => AAMkADEyMjRhYTVlLTE3OTctNGQ2Ni04NDg1asdaLTcwNzFjZTNiODQzasdOAAuAAAAAAAGZgAbShCiR4lFfvRq93A65ZAQAwcPCRPSx3So_AamaFxPrWAAExwcgjAAA=
                    [displayName] => Archive
                    [parentFolderId] => AAMkADEyMjRhYTVlLTE3OTctNGQ2Ni04NDsdgg1LTcwNzFjZTNiODQzOAAzxcuAAAAAAAGZgAbShCiR4lFRq93A65ZAQAwcPCRPSx3So_AamaFxPrWAAAAAAEIAAA=
                    [childFolderCount] => 0
                    [unreadItemCount] => 0
                    [totalItemCount] => 0
                    [sizeInBytes] => 0
                    [isHidden] => 
                )

        )

Can please someone helm with this, thanks in advance.

**Comment by Ndiritu** [comment]
@vasim-seta you can call `getId()` on any model.
`MailFolder` extends [Entity](https://github.com/microsoftgraph/msgraph-sdk-php/blob/dev/src/Model/Entity.php)

**Comment by vasim-seta** [comment]
> getId()

Thank you for your response. It worked, I think there is lack of details in documentation.

Again Big Thank you [Ndiritu](https://github.com/Ndiritu)
