### ISSUE TITLE
Skip generation for the /me endpoints 

### ISSUE THREAD

**Issue by isvargasmsft** [microsoftgraph/msgraph-sdk-php#1191]
/me and /users/{id} are effectively identical from a metadata perspective. This presents an opportunity to reduce build time further (~17% from our early measurements) while minimally impacting the experience for users.

TODO:
- [ ] in graph core, add a UrlReplaceOption request option. It needs to implement the interface and provide accessors for Enabled (default true) as well as "ReplacementPairs" (map[string]string), default [/users/me-token-to-replace, /me]
- [ ] in graph core add a UrlReplaceHandler that implements the middleware handler, replaces the tokens in the URLs, and traces its activity with the telemetry.
- [ ] in graph core, add this new handler as part of the defaults
- [ ] in code generator, update the PHP weekly generation steps to exclude /me (exclude paths, /me and /me/**, or something similar)
- [ ] trigger a code generation from beta
- [ ] in that newly generated PR, update the dependency to core
- [ ] in that newly generated PR, cherry pick the first commit from #333
- [ ] update the snippets generation to map inline types for /me to /users

**Comment by isvargasmsft** [comment]
@Ndiritu could you please add this to the GA requirements?

**Comment by Ndiritu** [comment]
I'm inclined towards us not needing to do this because PHP isn't compiled, so we don't have build time concerns.
This change would also introduce an extra step for developers of apps that use delegated permissions where they'd have to get the user's identity for them to construct a `/users/{user-id}` request.
But open to other thoughts.

cc: @SilasKenneth @shemogumbe

**Comment by isvargasmsft** [comment]
@baywet I'd like your ideas on this specific for PHP.

**Comment by Ndiritu** [comment]
I realise that I had misunderstood how this would work. I was concerned that we would be deprecating the `me()` fluent method which isn't the case from looking at Go. Instead we'll just be replacing the "temporary user ID" with `/me`/ before making the request.

This would definitely improve the SDK without hurting the dev experience.

**Comment by isvargasmsft** [comment]
Thank you very much for clarifying Philip. Let's add it to the queue. 

CC: @shemogumbe

**Comment by Ndiritu** [comment]
closed by
https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/1000
https://github.com/microsoftgraph/msgraph-sdk-php-core/pull/110
