### ISSUE TITLE
API version

### ISSUE THREAD

**Issue by catalin-luntraru** [microsoftgraph/msgraph-sdk-php#12]
This api sdk library uses https://graph.microsoft.com/ with v1.0, but if you have a look at the calendar api here https://msdn.microsoft.com/office/office365/APi/calendar-rest-operations and check the v2.0 checkbox at the top, you will see that this sdk actually uses https://outlook.office.com/api/ with v2.0

I know this is true because I tried the POST body parameters of the version 1.0 and it gave me an error.

Can someone explain the different names and versions of these apis?
I tried going to https://developer.microsoft.com/en-us/graph/ but there's no information about the api versions.

Thank you.

**Comment by cbales** [comment]
Microsoft Graph is actually an aggregator service that exposes these APIs in a uniform way. The version numbers for graph (v1.0, beta) do not correlate in any way to the underlying service APIs (v1.0, v2.0 in Outlook). I realize this is pretty confusing.
Is there something you were unable to accomplish using Graph and Outlook? If you could give me a specific scenario, I can check that Graph is getting the latest version of the Outlook API.

**Comment by catalin-luntraru** [comment]
Thank you for the response, I understand now.
