### ISSUE TITLE
No methods for 'Other' phone numbers in the Contact Model?

### ISSUE THREAD

**Issue by louisl** [microsoftgraph/msgraph-sdk-php#120]
I can add an 'other' phone number to a contact on outlook.office.com, but It doesn't appear in the returned data when retrieving the contact with the API and looking at the Contact model I see no methods for Other phone number types?

Also why doesn't the Contact model use the Phone model for phone numbers which incidentally does have types. I'm a little confused here.

**Comment by MIchaelMainer** [comment]
The lack of the 'other' and the other phone categories

**Comment by MIchaelMainer** [comment]
No response and not a client issue.

**Comment by louisl** [comment]
Haven't had a chance to jump back onto this job yet.
