### ISSUE TITLE
Access is denied. Check credentials and try again

### ISSUE THREAD

**Issue by phamvanhiepvn** [microsoftgraph/msgraph-sdk-php#1204]
Hi Guys,

Could you help check and explain this error, I'm creating a new application and send mail by my coding, but it always responds for me: \"code\":\"ErrorAccessDenied\",\"message\":\"Access is denied. Check credentials and try again.\"}

Thank you

**Comment by Ndiritu** [comment]
@phamvanhiepvn what version of the SDK are you using? Are you able to share a code snippet?

**Comment by phamvanhiepvn** [comment]
Hi @Ndiritu, I using SDK "^1.5", Actually I also try change to ^1.9 but it' same error
it is my code to get the access token: 
```
$url = 'https://login.microsoftonline.com/' . config('office365mail.tenant') . '/oauth2/v2.0/token';
        $token = json_decode($guzzle->post($url, [
            'form_params' => [
                'client_id' => config('office365mail.client_id'),
                'client_secret' => config('office365mail.client_secret'),
                'scope' => 'https://graph.microsoft.com/.default',
                'grant_type' => 'client_credentials',
            ],
        ])->getBody()->getContents());
```
there is no error, I still saw the token
And sending mail
```
$graph->createRequest("POST", "/users/" . $email->getFrom()[0]->getAddress() . "/sendmail")
                ->attachBody($messageBody)
                ->setReturnType(\Microsoft\Graph\Model\Message::class)
                ->execute();
```
when sending mail it returns the above error

**Comment by Ndiritu** [comment]
@phamvanhiepvn please confirm that you've enabled the [`Mail.Send`](https://learn.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=http#permissions) permissions on your app
