### ISSUE TITLE
We should align with other languages and make initialization easier

### ISSUE THREAD

**Issue by isvargasmsft** [microsoftgraph/msgraph-sdk-php#1214]
As discussed, we'd like to find a way to abstract these 3 lines of code:
```php
$authProvider = new PhpLeagueAuthenticationProvider($tokenRequestContext, $scopes);
$requestAdapter = new GraphRequestAdapter($authProvider);
$graphServiceClient = new GraphServiceClient($requestAdapter);
```
And only request from the developer to specify the context, the scope and its required values. 

Notes:
- PHP doesn't support construction overloads, used in other languages for this purpose.

**Comment by baywet** [comment]
solutions about the constructor overload are:
- configuration class parameter
- union type parameter
- static builder method for the one with the request adapter, and use the main constructor for the context/scopes parameters

During internal discussions it seemed that the latter would offer a better experience to end users. To be validated.
