### ISSUE TITLE
Send email -> impossible to retrieve email id

### ISSUE THREAD

**Issue by pdolinaj** [microsoftgraph/msgraph-sdk-php#1250]
I was following the example of how to send email but after sending, I am unable to retrieve the email id. Is this a bug or it is not implemented yet? thank you

**Comment by Ndiritu** [comment]
@pdolinaj when calling `/me/sendMail` the [expected response](https://learn.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=http) is a 202 status code without response body. This guarantees that the message was delivered.

Alternatively, you can first [create a draft message](https://learn.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&tabs=http) which returns the created message's ID, then [send the draft message](https://learn.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&tabs=http)

You can also get the message ID by expanding the "messages" in the `sent items` of the sender/`inbox` of the recipient i.e. `/me/mailFolders/sentitems/messages` or `/me/mailFolders/inbox/messages` but it may be harder to validate that the most recent message ID is the one you sent.

Hope that helps

**Comment by Ndiritu** [comment]
@pdolinaj resolved?

**Comment by pdolinaj** [comment]
My original idea was to create an email and grab the ID together with conversation ID so I could track replies to that email and pull all the replies and store locally in database. My workaround to get the ID, immediately after sending the email, I retrieve past XX emails from the mailbox and try to match that email based on sender email / recipient email / subject which I believe will work just fine. 

Would you be able to provide working example of how to create Draft email, get the ID and send draft message in PHP? Thank you

**Comment by Ndiritu** [comment]
[Create Draft Email & get ID in response](https://learn.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&tabs=http)
[Send draft email](https://learn.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&tabs=http#example-1-send-an-existing-draft-message)

The Reference docs contain the expected request and response payloads.

You could also consider using our [v2 Release Candidate](https://github.com/microsoftgraph/msgraph-sdk-php/tree/feat/kiota-preview#install-the-sdk) that should be stable soon.
