### ISSUE TITLE
ScheduleInformation::getScheduleItems() returns a single instance

### ISSUE THREAD

**Issue by BenRutlandWeb** [microsoftgraph/msgraph-sdk-php#1262]
`\Microsoft\Graph\Model\ScheduleInformation::getScheduleItems()` should return a collection of `Microsoft\Graph\Model\ScheduleItem` 
 according to https://learn.microsoft.com/en-us/graph/api/resources/scheduleinformation?view=graph-rest-1.0#properties but it returns only one instance. 

The props passed to `ScheduleItem` is a collection which causes the getters to always return null.

**Comment by Ndiritu** [comment]
@BenRutlandWeb sorry about this. It's a known issue in our version `1.x` SDKs

Here's a similar issue with a suggested workaround - https://github.com/microsoftgraph/msgraph-sdk-php/issues/1134#issuecomment-1411905583

Will pin the known issues and workarounds for v1.x. If you can, please consider trying out our [2.0.0-RC](https://github.com/microsoftgraph/msgraph-sdk-php/tree/feat/kiota-preview#get-started-with-the-microsoft-graph-sdk-for-php) and share any feedback.
