### ISSUE TITLE
Wrong baseUrl after upgrading to 2.0.0-RC15

### ISSUE THREAD

**Issue by hubipe** [microsoftgraph/msgraph-sdk-php#1263]
Hello,
after upgrading from RC14 to RC15 and updating graph initialization from:

```php
$graphServiceClient  = new GraphServiceClient($this->getGraphRequestAdapter());
```

to

```php
$graphServiceClient =  GraphServiceClient::createWithRequestAdapter($this->getGraphRequestAdapter());
```

the requests started to failing on HTTP 404 response code. The problem is with the baseUrl. GraphServiceClient::createWithRequestAdapter sets baseUrl from the second argument $nationalCloud as a (default) value _https://graph.microsoft.com_. The URL of the requested resource then looks like:

`https://graph.microsoft.com/drives/<driveId>/items/<itemId>/preview`

![image](https://github.com/microsoftgraph/msgraph-sdk-php/assets/617880/fac62211-1dfb-4a2d-be90-768d0932c632)

but should look like

`https://graph.microsoft.com/v1.0/drives/<driveId>/items/<itemId>/preview` (notice the „/v1.0“)

![image](https://github.com/microsoftgraph/msgraph-sdk-php/assets/617880/977d299d-8195-4199-a4d7-c5d788243510)

I've handled wrong default baseUrl by passing second argument to the createWithRequestAdapter method like this:

```php
$requestAdapter = $this->getGraphRequestAdapter();
return GraphServiceClient::createWithRequestAdapter($requestAdapter, $requestAdapter->getBaseUrl());
```

Then the base URL (nationalCloud) is correctly set as _https://graph.microsoft.com/v1.0_, but I think this method should set the baseUrl correctly by default.

**Comment by Ndiritu** [comment]
@hubipe thanks for reporting this. It should be resolved from [2.0.0-RC16](https://github.com/microsoftgraph/msgraph-sdk-php/releases/2.0.0-RC16)
