### ISSUE TITLE
"BadRequest", "message": "Query option '$top' was specified more than once

### ISSUE THREAD

**Issue by robtesch** [microsoftgraph/msgraph-sdk-php#127]
Recently I've been getting a lot of issues when trying to retrieve a user's email messages. I have followed the instructions on here about pagination in order to get 100 emails at a time as follows:

`$messageGrabber = $graph->createCollectionRequest('GET', $userId . '/messages?$select=' . $select . '&$filter=' . $filter)
                                ->setReturnType(Message::class)
                                ->setPageSize(100);`

When doing this as per the documentation, i often (but not always) get the error message below back:

`"BadRequest", "message": "Query option '$top' was specified more than once`

Where am i going wrong with this? I don't really want to just exclude that option, since I want to control how many messages I get back per call.

**Comment by MIchaelMainer** [comment]
It sounds like the client is intermittently generating duplicate $top params. How often are you getting this error? Can you share a sanitized capture file showing the request and response?

**Comment by MIchaelMainer** [comment]
No response. Please reopen if you are still concerned with this error.
