### ISSUE TITLE
Wrong php version

### ISSUE THREAD

**Issue by Izet0004** [microsoftgraph/msgraph-sdk-php#1270]
"php: ^8.0 || ^7.3" Is not correct, >= 8.0.2 is required

`Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.2". You are running 7.4.33. in /var/www/html/vendor/composer/platform_check.php on line 24
`

composer.json:

`{
    "require": {
        "sendgrid/sendgrid": "^8.0",
        "google/recaptcha": "^1.2",
        "vlucas/phpdotenv": "^5.4",
        "league/csv": "^9.8",
        "microsoft/microsoft-graph": "^1.99"
    },
    "autoload": {
        "psr-4": {
            "Izet\\Www\\": "src/"
        },
        "classmap": [
            "includes"
        ]
    }
}`

The dependency

`        {
            "name": "symfony/deprecation-contracts",
            "version": "v3.0.2",
            "source": {
                "type": "git",
                "url": "https://github.com/symfony/deprecation-contracts.git",
                "reference": "26954b3d62a6c5fd0ea8a2a00c0353a14978d05c"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/symfony/deprecation-contracts/zipball/26954b3d62a6c5fd0ea8a2a00c0353a14978d05c",
                "reference": "26954b3d62a6c5fd0ea8a2a00c0353a14978d05c",
                "shasum": ""
            },
            "require": {
                "php": ">=8.0.2"
            },
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-main": "3.0-dev"
                },
                "thanks": {
                    "name": "symfony/contracts",
                    "url": "https://github.com/symfony/contracts"
                }
            },
            "autoload": {
                "files": [
                    "function.php"
                ]
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Nicolas Grekas",
                    "email": "p@tchwork.com"
                },
                {
                    "name": "Symfony Community",
                    "homepage": "https://symfony.com/contributors"
                }
            ],
            "description": "A generic function and convention to trigger deprecation notices",
            "homepage": "https://symfony.com",
            "support": {
                "source": "https://github.com/symfony/deprecation-contracts/tree/v3.0.2"
            },
            "funding": [
                {
                    "url": "https://symfony.com/sponsor",
                    "type": "custom"
                },
                {
                    "url": "https://github.com/fabpot",
                    "type": "github"
                },
                {
                    "url": "https://tidelift.com/funding/github/packagist/symfony/symfony",
                    "type": "tidelift"
                }
            ],
            "time": "2022-01-02T09:55:41+00:00"
        },`

**Comment by Ndiritu** [comment]
@Izet0004 I'm unable to reproduce this error. The set of dependencies provided works with PHP 7.4.33
```cli
"require": {
        "sendgrid/sendgrid": "^8.0", 
        "google/recaptcha": "^1.2", 
        "vlucas/phpdotenv": "^5.4", 
        "league/csv": "^9.8", 
        "microsoft/microsoft-graph": "^1.99"
    }
```
Please confirm the list of dependencies you've provided is correct

**Comment by Izet0004** [comment]
> @Izet0004 I'm unable to reproduce this error. The set of dependencies provided works with PHP 7.4.33
> 
> ```
> "require": {
>         "sendgrid/sendgrid": "^8.0", 
>         "google/recaptcha": "^1.2", 
>         "vlucas/phpdotenv": "^5.4", 
>         "league/csv": "^9.8", 
>         "microsoft/microsoft-graph": "^1.99"
>     }
> ```
> 
> Please confirm the list of dependencies you've provided is correct

I can confirm that's my composer.json.


The issue is inside composer.lock, 'symfony/deprecation-contracts', it requires '>=8.0.2'

**Comment by Ndiritu** [comment]
@Izet0004  That's interesting. We don't lock our dependency version within this library - we don't ship with a `composer.lock`.
Please consider removing your composer.lock and reinstalling dependencies, otherwise please share your composer.lock file.

**Comment by Izet0004** [comment]
@Ndiritu I did try removing composer.lock and install dependencies again, same error.
I did force composer install --ignore-platform-req=php so i could get it working

But heres the composer.lock file
https://pastebin.com/vWFYQLMi

**Comment by Ndiritu** [comment]
From the lock file, I see `google/recaptcha`  [1.3](https://packagist.org/packages/google/recaptcha#1.3.0) meaning you're running PHP >=8? 
Please confirm the PHP version in the output of `composer -vvv about`?

**Comment by Izet0004** [comment]
with PHP 8.0.9 on Windows NT / 10.0 (Local)

But docker PHP 7.4.33 (I am using same version as my prod server)

**Comment by Ndiritu** [comment]
@Izet0004 yes, I think running composer on your local should use the PHP version on your local machine. 
To install, configure & run composer for your docker container, check these out:
- https://stackoverflow.com/questions/51443557/how-to-install-php-composer-inside-a-docker-container
- https://www.w3docs.com/snippets/php/how-to-install-php-composer-inside-a-docker-container.html

**Comment by Izet0004** [comment]
@Ndiritu 

Alright, sorry for bothering you :)

**Comment by Ndiritu** [comment]
@Izet0004 No worries! Learnt something in the process.
