### ISSUE TITLE
2.x - Need support for OneDrive's itemWithPath

### ISSUE THREAD

**Issue by jasonjoh** [microsoftgraph/msgraph-sdk-php#1279]
OneDrive lets you get items with a path syntax (rather than an ID), like:

```http
GET /drives/{drive-id}/root:/{item-path}
GET /me/drive/root:/{item-path}
```

Other Kiota-based SDKs already expose this with an `itemWithPath` function.

## C#

```csharp
var myDrive = await graphClient.Me.Drive.GetAsync();
var uploadSession = await graphClient.Drives[myDrive?.Id]
    .Items["root"]
    .ItemWithPath(itemPath)
    .CreateUploadSession
    .PostAsync(uploadSessionRequestBody);
```

## Java

```java
final UploadSession uploadSession = graphClient.me().drive().root()
    .itemWithPath(itemPath).createUploadSession(uploadParams).buildRequest()
    .post();
```

**Comment by Ndiritu** [comment]
@jasonjoh the .NET SDK includes some custom/handwritten extension methods e.g. [`itemWithPath`](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blame/feature/5.0/src/Microsoft.Graph/Extensions/DriveItemRequestBuilderExtensions.cs) on the Drive request builders.
Can't find a solution for PHP that would keep the fluent experience and not "corrupt" Kiota's generation to make accommodations for Graph.

PHP's equivalent at the moment would be:
```php
$uploadSession = $graphServiceClient->drives()->byDriveId('driveId')->items()->byDriveItemId('root:/{itemPath}:')->createUploadSession()->post($uploadSessionBody)->wait();
```

@baywet any thoughts?

**Comment by baywet** [comment]
yep to avoid over expansion, we only expand things on canonical paths when converting from OData to OpenAPI. This is annoying but avoids getting descriptions (and SDKs) that are impossible to do anything with.
@irvinesunday has been working on annotations that'd mean "yes yes, I know this isn't the canonical path, but expand it anyway" so we could use this surgically. I'm not sure where that work is at though.

Although the dotnet solution is working, it's kind of cheating and as far as I know no other language supports extension methods or an equivalent (even Go that technically could, throws errors when you define methods in other files to force you to keep the code at one place).
