### ISSUE TITLE
Add validate-pull-request once migrated to Kiota

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-php#1339]
Reference https://github.com/microsoftgraph/msgraph-sdk-php/pull/1333.

This is to enable phpstan for our static analysis requirement.

**Comment by Ndiritu** [comment]
@MIchaelMainer resolved in https://github.com/microsoftgraph/msgraph-sdk-php/commit/8dd1a2f22565df9085c7ca3f9f23f01ff89b1ba8
