### ISSUE TITLE
Create a Microsoft Graph client error: Uncaught Error: Class 'Microsoft\Graph\GraphServiceClient' not found in xxx.php

### ISSUE THREAD

**Issue by quyunet** [microsoftgraph/msgraph-sdk-php#1374]
I successfully installed Microsoft graph php sdk using the following documentation method:
[https://learn.microsoft.com/en-us/graph/sdks/sdk-installation#install-the-microsoft-graph-php-sdk](https://learn.microsoft.com/en-us/graph/sdks/sdk-installation#install-the-microsoft-graph-php-sdk)

The composer.json document configuration during installation is as follows: 
```
{
    "require": {
        "microsoft/microsoft-graph": "^1.108",
	"microsoft/microsoft-graph-core": "^2.0.0-RC10"
    }
}
```

But an error occurred when I executed the following document example:
[https://learn.microsoft.com/en-us/graph/sdks/create-client?tabs=php](https://learn.microsoft.com/en-us/graph/sdks/create-client?tabs=php)

error: Fatal error: Uncaught Error: Class 'Microsoft\Graph\GraphServiceClient' not found in /demo/test.php

The following is the test.php script:
```php
<?php
require 'vendor/autoload.php';

$tenantId = "xxxxxxxxxxxxxxx";
$clientId = "xxxxxxxxxxxxx";
$clientSecret = "xxxxxxxxxxxxxxxxxxxx";

use Microsoft\Graph\GraphServiceClient;
use Microsoft\Kiota\Abstractions\ApiException;
use Microsoft\Kiota\Authentication\Oauth\ClientCredentialContext;

$tokenRequestContext = new ClientCredentialContext(
    $tenantId,
    $clientId,
    $clientSecret
);
$graphServiceClient = new GraphServiceClient($tokenRequestContext);
print_r($graphServiceClient);
```
Why can't I find "Microsoft\Graph\GraphServiceClient"? do you need to install additional SDK libraries?

**Comment by Ndiritu** [comment]
@quyunet apologies for this. We're scheduled to release a stable `2.0.0` version of this SDK within the next few days, but looks like docs changes are live earlier.

Please consider using the latest RC for now. We don't expect to make any breaking changes before release.
```
{
    "require": {
        "microsoft/microsoft-graph": "^2.0.0-RC27",
        "microsoft/microsoft-graph-core": "@RC"
    }
}
```

**Comment by leejosh** [comment]
When doing it the way you described above.  I get errors with open-telemetry.

**PHP Error[2]: include(Fiber.php): failed to open stream: No such file or directory**

i only get this error when using the SDK that has open-telemetry as a dependency.

**Comment by Ndiritu** [comment]
@leejosh are you using RC-27? Please share a sample failing code sample?

**Comment by Ndiritu** [comment]
> @quyunet apologies for this. We're scheduled to release a stable `2.0.0` version of this SDK within the next few days, but looks like docs changes are live earlier.
> 
> Please consider using the latest RC for now. We don't expect to make any breaking changes before release.
> 
> ```
> {
>     "require": {
>         "microsoft/microsoft-graph": "^2.0.0-RC27",
>         "microsoft/microsoft-graph-core": "@RC"
>     }
> }
> ```

Update: version 2.0.0 is out.

**Comment by developer-itsapp2you** [comment]
```
{
    "config": {
        "allow-plugins": {
            "php-http/discovery": false
        }
    },
    "require": {
        "microsoft/microsoft-graph": "^2.11",
        "microsoft/microsoft-graph-core": "^2.1"
    }
}
```
Having same issue to me as well.
