### ISSUE TITLE
Client error: `GET https://graph.microsoft.com/v1.0/me` resulted in a `400 Bad Request` response: { "error": { "code": "BadRequest", "message": "Current authenticated context is not valid for this request. (truncated...)

### ISSUE THREAD

**Issue by abkiran** [microsoftgraph/msgraph-sdk-php#138]
How to solve this on PHP - Laravel?

"""
Client error: `GET https://graph.microsoft.com/v1.0/me` resulted in a `400 Bad Request` response:
{
  "error": {
    "code": "BadRequest",
    "message": "Current authenticated context is not valid for this request. (truncated...)
""" 
[AB#7583](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7583)

**Comment by MIchaelMainer** [comment]
You need to make sure you set a valid access token for the request.

**Comment by abkiran** [comment]
```
$url = 'https://login.microsoftonline.com/' . $tenantId . '/oauth2/token?api-version=1.0';
        $token = json_decode($guzzle->post($url, [
            'form_params' => [
                'client_id' => $clientId,
                'client_secret' => $clientSecret,
                'resource' => 'https://graph.microsoft.com/',
                'grant_type' => 'client_credentials',
            ],
        ])->getBody()->getContents());
        $accessToken = $token->access_token;
```

Is the above code is correct to get the access Token?

**Comment by MIchaelMainer** [comment]
It looks correct. Did you register the application? I suggest that you take a look at this:
https://github.com/microsoftgraph/msgraph-training-phpapp

**Comment by rps-repo** [comment]
I have the same issue and I am using PHP 7.2.  A token is being returned so I assume that part is valid.  If I change "me" to "users"  I do get back an object in the $user var.  

I changed this
```
        $user = $graph->createRequest("GET", "/me")
                      ->setReturnType(Model\User::class)
                      ->execute();
```
to this

```
        $user = $graph->createRequest("GET", "/users")
                      ->setReturnType(Model\User::class)
                      ->execute();
```

When I print_r $user it looks like this:

```
Array
(
    [0] => Microsoft\Graph\Model\User Object
        (
            [_propDict:protected] => Array
                (
                    [businessPhones] => Array
                        (
                            [0] => 4250000000
                        )

                    [displayName] => Tom Smith
                    [givenName] => Tom
                    [jobTitle] => 
                    [mail] => tom.smith@fpsys.onmicrosoft.com
                    [mobilePhone] => 
                    [officeLocation] => 
                    [preferredLanguage] => en-US
                    [surname] => Smith
                    [userPrincipalName] => tom.smith@fpsys.onmicrosoft.com
                    [id] => a93d6252-d655-4485-9d30-3d5214d7sfb1
                )

        )
)
```



$user->getGivenName() will not work.  I get the error:

ERROR - 2019-04-15 17:11:21 --> Severity: error --> Exception: Call to a member function getGivenName()

**Comment by Ndiritu** [comment]
Closing this since this is not an SDK issue & as there was no further feedback from @abkiran
