### ISSUE TITLE
API_VERSION not defined when using Beta API

### ISSUE THREAD

**Issue by AMGGroupLtd** [microsoftgraph/msgraph-sdk-php#1397]
When trying to instantiate Graph, you get an error stating that API_VERSION has not been defined.
Graph installed via Composer.
Code snippet that produces the error :

`
use Microsoft\Graph\Graph;
use Beta\Microsoft\Graph\Model as BetaModel;
$graph = new Graph();
`

Error thrown in file 'Graph.php' line 75
Line 75 : 
`
$this->_apiVersion = GraphConstants::API_VERSION;
`

The constant '**GraphConstants::API_VERSION**' is not getting defined.

Other constants appear to be fine.
If line 75 is replaced with 
`
$this->_apiVersion = 'beta';
`
The API works as expected.

Thanks
marl_scot

**Comment by Ndiritu** [comment]
Hi @AMGGroupLtd 

New `Graph` objects default to `v1.0`. Please try
```php

$graph = new Graph();
$graph->setApiVersion('beta');
```

**Comment by Ndiritu** [comment]
Also, please consider using our [Beta SDK](https://github.com/microsoftgraph/msgraph-beta-sdk-php)
We should be making it stable in a few days.

**Comment by AMGGroupLtd** [comment]
Hi @Ndiritu 
Thanks for that, but the error is being thrown as Graph is being instantiated, so its not possible to set the api version as you suggest.

**Comment by Ndiritu** [comment]
Please share the version of the SDK you're using as well your PHP version/setup environment. This currently works for me using SDK version 1.109.0 and PHP 7.4.33 CLI:

```php
use Microsoft\Graph\Graph;
use Beta\Microsoft\Graph\Model as BetaModel;

$graph = new Graph();
$graph->setApiVersion('beta');

```

**Comment by fonemi** [comment]
Same error here. In GraphConstants.php file (under microsoft-graph-core) there are 2 relevant constants:

```
const BETA_API_VERSION = "beta";
const V1_API_VERSION = "v1.0";
```

In the constructor function, one of these constants should be used.
