### ISSUE TITLE
Get Events from [start] to [end]

### ISSUE THREAD

**Issue by webdev522** [microsoftgraph/msgraph-sdk-php#140]
Hi,

I'd like to get events between start and end dates.

This is the code snippet I've tried. But it doesn't work correctly.
$startTime = new \DateTime('today midnight');
$startTime = $startTime->format('Y-m-d H:i:s');
$endTime = new \DateTime('tomorrow midnight');
$endTime = $endTime->format('Y-m-d H:i:s');
$events = $graph->createRequest("GET", "/me/events?startDateTime=$startTime&endDateTime=$endTime")
    						   ->setReturnType(Model\Event::class)
    						   ->execute();
`

It returns all of events. let me know the solution for it.

Regards.

=========================================
This is the result that I got on my end.

- [ICalUId]: 040000008200E00074C5B7101A82E008000000004064FF3AC7BFD401000000000000000010000000F660243807B2D14AB8B88F0C0788910E
- [Subject]: Christopher Callaghan vs. Ray Daniell Woodliff [2PM EST/11AM PST]
- [BodyPreview]: Hi there, Alison Almand is inviting you to a scheduled Zoom meeting. Join from PC, Mac, Linux, iOS or Android: https://GeorgiaReporting.zoom.us/j/994945168 or Visit https://georgiareporting.zoom.us/ Click "Join Meeting" Enter Meeting ID: 994
- [Start]: 2019-03-04T19:00:00.0000000
- [End]: 2019-03-04T22:00:00.0000000
- [Attendees]: Array ( [0] => Array ( [type] => required [status] => Array ( [response] => none [time] => 0001-01-01T00:00:00Z ) [emailAddress] => Array ( [name] => Alison Almand [address] => alisona@georgiareporting.com ) ) [1] => Array ( [type] => required [status] => Array ( [response] => none [time] => 0001-01-01T00:00:00Z ) [emailAddress] => Array ( [name] => EGCR-Scheduling [address] => scheduling@georgiareporting.com ) ) ) 
- [Organizer]: Microsoft\Graph\Model\Recipient Object ( [_propDict:protected] => Array ( [emailAddress] => Array ( [name] => Alison Almand [address] => alisona@georgiareporting.com ) ) ) 
------------------------------------------
- [ICalUId]: 040000008200E00074C5B7101A82E0080000000000000000000000000000000000000000330000007643616C2D556964010000007B43303432443230302D333144322D343739372D383443422D4446424443423730454633417D00
- [Subject]: Ricardo Godinez vs. Carl Gustason
- [BodyPreview]: Hi there, Scheduling Scheduling is inviting you to a scheduled Zoom meeting. Topic: Ricardo Godinez vs. Carl Gustason Time: Feb 13, 2019 11:00 AM Eastern Time (US and Canada) Join from PC, Mac, Linux, iOS or Android: https://GeorgiaReporting.
- [Start]: 2019-02-13T16:00:00.0000000
- [End]: 2019-02-13T18:00:00.0000000
- [Attendees]: Array ( [0] => Array ( [type] => required [status] => Array ( [response] => none [time] => 0001-01-01T00:00:00Z ) [emailAddress] => Array ( [name] => Diana Shin [address] => DianaS@georgiareporting.com ) ) [1] => Array ( [type] => required [status] => Array ( [response] => none [time] => 0001-01-01T00:00:00Z ) [emailAddress] => Array ( [name] => EGCR-Scheduling [address] => scheduling@georgiareporting.com ) ) ) 
- [Organizer]: Microsoft\Graph\Model\Recipient Object ( [_propDict:protected] => Array ( [emailAddress] => Array ( [name] => Diana Shin [address] => DianaS@georgiareporting.com ) ) ) 
------------------------------------------
- [ICalUId]: 040000008200E00074C5B7101A82E0080000000040F44EED2CBED4010000000000000000100000001A1F370C49FCA948AE9B07CAF7B17000
- [Subject]: Expert - Nancy Michalski, RN [ 1pm Eastern / 10am Pacific ]
- [BodyPreview]: Hi there, Alison Almand is inviting you to a scheduled Zoom meeting. Join from PC, Mac, Linux, iOS or Android: https://GeorgiaReporting.zoom.us/j/207766125 or Visit https://georgiareporting.zoom.us/ Click "Join Meeting" Enter Meeting ID: 207
- [Start]: 2019-02-21T18:00:00.0000000
- [End]: 2019-02-21T22:00:00.0000000
- [Attendees]: Array ( [0] => Array ( [type] => required [status] => Array ( [response] => none [time] => 0001-01-01T00:00:00Z ) [emailAddress] => Array ( [name] => Alison Almand [address] => alisona@georgiareporting.com ) ) [1] => Array ( [type] => required [status] => Array ( [response] => none [time] => 0001-01-01T00:00:00Z ) [emailAddress] => Array ( [name] => EGCR-Scheduling [address] => scheduling@georgiareporting.com ) ) ) 
- [Organizer]: Microsoft\Graph\Model\Recipient Object ( [_propDict:protected] => Array ( [emailAddress] => Array ( [name] => Alison Almand [address] => alisona@georgiareporting.com ) ) ) 
------------------------------------------
- [ICalUId]: 040000008200E00074C5B7101A82E0080000000020B60FCA8EBDD4010000000000000000100000008195C916C053DE4BB24CF0FAF99B69A1
- [Subject]: Fake Off Date
- [BodyPreview]: This is a fake entry
- [Start]: 2019-02-06T00:00:00.0000000
- [End]: 2019-02-07T00:00:00.0000000
- [Attendees]: Array ( [0] => Array ( [type] => required [status] => Array ( [response] => none [time] => 0001-01-01T00:00:00Z ) [emailAddress] => Array ( [name] => EGCR-Scheduling [address] => scheduling@georgiareporting.com ) ) ) 
- [Organizer]: Microsoft\Graph\Model\Recipient Object ( [_propDict:protected] => Array ( [emailAddress] => Array ( [name] => EGCR-Scheduling [address] => scheduling@georgiareporting.com ) ) ) 
------------------------------------------
- [ICalUId]: 040000008200E00074C5B7101A82E00800000000907A8E2161BDD4010000000000000000100000004CE0546F6F3FA24AAED0946002922D87
- [Subject]: Shannon Leviton v. Joe Wallace
- [BodyPreview]: Hi there, Alison Almand is inviting you to a scheduled Zoom meeting. Join from PC, Mac, Linux, iOS or Android: https://GeorgiaReporting.zoom.us/j/415605349 or Visit https://georgiareporting.zoom.us/ Click "Join Meeting" Enter Meeting ID: 415
- [Start]: 2019-02-28T16:00:00.0000000
- [End]: 2019-02-28T19:00:00.0000000
- [Attendees]: Array ( [0] => Array ( [type] => required [status] => Array ( [response] => none [time] => 0001-01-01T00:00:00Z ) [emailAddress] => Array ( [name] => Alison Almand [address] => alisona@georgiareporting.com ) ) [1] => Array ( [type] => required [status] => Array ( [response] => none [time] => 0001-01-01T00:00:00Z ) [emailAddress] => Array ( [name] => EGCR-Scheduling [address] => scheduling@georgiareporting.com ) ) ) 
- [Organizer]: Microsoft\Graph\Model\Recipient Object ( [_propDict:protected] => Array ( [emailAddress] => Array ( [name] => Alison Almand [address] => alisona@georgiareporting.com ) ) ) 
------------------------------------------
- [ICalUId]: 040000008200E00074C5B7101A82E00800000000908B665982BCD401000000000000000010000000CBF6DD2423A7B14FA68B86C413B38C3D
- [Subject]: Dr. Cox - Expert Depo
- [BodyPreview]: Hi there, Alison Almand is inviting you to a scheduled Zoom meeting. Join from PC, Mac, Linux, iOS or Android: https://GeorgiaReporting.zoom.us/j/638857685 or Visit https://georgiareporting.zoom.us/ Click "Join Meeting" Enter Meeting ID: 638
- [Start]: 2019-02-12T23:00:00.0000000
- [End]: 2019-02-13T00:00:00.0000000
- [Attendees]: Array ( [0] => Array ( [type] => required [status] => Array ( [response] => none [time] => 0001-01-01T00:00:00Z ) [emailAddress] => Array ( [name] => Alison Almand [address] => alisona@georgiareporting.com ) ) [1] => Array ( [type] => required [status] => Array ( [response] => none [time] => 0001-01-01T00:00:00Z ) [emailAddress] => Array ( [name] => EGCR-Scheduling [address] => scheduling@georgiareporting.com ) ) ) 
- [Organizer]: Microsoft\Graph\Model\Recipient Object ( [_propDict:protected] => Array ( [emailAddress] => Array ( [name] => Alison Almand [address] => alisona@georgiareporting.com ) ) ) 
------------------------------------------
- [ICalUId]: 040000008200E00074C5B7101A82E0080000000020E853C13DBAD4010000000000000000100000009F412DDDA74C464E8F1E1156B60DC1E2
- [Subject]: Telephone deposition
- [BodyPreview]: Hi there, Alison Almand is inviting you to a scheduled Zoom meeting. Join from PC, Mac, Linux, iOS or Android: https://GeorgiaReporting.zoom.us/j/178484973 or Visit https://georgiareporting.zoom.us/ Click "Join Meeting" Enter Meeting ID: 178
- [Start]: 2019-02-01T20:00:00.0000000
- [End]: 2019-02-01T21:00:00.0000000
- [Attendees]: Array ( [0] => Array ( [type] => required [status] => Array ( [response] => none [time] => 0001-01-01T00:00:00Z ) [emailAddress] => Array ( [name] => Alison Almand [address] => alisona@georgiareporting.com ) ) [1] => Array ( [type] => required [status] => Array ( [response] => none [time] => 0001-01-01T00:00:00Z ) [emailAddress] => Array ( [name] => EGCR-Scheduling [address] => scheduling@georgiareporting.com ) ) ) 
- [Organizer]: Microsoft\Graph\Model\Recipient Object ( [_propDict:protected] => Array ( [emailAddress] => Array ( [name] => Alison Almand [address] => alisona@georgiareporting.com ) ) ) 
------------------------------------------
- [ICalUId]: 040000008200E00074C5B7101A82E0080000000000000000000000000000000000000000330000007643616C2D556964010000007B45423741424441322D334630342D343137302D393033352D3036394645314433383442367D00
- [Subject]: Benjamin vs. Swanson
- [BodyPreview]: Hi there, Maria Todero is inviting you to a scheduled Zoom meeting. Topic: Benjamin vs. Swanson Time: Jan 28, 2019 5:00 PM Eastern Time (US and Canada) Join from PC, Mac, Linux, iOS or Android: https://GeorgiaReporting.zoom.us/j/723711638
- [Start]: 2019-01-28T22:00:00.0000000
- [End]: 2019-01-28T23:00:00.0000000
- [Attendees]: Array ( [0] => Array ( [type] => required [status] => Array ( [response] => none [time] => 0001-01-01T00:00:00Z ) [emailAddress] => Array ( [name] => Alison Almand [address] => alisona@georgiareporting.com ) ) [1] => Array ( [type] => required [status] => Array ( [response] => none [time] => 0001-01-01T00:00:00Z ) [emailAddress] => Array ( [name] => EGCR-Scheduling [address] => scheduling@georgiareporting.com ) ) ) 
- [Organizer]: Microsoft\Graph\Model\Recipient Object ( [_propDict:protected] => Array ( [emailAddress] => Array ( [name] => Alison Almand [address] => alisona@georgiareporting.com ) ) ) 
------------------------------------------
- [ICalUId]: 040000008200E00074C5B7101A82E00800000000F00F6B3B17B7D4010000000000000000100000000AFFF5CA0738EC4F81B90DD33C7EE8AD
- [Subject]: Cesar Rodriguez and Rebeca Rodriguez vs. Alexei Moraczewski, et al.
- [BodyPreview]: Hi there, Alison Almand is inviting you to a scheduled Zoom meeting. Join from PC, Mac, Linux, iOS or Android: https://GeorgiaReporting.zoom.us/j/923972163 or Visit https://georgiareporting.zoom.us/ Click "Join Meeting" Enter Meeting ID: 923
- [Start]: 2019-01-31T20:00:00.0000000
- [End]: 2019-01-31T21:00:00.0000000
- [Attendees]: Array ( [0] => Array ( [type] => required [status] => Array ( [response] => none [time] => 0001-01-01T00:00:00Z ) [emailAddress] => Array ( [name] => Alison Almand [address] => alisona@georgiareporting.com ) ) [1] => Array ( [type] => required [status] => Array ( [response] => none [time] => 0001-01-01T00:00:00Z ) [emailAddress] => Array ( [name] => EGCR-Scheduling [address] => scheduling@georgiareporting.com ) ) ) 
- [Organizer]: Microsoft\Graph\Model\Recipient Object ( [_propDict:protected] => Array ( [emailAddress] => Array ( [name] => Alison Almand [address] => alisona@georgiareporting.com ) ) ) 
------------------------------------------
- [ICalUId]: 040000008200E00074C5B7101A82E008000000004052B6EE01B4D4010000000000000000100000000BBE909E22FD3C4B95296E4205913DA3
- [Subject]: Bethany Mae Stiff v. Seth Richard Stiff
- [BodyPreview]: Hi there, Alison Almand is inviting you to a scheduled Zoom meeting. Join from PC, Mac, Linux, iOS or Android: https://GeorgiaReporting.zoom.us/j/524457339 or Visit https://georgiareporting.zoom.us/ Click "Join Meeting" Enter Meeting ID: 524
- [Start]: 2019-01-30T20:00:00.0000000
- [End]: 2019-01-30T22:00:00.0000000
- [Attendees]: Array ( [0] => Array ( [type] => required [status] => Array ( [response] => none [time] => 0001-01-01T00:00:00Z ) [emailAddress] => Array ( [name] => Alison Almand [address] => alisona@georgiareporting.com ) ) [1] => Array ( [type] => required [status] => Array ( [response] => none [time] => 0001-01-01T00:00:00Z ) [emailAddress] => Array ( [name] => EGCR-Scheduling [address] => scheduling@georgiareporting.com ) ) ) 
- [Organizer]: Microsoft\Graph\Model\Recipient Object ( [_propDict:protected] => Array ( [emailAddress] => Array ( [name] => Alison Almand [address] => alisona@georgiareporting.com ) ) )

**Comment by MIchaelMainer** [comment]
You'll want to use the calendarview to get all of the events between to points in time.

https://docs.microsoft.com/en-us/graph/api/calendar-list-calendarview?view=graph-rest-1.0

**Comment by darrelmiller** [comment]
Due to inactivity we will optimistically assume the solution worked.  Let us know if you still have issues.
