### ISSUE TITLE
Unable to add/edit data in Excel Workbook

### ISSUE THREAD

**Issue by AAllport** [microsoftgraph/msgraph-sdk-php#1405]
Hi Team,

I'm working on a webapp that involves putting data into a user's excel workbook.
However, we seem to be hitting a series or roadblocks.

We can successfully retrieve a list of sheets, but there doesn't seem to be any function to update the records?
![image](https://github.com/microsoftgraph/msgraph-sdk-php/assets/3750120/5a02b1d0-d8a2-4b2b-bea8-63d3917f0cfa)
![image](https://github.com/microsoftgraph/msgraph-sdk-php/assets/3750120/473d9306-dac7-41b0-b1fb-fada33ff76a0)

Please advise, as the documentation here seems lacking - https://learn.microsoft.com/en-us/graph/api/range-update

Thanks!

**Comment by Ndiritu** [comment]
@AAllport we're working to resolve this upstream. Will revert once it's fixed.

Pending fix - https://github.com/microsoft/OpenAPI.NET.OData/pull/431

**Comment by AAllport** [comment]
Appreciated 🙌

**Comment by SilasKenneth** [comment]
Hi @AAllport,
This should be resolved now. If that is not the case, kindly reopen the issue.
Thank you trying the sdk.
