### ISSUE TITLE
Iterator hangs when passed an empty DriveItemCollectionResponse

### ISSUE THREAD

**Issue by GBirch** [microsoftgraph/msgraph-sdk-php#1406]
If you follow the example for paging through a collection in Examples.md, but you have searched for, say, the children() of an empty DriveItem folder, then $pageIterator->hasNext() returns TRUE.  That causes an infinite loop, and the application hangs.  

Clearly hasNext() should return FALSE in this instance, but at the very least, can we update the example?

**Comment by ian-paqt** [comment]
Yeah, I found that using `$pageIterartor->iterate()` works WITHOUT the `while` loop from the example.

**Comment by GBirch** [comment]
@ian-paqt Can you share example code?

**Comment by Ndiritu** [comment]
> Yeah, I found that using `$pageIterartor->iterate()` works WITHOUT the `while` loop from the example.

This would only work if the callback you're providing never pauses iteration (never returns false).

**Comment by Ndiritu** [comment]
This is resolved in the latest release `2.0.1`
