### ISSUE TITLE
How to download file with v2

### ISSUE THREAD

**Issue by tvaughan73** [microsoftgraph/msgraph-sdk-php#1410]
in V1 I could do

```
$this->graph->createRequest('GET', '/drives/' . $driveId . '/items/' . $itemId . '/content')->download($path);
```
How do I do the same with V2?

I think it would be something like

```
$tokenRequestContext = new \Microsoft\Kiota\Authentication\Oauth\ClientCredentialContext(
    config('graphapi.azure_tenant_id'),
    config('graphapi.azure_client_id'),
    config('graphapi.azure_client_secret')
);
$graphServiceClient = new \Microsoft\Graph\GraphServiceClient($tokenRequestContext);
$response  = $graphServiceClient->drives()->byDriveId(config('graphapi.attachments_drive_id'))->items()->byDriveItemId('< drive item id>')->content()->get();
```
I cannot figure out how to download the file from $response.

**Comment by Ndiritu** [comment]
HI @tvaughan73, you'd need to `wait()` on the returned Promise to get the `StreamInterface` returned.

```php
$response  = $graphServiceClient->drives()->byDriveId(config('graphapi.attachments_drive_id'))->items()->byDriveItemId('< drive item id>')->content()->get()->wait();
```

**Comment by Ndiritu** [comment]
Please re-open incase this is not resolved

**Comment by JacoSJKruger** [comment]
I have a related question. Well, sort off. 

So in the new version when an email has an attachment, but that attachment is itself an email, then this is in fact handled as an 'Item'. 

It does not have the standard properties like ContentBytes and ContentId. 
I would however like to download this file/item programatically but things like $emailAttachment->getContentBytes(); does not work. 

I've also tried getting creative like:
$fileContents = $graphServiceClient->users()->byUserId($user_id)->messages()->byMessageId($email->getId())->attachments()->byAttachmentId($emailAttachment->getId())->content()->get()->wait();

But alas, still not working. 
Any ideas?
