### ISSUE TITLE
Set timezone for start and end when creating event

### ISSUE THREAD

**Issue by mic1983** [microsoftgraph/msgraph-sdk-php#143]
When create event i was not able to set timezone for start and end.
I try with header Prefer: outlook.timezone="Pacific Standard Time"
and with setOriginalStartTimeZone/setOriginalEndTimeZone.
 What is wrong?
Thanks

**Comment by MIchaelMainer** [comment]
This sounds like a service API specific question. Please post to StackOverflow with the [microsoft-graph](https://stackoverflow.com/questions/tagged/microsoft-graph) tag. Post the link to your StackOverflow post in this issue.

**Comment by MIchaelMainer** [comment]
And make sure you provide much more details than you have in this issue. Provide examples of what you have tried, HTTP capture traces, links to documentation, error codes, etc.
