### ISSUE TITLE
Unable to install version 2.2.0 of the SDK

### ISSUE THREAD

**Issue by kellslte** [microsoftgraph/msgraph-sdk-php#1430]
Hi, I have looked at the Packagist listing for this SDK, and I saw version 2.2.0, but once I tried to install it, I got an error saying the available version was 2.1.0. Could this be updated to match the available installable version?

**Comment by kellslte** [comment]
I also noticed that the GraphServiceClient is giving me an error. I attached the error to this comment.
![2023-12-14 17 44 12](https://github.com/microsoftgraph/msgraph-sdk-php/assets/29720486/f7d8aa5b-8fd8-4391-9ee1-2987a1a09b6e)

**Comment by jamesmacwhite** [comment]
Noticed the same, the composer release doesn't exist.

https://packagist.org/packages/microsoft/microsoft-graph

2.1.0 is the latest composer package.

**Comment by Ndiritu** [comment]
Apologies and thanks for raising this.

The README has been updated https://github.com/microsoftgraph/msgraph-sdk-php/pull/1434
