### ISSUE TITLE
Question: how to obtain accessToken from graphServiceClient?

### ISSUE THREAD

**Issue by alecrt** [microsoftgraph/msgraph-sdk-php#1443]
I need to call Sharepoint REST Api v1 in order to get comments of a ListItem.

How can I get the accessToken from a client instatiated as follow?

```
$tokenRequestContext = new ClientCredentialContext(
         $tenantId,
         $clientId,
         $clientSecret
      );
$client = new GraphServiceClient($tokenRequestContext);
```

**Comment by Ndiritu** [comment]
There's an ongoing discussion about this [here](https://github.com/microsoftgraph/msgraph-sdk-php/issues/1407) so I'll close this.
