### ISSUE TITLE
Problem calling PATCH on an OnlineMeeting

### ISSUE THREAD

**Issue by gkotsinos** [microsoftgraph/msgraph-sdk-php#1484]
Hello,

as stated, I am trying to patch an Microsoft\Graph\Generated\Models\OnlineMeeting model. The error I am getting is that I am sending a property that isn't allowed to get PATCHed. After some debugging I figured out that although during the instantiation of my OnlineMeeting object I am only filling the attendees property, the body of the request ends up being this:

`{"@odata.type":"#microsoft.graph.onlineMeeting","attendeeReport":null,"participants":{"attendees":[{"upn":"user@somedomain.com"}]}}`

From what I understand the `attendeeReport` property should not end up in the request body since I am not setting it, and I have confirmed that is the issue since sending the same request without the property works fine.

Also as defined in the relevant documentation this property is not even in the list of options that are updateable ( https://learn.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-1.0&tabs=http#request-body )

EDIT: I can successfully solve the issue with this simplistic approach confirming the issue:

Within `Microsoft\Graph\Generated\Models\OnlineMeeting`

change this line:

`$writer->writeBinaryContent('attendeeReport', $this->getAttendeeReport());`

to this line:
`
if (!empty($this->getAttendeeReport())) {
    $writer->writeBinaryContent('attendeeReport', $this->getAttendeeReport());
}
`

**Comment by SilasKenneth** [comment]
Hi @gkotsinos, thanks for providing additional information.
I am able to reproduce the issue.
I am putting this as high priority so we get it fixed ASAP.
Sorry for the inconvenience.
