### ISSUE TITLE
Class 'Microsoft\Graph\Graph' not found (Nette 3x)

### ISSUE THREAD

**Issue by jAKErCZ** [microsoftgraph/msgraph-sdk-php#1522]
Hi, I have downloaded the microsoft graph via composer and while adding these lines

use Microsoft\Graph\Graph;
use Microsoft\Graph\Model;

in my codeigniter project it shows the error

Class 'Microsoft\Graph\Graph' not found
Class 'Microsoft\Graph\Model' not found

I'm developing with Nette(3.1) and I installed it using composer require microsoft/microsoft-graph

microsoft/microsoft-graph version 2.8.0

How to solve this problem?

**Comment by SilasKenneth** [comment]
Hi @jAKErCZ, the class 
```php 
Microsoft\Graph\Graph
 ```
is not available in the version 2.8.0 of the SDK.
Kindly consider looking at [examples of how to use the SDK](https://github.com/microsoftgraph/msgraph-sdk-php/blob/dev/docs/Examples.md).

**Comment by gagston** [comment]
You should follow this link that helps you to overcome your problem
[https://github.com/microsoftgraph/msgraph-sdk-php](https://github.com/microsoftgraph/msgraph-sdk-php)
