### ISSUE TITLE
Question regarding 1.x usage

### ISSUE THREAD

**Issue by npracht** [microsoftgraph/msgraph-sdk-php#1529]
Hello,

I am wondering if we are obligated to move to 2.x ? Is there an EOL for 1.x ? Is there an incompatibility with MS APIs coming ?
Thanks.

cc @damzoneuh

**Comment by SilasKenneth** [comment]
Hi @npracht, thank you for your interest in the SDK,
Version 1.x of the SDK will only be receiving security updates going forward.

Regarding compatibility, we no-longer do the model updates, meaning at some point when new properties are added, you won't be able to include them in the request.

cc @sebastienlevert
