### ISSUE TITLE
Files upload to the OneDrive though Laravel without user login

### ISSUE THREAD

**Issue by nehamashal23** [microsoftgraph/msgraph-sdk-php#1535]
I am developing a website where clients can log in and upload files, which need to be saved to an admin's OneDrive account. I am using Laravel (or core PHP) for this project. Despite my efforts to use the Microsoft Graph API, I have not been successful in achieving this functionality.

Could you provide a detailed guide or example on how to upload files to OneDrive using Laravel or core PHP? Specifically, I need to know:

1. How to authenticate with the Microsoft Graph API and obtain the necessary tokens.
2. How to configure the app to interact with OneDrive.
3. How to upload files to OneDrive and access them later.

Any help or pointers would be greatly appreciated.

**Comment by SilasKenneth** [comment]
Hi @nehamashal23, thanks for trying out the SDK.
For general help on how to use the SDK, please check the Examples [Here](https://github.com/microsoftgraph/msgraph-sdk-php/blob/main/docs/Examples.md#uploading-large-files).
Feel free to open another issue if you have a problem using the SDK.

**Comment by nehamashal23** [comment]
Hi @SilasKenneth , Thank you for the guidance and resources provided. I will review the examples and provide my feedback accordingly
