### ISSUE TITLE
Undifined classes

### ISSUE THREAD

**Issue by SaadEnne** [microsoftgraph/msgraph-sdk-php#1552]
### Describe the bug

use Microsoft\Graph\Model;
use Microsoft\Graph\Graph;
use Microsoft\Graph\Model\Event;

### Expected behavior

when I try to import those classes I face those problems

### How to reproduce

create those classes asap 
![image](https://github.com/microsoftgraph/msgraph-sdk-php/assets/96637517/cd409140-2d7c-4255-a4eb-927461a24be9)

### SDK Version

2.8.0

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by Ndiritu** [comment]
Thanks for reaching out @SaadEnne.

The import namespaces have changed in version 2.x of the SDK while I see you're using imports from version 1.x.

Feel free to check our code [samples](https://github.com/microsoftgraph/msgraph-sdk-php/blob/main/docs/Examples.md#creating-a-graph-client) and [API reference docs](https://learn.microsoft.com/en-us/graph/api/overview?view=graph-rest-1.0) for the correct imports.
