### ISSUE TITLE
uniqueBody of messages is not unique

### ISSUE THREAD

**Issue by mBaldasty** [microsoftgraph/msgraph-sdk-php#1576]
### Describe the bug

I created a mail conversation from A to B.

A sent a message to B, B responded, A responded Back, B responded back, A responded back.

As expected the whole conversation is sent, getBody()->getContent() correctly returns all that.

I included uniqueBody in the expectation that only the new content would be present there I was wrong: Still the whole conversation is included.

### Expected behavior

Only include the newest response.

### How to reproduce

Just create a simple back and forth conversation between two mails and call, get the contents of the inbox loop over the mails and call

```php
$requestConfig = new MessageItemRequestBuilderGetRequestConfiguration();
$requestConfig->queryParameters = MessageItemRequestBuilderGetRequestConfiguration::createQueryParameters();
$requestConfig->queryParameters->select = array('uniqueBody', 'bodyPreview', 'body', 'toRecipients', 'conversationId', 'conversationIndex', 'id', 'sender', 'subject', 'receivedDateTime');

foreach ($mails->getValue() as $mail) {
  $id = $mail->getId();
   $message = $graphServiceClient->users()->byUserId(_coreUser_)->mailFolders()->byMailFolderId('Inbox')->messages()->byMessageId($id)->get($requestConfig)->wait();
  Log::info($message->getUniqueBody()->getContent());
}
```

(using laravel here).

This is a sever bug.

### SDK Version

2.13.0

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by Ndiritu** [comment]
Hi @mBaldasty, thanks for reporting this bug.
I'm unable to reproduce this scenario while testing on https://developer.microsoft.com/en-us/graph/graph-explorer.
Are you able to double-check that the `uniqueBody` is not working as expected. I don't see similar API issues created which would point to a larger problem.
