### ISSUE TITLE
SharingLink->getWebUrl() incorrectly mapped

### ISSUE THREAD

**Issue by bsprengelmeijer** [microsoftgraph/msgraph-sdk-php#1583]
### Describe the bug

When I request a sharing link, I can't access the webUrl because it is nested inside a link property, which is missing in `getWebUrl()` 

This is my response
![image](https://github.com/user-attachments/assets/1eee2556-8e4c-4305-a2b3-bdd444a89546)

And this is the `getWebUrl()`

```
public function getWebUrl()
    {
        if (array_key_exists("webUrl", $this->_propDict)) {
            return $this->_propDict["webUrl"];
        } else {
            return null;
        }
    }
  ```

### Expected behavior

->getWebUrl() returns the `_propDict[link][weburl]`

### How to reproduce

```php
$graphRequest = $this->graph->createRequest(Request::METHOD_POST, "/drives/{drive_id}/items/{microsoft_id}/createLink");

$graphRequest
       ->attachBody([
            'type'  => 'view',
            'scope' => 'anonymous',
       ])
       ->setReturnType(SharingLink::class);

/** @var SharingLink $sharingLink */
$sharingLink = $graphRequest->execute();
  ```

### SDK Version

1.110.0

### Known Workarounds

Override sharingLink
```php
class SharingLink extends \Microsoft\Graph\Model\SharingLink
{
    public function getLink(): ?string
    {
        if (array_key_exists('link', $this->_propDict) && array_key_exists('webUrl', $this->_propDict['link'])) {
            return $this->_propDict['link']['webUrl'];
        }

        return null;
    }
}
```

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by Ndiritu** [comment]
Hi @bsprengelmeijer, thanks for reaching out.
The expected return type for this API call is a [`Permission` object](https://learn.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-1.0&tabs=http#response)
By using this return type, I believe you should be able to do `$response->getLink()->getWebUrl()`

**Comment by bsprengelmeijer** [comment]
Hi @Ndiritu, the Permission object is working thanks
