### ISSUE TITLE
Library is very large

### ISSUE THREAD

**Issue by Jamesking56** [microsoftgraph/msgraph-sdk-php#1584]
### Describe the bug

This Composer library is inordinately large compared to most libraries. Downloaded it is `244.8 MiB`.

This causes issues for me since my hosting provider limits Composer to run maximum for 5 minutes. This library is so big that it causes Composer to timeout on my host.

I am only using the library since it is required for using PHP to send emails via Office 365, since SMTP is being phased out.

Is there a better trimmed version of this library that can be made available?

### Expected behavior

The library size is closer to most Composer libraries, < `50 MiB`.

For comparison, AWS SDK is `48.7 MiB`.

### How to reproduce

Require this library and look at the size output in `vendor`.

### SDK Version

2.14.0

### Debug output

![image](https://github.com/user-attachments/assets/41bc9f5c-f0b3-4313-a1a4-decbb04cfd63)

### Configuration

- OS: PopOS 22.04
- Architecture: x64

Specifically PHP timeout set to 300 seconds

### Other information

Looks like the largest file in this repo is `src/Generated/kioa-dom-export.txt` at `35.7 MiB` alone, do we need this file?

**Comment by Ndiritu** [comment]
Thank you for reporting this @Jamesking56 and for pointing out the large size of the `kiota-dom-export` file

We acknowledge this challenge and provide two workarounds at the moment:
- Using [`microsoft-graph-core`](https://packagist.org/packages/microsoft/microsoft-graph-core) which provides a `Guzzle` HTTP client pre-configured with middleware to call Microsoft Graph. [Setup & samples](https://github.com/microsoftgraph/msgraph-sdk-php-core/blob/main/README.md)


- This SDK is generated based off Microsoft Graph's OpenAPI description using a tool we maintain called [Kiota](https://learn.microsoft.com/en-us/openapi/kiota/). You can run Kiota CLI & generate an SDK for only the Mail endpoints and add this to your CI pipelines to get regular updates:

```cli
kiota generate -l PHP -d https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/refs/heads/master/openapi/v1.0/openapi.yaml --include-path **/messages/** --include-path **/mailFolders/**  -c GraphMailClient -n Microsoft\Graph\Mail\Client -o ./client
```

For a guide on this, please refer to https://learn.microsoft.com/en-us/openapi/kiota/quickstarts/php.
