### ISSUE TITLE
Office365 api issue with timezone

### ISSUE THREAD

**Issue by paramonovav** [microsoftgraph/msgraph-sdk-php#159]
We create calendar events with timeZone  Europe/London
```
…..
                'start' => [
                    'dateTime' =>'2019-04-02T12:30:00+01:00',
                    'timeZone' => 'Europe/London'
                ],
                'end' => [
                    'dateTime' => '2019-04-02T13:30:00+01:00',
                    'timeZone' => 'Europe/London'
                ],
….
```
But when we open appointment in desktop time zone always show UTC. Why ? and how to fix it ?

![Outlook screenshot](https://user-images.githubusercontent.com/607431/55308376-3dfd0b80-5463-11e9-991f-ca5fb6c75f1e.png)

**Comment by daveismyname** [comment]
use the full timezone name:

```php
'start'     => ['dateTime' => $from, 'timeZone' => 'GMT Standard Time'],
'end'       => ['dateTime' => $to, 'timeZone' => 'GMT Standard Time'],
```

**Comment by friek108** [comment]
How do you convert a timezone in PHP to the 'full timezone name' as you mentioned. For example, if I have 'Australia/Melbourne' in php (and this is not supported in the list of ms-graph timezones), then how do you convert it to a timezone that Microsoft will recognise?

**Comment by keithslater** [comment]
I know this is old but I ran into the same issue. 
This can also happen if you specify a timezone on your start/end dates. Remove +01:00 and just specify the timezone parameter and it should work.
