### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by pawelcudowski** [microsoftgraph/msgraph-sdk-php#1599]
I cannot install Microsoft Graph, I try to install by composer require microsoft/microsoft-graph in docker
![screen](https://github.com/user-attachments/assets/fcc62485-6e1c-4731-8dd3-3ebad5b711bd)

**Comment by cartertech** [comment]
Similar issue here:
![image](https://github.com/user-attachments/assets/8670bf65-fb0c-476f-b401-2045633ae640)

Have tried to increase the timeout and have ran as root - all fail.

**Comment by andrueastman** [comment]
Thanks for raising this @cartertech, @pawelcudowski 

To confirm, does this occur in previous versions as well or only on the latest version?

**Comment by cartertech** [comment]
> Thanks for raising this @cartertech, @pawelcudowski
> 
> To confirm, does this occur in previous versions as well or only on the latest version?

I've tried this on 2.11 and it also occurs.

**Comment by guillaumerichardv** [comment]
I have tried all the latest versions since v2.12 or v2.13, and it is taking increasingly longer to retrieve.
Initially, it took 15-20 minutes, and now it takes at least 30-40 minutes.
