### ISSUE TITLE
URL error on getting new page from GraphCollectionRequest object

### ISSUE THREAD

**Issue by brentashley** [microsoftgraph/msgraph-sdk-php#160]
After using GetPage() to get the next page of a collection, a 404 error is thrown because the URL has v1.00 in it instead of v1.0  

The problem is an off-by-one error in setPageCallInfo() in src/Http/GraphCollectionRequest.php, which attempts to get the endpoint from the end of NextLink but starts one character too soon, picking up the 0 at the end of the api version.

line 180 should read: 

`$this->endpoint = substr($this->nextLink, $baseLength + 1);`
 
[AB#7587](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7587)

**Comment by brentashley** [comment]
[proposed label] Bug

Please triage as a bug, as this issue means paging is broken.  For now we are patching the SDK to make it work.

**Comment by Ndiritu** [comment]
Hi @brentashley 
Thanks for reporting this issue. I was able to reproduce this issue only by using a custom baseUrl as opposed to the default one. Therefore, a different solution from your suggested one has been proposed in the linked PR.
Looking forward to more feedback from you on the SDK
