### ISSUE TITLE
Get response headers via API - Team Creation

### ISSUE THREAD

**Issue by bharatpareek** [microsoftgraph/msgraph-sdk-php#161]
I am trying to create a team with new API endpoint introduced in beta APIs.

I am successfully able to create a Team using the API request

The document says response headers should be like the following:
```
HTTP/1.1 202 Accepted
Content-Type: application/json
Location: /teams/{teamId}/operations/{operationId}
Content-Location: /teams/{teamId}
{
}
```
It also says **If successful, this API returns a 202 Accepted response containing a link to the teamsAsyncOperation.**

But the API not returning any response headers, is there any way to get response headers as API call result?

**SDK version 1.6.**

**Comment by bharatpareek** [comment]
I think i solved it.

I was setting returnType in graph request, which was not required so i removed it, then i just called getHeaders() function on the object like this:

`$team->getHeaders();` and it worked.

**Comment by Matt-B50** [comment]
This worked for me - thank you!  I think the issue can be closed ;-)

**Comment by howest-ward** [comment]
I am looking for the exact same thing.

Is it possible to post some example code, because I don't get what you are doing to get the headers.

this is my code: 

```
$graphServiceClient = $this->getGraphServiceClient();

$requestBody = new Team();
$requestBody->setDisplayName($teamName);
$requestBody->setDescription($teamName.' description');

$membersArray = [];

$membersConversationMember = new AadUserConversationMember();
$membersConversationMember->setOdataType('#microsoft.graph.aadUserConversationMember');
$membersConversationMember->setRoles(['owner']);
$additionalData = [
    'user@odata.bind' => 'https://graph.microsoft.com/v1.0/users(\'xxxxxxxx-xxxx-xxxx-xxxx-xxxcxxxxxxxx\')',
];
$membersConversationMember->setAdditionalData($additionalData);
$membersArray[] = $membersConversationMember;
        
$requestBody->setMembers($membersArray);

$additionalData = [
    'template@odata.bind' => 'https://graph.microsoft.com/v1.0/teamsTemplates(\'standard\')',
];
$requestBody->setAdditionalData($additionalData);

$result = $graphServiceClient->teams()->post($requestBody)->wait();
```
The teams is created correctly but $result is null here. And I cant't find a way to get the new team id (from content-location in the headers).
