### ISSUE TITLE
Getting individual record of users not happening

### ISSUE THREAD

**Issue by tharun777** [microsoftgraph/msgraph-sdk-php#168]
$user = $graph->createRequest("GET", "/me")
						  ->setReturnType(Model\User::class)
						  ->execute();

is not working.,.. 
instead 

$user = $graph->createRequest("GET", "/users") working..

How to make /me to work..  
[AB#7572](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7572)

**Comment by daveismyname** [comment]
it sounds like your logged in as a admin/tenant instead of as a user

**Comment by MIchaelMainer** [comment]
This is correct. Your application has to run in the context of a user to use /me. Otherwise, it must use /users/{userid} to get information about a user.

related to #165
