### ISSUE TITLE
missing @microsoft.graph.downloadUrl field in Model DriveItem

### ISSUE THREAD

**Issue by landall** [microsoftgraph/msgraph-sdk-php#169]
There is no way to access this field now. What should i do?

**Comment by MIchaelMainer** [comment]
@landall How were you accessing the @microsoft.graph.downloadUrl field? Can you give us a bit more information?

**Comment by landall** [comment]
i am listing files in onedrive and get a set of DriveItem object. I can see this with var_dump. but i cannot find a public method or property to read it.

**Comment by MIchaelMainer** [comment]
I believe you'd access with something like this:

```
$properties = $driveItem->getProperties()
if (array_key_exists("@microsoft.graph.downloadUrl", $properties))
{
   $downloadUrl = $properties["@microsoft.graph.downloadUrl"]
}
```

**Comment by landall** [comment]
thank you! it is my fault. i have not found this public method. (⊙_⊙)

**Comment by MIchaelMainer** [comment]
You're welcome! Glad to help.

**Comment by lamoboos223** [comment]
i couldn't extract `@microsoft.graph.downloadurl` in the django file because of the `@` character 

so i updated my method in the python backend so it adds a filed called `downloadurl` in my list before pass it to the html file

```python
def onedrive(request):
  context = initialize_context(request)

  token = get_token(request)

  files = get_files(token)

  for file in files['value']:
        file["downloadUrl"] = (file["@microsoft.graph.downloadUrl"])
  context['files'] = files['value']

  return render(request, 'tutorial/files.html', context)
```
