### ISSUE TITLE
PHP enum generation issues

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-php#170]
We've noticed some issues with the code generation for PHP and how it handles enums.

- [ ] For example, [VoiceGender](https://github.com/microsoftgraph/msgraph-sdk-php/blob/pipelinebuild/beta/1191902/src/Beta/Model/VoiceGender.php). The member names are uppercase but are generated as lower case.

      <EnumType Name="VoiceGender">
        <Member Name="Female" Value="0" />
        <Member Name="Male" Value="1" />
      </EnumType>

- [ ] Enum members with underscores in the name have the underscore removed. For example, in DeviceManagementSubscriptions, Member Name="intune_EDU" becomes

    const INTUNE_EDU = "intuneEDU"; 
[AB#7580](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7580)

**Comment by Ndiritu** [comment]
Underscores and upper-casing issue in enums resolved in Beta and V1 Kiota previews
