### ISSUE TITLE
about list file tree in onedrive with remote items

### ISSUE THREAD

**Issue by landall** [microsoftgraph/msgraph-sdk-php#173]
Q1: in which situation is a remote item used?
I just find it is produced when i add a shared folder to my onedrive root(only folder and root).

Q2: i want to product a file explorer to list the file tree in my onedrive. How should calc the shown path of a remote item? eg. /abc mapped to /drives/123/items/456. What should i calc the path of a item with related path def/ghi under /abc(as shown in Win10). 
[AB#7586](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7586)

**Comment by MIchaelMainer** [comment]
Thank you for your questions about the Microsoft Graph. Please post your questions to StackOverflow with the microsoft-graph tag. After you've posted your question on StackOverflow, please provide a link here back to your post. That way, the question will be found by more people -- plus it gives back to the dev community on StackOverflow. 

Make sure you include the following information in your post on StackOverflow:
* What you've tried, your repro steps
* A trace of both the request and response
* Any error messages
* Any settings
