### ISSUE TITLE
I am unable to add custom parameter Microsoft Auth 

### ISSUE THREAD

**Issue by lokendrapanwar** [microsoftgraph/msgraph-sdk-php#185]
Here is the detailed in this url :
https://stackoverflow.com/questions/56303616/microsoft-outlook-add-custom-parameter-authorization-request

I need to add extra param which have dynamic value
I did not found for this in given Microsoft Docs
Like this example -

$provider = new \League\OAuth2\Client\Provider\GenericProvider([
'clientId' => Constants::CLIENT_ID,
'clientSecret' => Constants::CLIENT_SECRET,
'redirectUri' => Constants::REDIRECT_URI,
'urlAuthorize' => Constants::AUTHORITY_URL . Constants::AUTHORIZE_ENDPOINT,
'urlAccessToken' => Constants::AUTHORITY_URL . Constants::TOKEN_ENDPOINT,
'urlResourceOwnerDetails' => '',
'custom_param' => '$user_type'
]);

**Comment by darrelmiller** [comment]
Currently we do not have an a authorization provider built into the PHP SDK.  It is necessary to use a 3rd party library.  We recommend you use one that supports the requirements you have.
