### ISSUE TITLE
Is there a way to add conflictBehavior to upload method?

### ISSUE THREAD

**Issue by landall** [microsoftgraph/msgraph-sdk-php#186]
As in the example, $graph->createRequest("PUT", "/me/drive/root/children/copydoc.docx/content")->upload('C:/copydoc.docx') will perform replace behavior as default with PUT request. It is any way to add the conflictBehavior param to perform fail or replace? Or I must use an upload session?

**Comment by MIchaelMainer** [comment]
Can you point me at the documentation you are using?

**Comment by landall** [comment]
https://docs.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&tabs=cs

**Comment by MIchaelMainer** [comment]
The `PUT /me/drive/root/children/copydoc.docx/content` API always replaces like you mention. You will need to use upload session to change that behavior.

**Comment by landall** [comment]
> The `PUT /me/drive/root/children/copydoc.docx/content` API always replaces like you mention. You will need to use upload session to change that behavior.

Thank you!
