### ISSUE TITLE
Getting mime content issue

### ISSUE THREAD

**Issue by mehul-saleshandy** [microsoftgraph/msgraph-sdk-php#187]
Hi,
I want to get mime content of message using this library but I can't get the result, it return empty string.
```
$graph = new \Microsoft\Graph\Graph();
$graph->setApiVersion("beta");            
$graph->setAccessToken($access_token);
$mimeUrl = '/me/messages/{my-message-id}/$value';
 $response = $graph->createRequest('GET', $mimeUrl)
                                 ->setReturnType("GuzzleHttp\Psr7\Stream")   // Also I tried remove this line but not success                               
                                 ->execute();
```
When I am tried above code, I get the empty result.
Can yo please help me, how can I get mime-content of specific message.
I had referred the link : https://docs.microsoft.com/en-us/graph/outlook-get-mime-message

**Comment by MIchaelMainer** [comment]
This is because the content isn't returned as a stream. It is returned as content-type: text/plain.  Can you confirm that the item has a body? Use Graph Explorer and make the same request there.

I think getRawBody() is what you'll want to use to get that mime content.

**Comment by mehul-saleshandy** [comment]
@MIchaelMainer Thanks!
getRawBody() working for me!

**Comment by ianef** [comment]
I was still scratching my head a lot after looking at this issue and other resources relating to fetching MIME content. Just calling getRawBody() doesn't work as the internal body variable in the result is a GuzzleHttp\Psr7\Stream class. You need to cast this to a string:
```
                                $messageEndpoint = '/me/messages/' . $message->getId() . '/$value';
                                /** @var GraphResponse $emailResponse */
                                $emailResponse = $graph->createRequest(Request::METHOD_GET, $messageEndpoint)
                                    ->execute();
                                $mimeBody = (string)$emailResponse->getRawBody();
```
I discovered the clue to this in the Guzzle docs where it says "The body of a response can be retrieved using the getBody method. The body can be used as a string, cast to a string, or used as a stream like object."

https://docs.guzzlephp.org/en/stable/quickstart.html

When the GraphResponse class is created, it calls getBody() on the Guzzle response to set the internal $_body variable. It's that variable you get when you call getRawBody() which can then be cast to a string.

Hope this helps someone else and saves them a few hours and a headache!

**Comment by Ndiritu** [comment]
> I was still scratching my head a lot after looking at this issue and other resources relating to fetching MIME content. Just calling getRawBody() doesn't work as the internal body variable in the result is a GuzzleHttp\Psr7\Stream class. You need to cast this to a string:
> 
> ```
>     $messageEndpoint = '/me/messages/' . $message->getId() . '/$value';
>     /** @var GraphResponse $emailResponse */
>     $emailResponse = $graph->createRequest(Request::METHOD_GET, $messageEndpoint)
>         ->execute();
>     $mimeBody = (string)$emailResponse->getRawBody();
> ```
> 
> I discovered the clue to this in the Guzzle docs where it says "The body of a response can be retrieved using the getBody method. The body can be used as a string, cast to a string, or used as a stream like object."
> 
> https://docs.guzzlephp.org/en/stable/quickstart.html
> 
> When the GraphResponse class is created, it calls getBody() on the Guzzle response to set the internal $_body variable. It's that variable you get when you call getRawBody() which can then be cast to a string.
> 
> Hope this helps someone else and saves them a few hours and a headache!

@ianef made a change to save future headaches. Sorry about the experience.

**Comment by melbings** [comment]
> I was still scratching my head a lot after looking at this issue and other resources relating to fetching MIME content. Just calling getRawBody() doesn't work as the internal body variable in the result is a GuzzleHttp\Psr7\Stream class. You need to cast this to a string:
> 
> ```
>     $messageEndpoint = '/me/messages/' . $message->getId() . '/$value';
>     /** @var GraphResponse $emailResponse */
>     $emailResponse = $graph->createRequest(Request::METHOD_GET, $messageEndpoint)
>         ->execute();
>     $mimeBody = (string)$emailResponse->getRawBody();
> ```

Thanks so much! I was close to giving up when I found your comment.
