### ISSUE TITLE
Class 'Microsoft\Graph\Graph' not found

### ISSUE THREAD

**Issue by Pravin-Raw** [microsoftgraph/msgraph-sdk-php#190]
Hi, I have downloaded the microsoft graph via composer and while adding these lines

**use Microsoft\Graph\Graph;
use Microsoft\Graph\Model;**

 in my codeigniter project it shows the error

**Class 'Microsoft\Graph\Graph' not found**

What should i do to include microsoft graph in my project?

**Comment by rps-repo** [comment]
Assuming you are using codeigniter 3 you would need to set composer to autoload.
in config/config.php:
`$config['composer_autoload'] = TRUE;`
