### ISSUE TITLE
Silent-sign in error

### ISSUE THREAD

**Issue by jtbratcher** [microsoftgraph/msgraph-sdk-php#191]
I'm having an issue where some of our clients are getting stuck on the Microsoft login screen., It is throwing an interruption error 50058. This is only happening to some people and not all. The only thing I can find that is unique about them is that they are using ADFS. 

I was using createCollectionRequest when pulling the groups. I changed it over to createRequest instead and it will allow them to resolve. Any ideas why that may be the case?

`$grabber = $this->graph->createCollectionRequest("GET", '/groups')
            ->setReturnType(Model\Group::class)
            ->setPageSize(100);

        $results = array();
        while (!$grabber->isEnd()) {
            $results = array_merge($results, $grabber->getPage());
        }

VS

$results = $this->graph->createRequest("GET", "/groups")
            ->setReturnType(Model\Group::class)
            ->execute();`

**Comment by darrelmiller** [comment]
Can you provide a HTTP trace for this issue if you are continuing to have this issue?  Thank you.
