### ISSUE TITLE
Which class should i getResponseAsObject in uploading a large file?

### ISSUE THREAD

**Issue by landall** [microsoftgraph/msgraph-sdk-php#192]
I think I should:
1. getResponseAsObject(Model\UploadSession::class) when calling createUploadSession.
2. getResponseAsObject(Model\UploadSession::class) when upload a fragment except the last one.
3. getResponseAsObject(Model\UploadSession::class) when GET the upload url.
4. I don't know which class should be used when I upload the last fragment
5. I don't know which class should be used when I delete the uploadurl.

**Comment by landall** [comment]
The same question when I want to get the status of onedrive copy action using the monitor url.

**Comment by dennisameling** [comment]
The response class is `Model\DriveItem::class`. I've just written an example implementation in https://github.com/microsoftgraph/msgraph-sdk-php/issues/212 (including most of the Best Practices described in the [docs](https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0#best-practices)), the only thing it doesn't support yet is deleting the uploadUrl. Hope this helps!
