### ISSUE TITLE
Paging through large collections

### ISSUE THREAD

**Issue by craigwillis** [microsoftgraph/msgraph-sdk-php#200]
Hi

I posted a SO question regarding pagination of a collection: https://stackoverflow.com/questions/56671478/microsoft-graph-api-paging-large-collections

As the question mentions, I'm trying to page through a large collection of records, ~50,000

The examples on the wiki seem to skip over the usage of the `@odata.nextLink`, which I'd like to use (I'm upgrading from the AAD Azure API, which does return the nextLink in the response)

I'm using v1.9 of the PHP SDK

Thanks

**Comment by Herz3h** [comment]
Same issue here #315

**Comment by MIchaelMainer** [comment]
Posting the example from the linked post for future convenience:

```php
$url = "/users";

// Get the first page
$response = $graph->createCollectionRequest("GET", $url)
                   ->setPageSize(50)
                   ->execute();

if ($response->getNextLink())
{
    $url = $response->getNextLink();
    // TODO: remove https://graph.microsoft.com/v1.0 part of nextlink
} else {
// There are no more pages.
    return null;
}

// get the next page, page size is already set in the next link
$response = $graph->createCollectionRequest("GET", $url)
                  ->execute();
```
