### ISSUE TITLE
Accessing API response data

### ISSUE THREAD

**Issue by craigwillis** [microsoftgraph/msgraph-sdk-php#201]
Hi

I'm currently using the SDK to retrieve details on a group. Looking at the Group model, there are quite a few methods to display data.

When I print_r() the group, it returns a Group object with a protected `_propDict` property. The issue is, some of these aren't accessible via getters, for example:

    Microsoft\Graph\Model\Group Object
    (
    [_propDict:protected] => Array
        (
            [id] => XX-YY-ZZ
            [deletedDateTime] => 
            [classification] => 
            [createdDateTime] => 2019-04-18T15:09:57Z
            [creationOptions] => Array
                (
                    [0] => Team
                    [1] => classAssignments
                    [2] => ExchangeProvisioningFlags:2509
                )

            [description] => 
            [displayName] => Example Group
            [groupTypes] => Array
                (
                    [0] => Unified
                )

            [mail] => test@example.com
            [mailEnabled] => 1
            [mailNickname] => ExampleGroup
            [onPremisesLastSyncDateTime] => 
            [onPremisesSecurityIdentifier] => 
            [onPremisesSyncEnabled] => 
            [preferredDataLocation] => 
            [proxyAddresses] => Array
                (
                    [0] => SPO:SPO_ABCDE123456
                    [1] => SMTP:test@example.com
                    [2] => smtp:rest@example.onmicrosoft.com
                )

            [renewedDateTime] => 2019-04-18T15:09:57Z
            [resourceBehaviorOptions] => Array
                (
                    [0] => HideGroupInOutlook
                    [1] => WelcomeEmailDisabled
                    [2] => ConnectorsDisabled
                    [3] => SubscribeNewGroupMembers
                )

            [resourceProvisioningOptions] => Array
                (
                    [0] => Team
                )

            [securityEnabled] => 
            [visibility] => HiddenMembership
            [extension_ABC123_Education_ObjectType] => Section
            [onPremisesProvisioningErrors] => Array
                (
                )
        )
    )

So, for example, there is no current way to get the `deletedDateTime` or the `createdDateTime`. I would also like to get the `extension_ABC123_Education_ObjectType` value as well.

Is there an easy way of doing this using the Group model?

Thanks

**Comment by MIchaelMainer** [comment]
Addressed on SO

**Comment by tasgray** [comment]
> Addressed on SO

May I ask what SO means? I am facing the same challenge as original poster.

**Comment by MIchaelMainer** [comment]
I'm sorry, I meant StackOverflow. The original poster probably asked the same question there. I think someone addressed it there. We should've linked to it.

**Comment by tasgray** [comment]
For anyone else trying to work this out, I discovered that getProperties() method will return all items in _propDict as an array.
