### ISSUE TITLE
resulted in a `404 Not Found`

### ISSUE THREAD

**Issue by krishna129** [microsoftgraph/msgraph-sdk-php#202]
Caught exception: Client error: `GET https://graph.microsoft.com/v1.0/me` resulted in a `404 Not Found` response: { "error": { "code": "Request_ResourceNotFound", "message": "Resource '9b3d5d12-4b17-4cdc-84cf-6f6a95683948 (truncated...)

**Comment by darrelmiller** [comment]
Could you confirm if this is continuing to be a problem?  This call should work correctly as shown.  Could you also confirm what OAuth flow you are using to obtain a token?  Is this for an app-only permission?

**Comment by dico** [comment]
I also got this error while testing the example under "Get started".

The Graph API docs says "For the signed-in user" under Get user -> /me. It took me a couple of minutes to think "What signed in user...??", as the token is for app-only.

/me is probably a bad example to use, as it only works with a user token.
