### ISSUE TITLE
400 Bad request

### ISSUE THREAD

**Issue by ufeg02** [microsoftgraph/msgraph-sdk-php#204]
I receive a 400 bad request error without a clear notice/indication of what's wrong.

`Client error: `POST https://graph.microsoft.com/v1.0/education/schools` resulted in a `400 Bad Request` response: { "error": { "code": "Request_BadRequest", "message": "The following extension properties are not available (truncated...)`

How can I troubleshoot?

**Comment by ufeg02** [comment]
Fixed the issue by doing a Postman request, then I was able to see the full error-message. Any way to enable this in this package too?

**Comment by darrelmiller** [comment]
Could you provide an example of the request body that you were able to send in Postman?
