### ISSUE TITLE
Client error: GET https://graph.microsoft.com/v1.0/me resulted in a `401 Unauthorized` response - InvalidAuthenticationToken - Access token validation failure

### ISSUE THREAD

**Issue by Sam-digitalife** [microsoftgraph/msgraph-sdk-php#205]
Hi all,
Since few days I try to use the token received with Oauth2-Client (the Networg or PHPleague) with MSGraph but till now I always get the same issue. 401 unauthorized.
I'm able to get the token and query azure AD to get user details.
but when I give the token to MSGraph I always get 401 Unauthorized :-/
Any idea ?

// Set up a new Oauth2 client that will be talking to Azure

$provider = new TheNetworg\OAuth2\Client\Provider\Azure([
    'clientId'                => CLIENT_ID,
    'clientSecret'            => CLIENT_SECRET,
    'redirectUri'             => REDIRECT_URI,
]);

if (!isset($_GET['code'])) {

    // If we don't have an authorization code then get one
    $authUrl = $provider->getAuthorizationUrl();
    $_SESSION['oauth2state'] = $provider->getState();
    header('Location: '.$authUrl);
    exit;

// Check given state against previously stored one to mitigate CSRF attack

} elseif (empty($_GET['state']) || ($_GET['state'] !== $_SESSION['oauth2state'])) {

    unset($_SESSION['oauth2state']);
    exit('Invalid state');

} else {

    // Try to get an access token (using the authorization code grant)

    $token = $provider->getAccessToken('authorization_code', [
        'code' => $_GET['code'],
        'resource' => 'https://graph.microsoft.com',
        'urlAPI' => 'https://graph.microsoft.com/v1.0/',
    ]);
    echo '<br>Token: '.$token.'!<br>';

    // Use this to interact with an API on the users behalf
    try {

        // We got an access token, let's now get the user's details
        $me = $provider->get("me", $token);

        // Use these details to create a new profile
        printf('<br>Hello %s!', $me['displayName']);
             
        $resourceOwner = $provider->getResourceOwner($token);
        echo '<br>Tenant: '.$resourceOwner->getTenantId().'!<br>';
        
        $graph = new Graph();
        $graph
	  ->setBaseUrl("https://graph.microsoft.com/")
	  ->setApiVersion("v1.0")
	  ->setAccessToken($token);

        $user = $graph->createRequest("get", "/me")
			    ->addHeaders(array("Content-Type" => "application/json"))
			    ->setReturnType(Model\User::class)
			    ->setTimeout("1000")
			    ->execute();  
        
    } catch (Exception $e) {

        //Failed to get user details
        echo 'Caught exception: ',  $e->getMessage(), "\n";
        exit('<br>Oh dear...');
    }
}

**Comment by PatchworkBoy** [comment]
After you’ve got your authorisation code, when you switch resource URIs from Azure to Graph, you need to do so separately first rather than just doing it within the refresh token array...

```
// Try to get an access token (using the authorization code grant)

// Get Azure token
$token = $provider->getAccessToken(
	'authorization_code', [
	    'code' => $_GET['code'],
	    'resource' => 'https://graph.windows.net',
	]
);

// Switch Resource over to Graph - THIS LINE IS ESSENTIAL!!
$provider->resource = "https://graph.microsoft.com/";

// Now exchange Azure token for Graph Refresh Token
$refresh = $provider->getAccessToken(
	'refresh_token', [
	    'refresh_token' => $token->getRefreshToken(),
	    'resource' => 'https://graph.microsoft.com'
	]
);

// Get user info from Graph
$me = $provider->get($provider->urlAPI . '/beta/me', $refresh);
$groups = $provider->get($provider->urlAPI . '/beta/me/memberOf', $refresh); 
```

Also, use the 'insert code' button above the reply editor to format your code in posts ;)

**Comment by Sam-digitalife** [comment]
looks like I have no error anymore.
I only change this
`$me = $provider->get($provider->urlAPI . '/beta/me', $refresh);`
by
`$me = $provider->get($provider->urlAPI . '/v1.0/me', $refresh);`
as I got another error. I make more tests tomorrow and keep you posted; Already thank you

**Comment by Sam-digitalife** [comment]
it works fine, thx for the support
