### ISSUE TITLE
Can't set timezone when collecting messages.

### ISSUE THREAD

**Issue by ConChang** [microsoftgraph/msgraph-sdk-php#208]
I am trying to set the timezone before I collecting the data.

`        $message = $graph->createRequest('GET', '/me/mailFolders/inbox/messages/' . $validatedData['mail_id'])
        ->addHeaders(['Prefer:' => 'Central European Time'])
        ->setReturnType(Model\Message::class)
        ->execute();`

Is the above code right?

**Comment by MIchaelMainer** [comment]
That's close.

```php
$message = $graph->createRequest('GET', '/me/mailFolders/inbox/messages/' . $validatedData['mail_id']) ->addHeaders(['Prefer' => 'outlook.timezone="Central European Time"']) ->setReturnType(Model\Message::class) ->execute();
```

Looking at the request, it should look like:
`Prefer: outlook.timezone="Central European Time"`

**Comment by ConChang** [comment]
Then I get an error.

> That's close.
> 
> ```
> $message = $graph->createRequest('GET', '/me/mailFolders/inbox/messages/' . $validatedData['mail_id']) ->addHeaders(['Prefer' => 'outlook.timezone="Central European Time"']) ->setReturnType(Model\Message::class) ->execute();
> ```
> 
> Looking at the request, it should look like:
> `Prefer: outlook.timezone="Central European Time"`

**Comment by ConChang** [comment]
This is what I have right now:

`        $mails = $graph->createCollectionRequest('GET', "/me/mailFolders/" . $folder_id . "/messages")
        ->addHeaders(['Prefer' => 'outlook.timezone="Central European Time"'])
        ->setReturnType(Model\Message::class)
        ->setPageSize(13);`

**Comment by JukkaHau** [comment]
> This is what I have right now:
> 
> ` $mails = $graph->createCollectionRequest('GET', "/me/mailFolders/" . $folder_id . "/messages") ->addHeaders(['Prefer' => 'outlook.timezone="Central European Time"']) ->setReturnType(Model\Message::class) ->setPageSize(13);`

Did you get this to work? everything i tried returns 500 error
