### ISSUE TITLE
$graph variable undefined

### ISSUE THREAD

**Issue by Danbardo** [microsoftgraph/msgraph-sdk-php#21]
Hi,

I just installed msgraph using:
composer require 'microsoft/microsoft-graph'

I am now trying to see if the installation was successful by returning the $graph variable after I run autoload.php.

include('../../vendor/autoload.php');
var_dump($graph);

It returns NULL.

Is there something that I have missed?

**Comment by MIchaelMainer** [comment]
Hello @Danbardo, I'm not familiar with PHP so I can't  comment on whether you've missed something. Have you tried the https://github.com/microsoftgraph/php-connect-sample as a way to get started?

**Comment by cbales** [comment]
You will need to instantiate a new Graph object first:
```php
$graph = new Graph();
```
Make sure to read the [readme](https://github.com/microsoftgraph/msgraph-sdk-php/blob/master/README.md); there are a few registration and authentication steps you will need to start using Graph.
