### ISSUE TITLE
Docblock for Message:setXRecipients is wrong

### ISSUE THREAD

**Issue by hailwood** [microsoftgraph/msgraph-sdk-php#222]
Hi Team,

Can we please get a correction on the docblock for these methods.
They should be `Recipient[]` and not just `Recipient`.

https://github.com/microsoftgraph/msgraph-sdk-php/blob/dev/src/Model/Message.php#L418-L430

https://github.com/microsoftgraph/msgraph-sdk-php/blob/dev/src/Model/Message.php#L448-L460

https://github.com/microsoftgraph/msgraph-sdk-php/blob/dev/src/Model/Message.php#L478-L485 
[AB#7351](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7351)

**Comment by Ndiritu** [comment]
related to #76 and #97 and #115

**Comment by Ndiritu** [comment]
Fixed in v2 preview release https://github.com/microsoftgraph/msgraph-sdk-php/issues/681

**Comment by isvargasmsft** [comment]
Hello @hailwood,

Thank you very much for your patience. This issue is resolved in our [new SDK version 2.0.0-RC5](https://github.com/microsoftgraph/msgraph-sdk-php/issues/943). 

Please feel free to give it a try and share your feedback with us.

Kind regards, 

Isaac Vargas
