### ISSUE TITLE
Uploading files containing brackets causes error

### ISSUE THREAD

**Issue by gjohncock** [microsoftgraph/msgraph-sdk-php#226]
Getting an error with uploading files where file names contain round brackets ie: ( and )
Square brackets seem to be acceptable
So this raises a several questions:
1. what needs to be done to the filename to ensure file names with brackets are uploaded without loss to the filename?
2. what other characters that are acceptable by sharepoint but cause an error in the upload function?
3. is there a function available to correctly format file names so they are accepted by the upload function? 
[AB#7358](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7358)

**Comment by gjohncock** [comment]
Actually I have resolved this issue.  It seems to be a common issue with graph.
Originally i used this syntax...
`$graph->createRequest("PUT", "/drives/$driveId/items/$folderId/children/$filename/content")->upload($sourceFile);`
I changed it to this and it works...
`$graph->createRequest("PUT", "/drives/$driveId/items/$folderId/children('$filename')/content")->upload($sourceFile);`

**Comment by Ndiritu** [comment]
Closing this, please re-open if this is still an issue.
