### ISSUE TITLE
how to add a header to a request

### ISSUE THREAD

**Issue by gjohncock** [microsoftgraph/msgraph-sdk-php#229]
Im trying to retrieve a record from a list based on its ID (inbuilt field).  Using "filter" does not work, the error returned is "Field 'ID' cannot be referenced in filter or orderby as it is not indexed".
The way around it is to provide a header "Prefer:HonorNonIndexedQueriesWarningMayFailRandomly" but I cannot find how to add this to the request.

**Comment by gjohncock** [comment]
found it

**Comment by armetiz** [comment]
could you please share the solution?

**Comment by supportreq** [comment]
yeah how do you pass a request header?

**Comment by Ndiritu** [comment]
@supportreq you can call the `addHeaders()` method on a GraphRequest:
```php
$result = $graph->createRequest("GET", "/abc")
        ->addHeaders([associative array])
       ->execute();
```
