### ISSUE TITLE
OneDrive functional tests require pre-existing files

### ISSUE THREAD

**Issue by caitlinrussell** [microsoftgraph/msgraph-sdk-php#23]
The following functional tests fail when the requested file does not exist:

- testSearchFile
- testCreateSharingLink
- testInvite

The setup for this test should make one or more files to be used in testing. testSearchFile() should also search for a minimum of one file, instead of requiring a certain number of files to be found. 
[AB#7591](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7591)

**Comment by roinochieng** [comment]
This requires us to have further coverage on more defined API scenarios, we've slotted this as a number 4 priority for future work.

**Comment by Ndiritu** [comment]
End to end testing will be removed from the package & Raptor will do the validation in #520
