### ISSUE TITLE
get user api with expand query leads to 400 bad request

### ISSUE THREAD

**Issue by landall** [microsoftgraph/msgraph-sdk-php#243]
GET /users/2baf35b1-a2f6-4190-9ea8-74c0fda89d9c?$expand=extensions

{"@odata.context":"https://graph.microsoft.com/v1.0/$metadata#users(extensions())/$entity"{
  "error": {
    "code": "BadRequest",
    "message": "The entity instance value of type 'microsoft.graph.user' doesn't have a value for property 'id'. To compute an entity's metadata, its key and concurrency-token property values must be provided.",
    "innerError": {
      "request-id": "0dbe226a-bf52-4a68-b00d-8099f2546484",
      "date": "2019-10-15T09:42:57"
    }
  }
}
 
[AB#7364](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7364)

**Comment by MIchaelMainer** [comment]
Thank you for your question. Please post your question to [StackOverflow](https://stackoverflow.com/questions/tagged/microsoft-graph) and tag your post with
the [microsoft-graph] tag. Make sure you include the following information:
1. Tell us what you've tried. Include detailed reproduction steps.
2. Link to the documentation and samples that you've used as reference.
3. Provide an example HTTP request and response that shows the call being made. Make sure you scrub your example of any secrets.

Does this work with other user ids? If so, what is the nature of that user? Does it work without the expansion?

**Comment by Ndiritu** [comment]
No further details and reproduction steps provided by @landall
