### ISSUE TITLE
Consider using Resiliency library to protect the library from network failures

### ISSUE THREAD

**Issue by mickaelandrieu** [microsoftgraph/msgraph-sdk-php#254]
Hi,

I've noted that you wanted to use the Circuit Breaker library from PrestaShop project.

I'm the former author of this library and I have forked it some months ago to push forward some concepts (like isolation and reset) but also to upgrade some dependencies.

Let me know if you are interested in you can find it here => https://github.com/loveOSS/resiliency

Regards 
[AB#7360](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7360)

**Comment by MIchaelMainer** [comment]
Thank you for reaching out to us. We will want to look at this at some point when we are better positioned to make enhancements in this library.

**Comment by MIchaelMainer** [comment]
We will be adding default middleware to add resiliency around retry for 429, 503, and 504. 

This solution would be great for custom middleware where this library meets the developer requirements around resiliency for accessing data that is stored in Microsoft Graph and that can also be accessed from other APIs or caches.

**Comment by MIchaelMainer** [comment]
related https://github.com/microsoftgraph/msgraph-sdk-php/issues/499
