### ISSUE TITLE
Install beta version by composer

### ISSUE THREAD

**Issue by arthurss93** [microsoftgraph/msgraph-sdk-php#259]
Hi, I'm trying to install beta version to call all the models Chat, but.... It's installing the version 1.12 and that version doesn't has models.

I tried install running `composer require microsoft/microsoft-graph`, and editing the file composer.json:

```
{
    "require": {
        "microsoft/microsoft-graph": "^1.0"
    }
}
```

I look forward hearing from you.

Thank you!

**Comment by Matt-B50** [comment]
I've hit this issue, composer does not install the beta models.
