### ISSUE TITLE
Get the pictures of all users in one request

### ISSUE THREAD

**Issue by bbccddaa** [microsoftgraph/msgraph-sdk-php#263]
Hey,

how can i get the pictures of all users in one request? Like displayName or givenName.

**Comment by MIchaelMainer** [comment]
No, you can't get all pictures of all users in one request. That would be one large response in the case of very large organizations. Please post your question to [Microsoft Graph User Voice](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests) as a feature request.
