### ISSUE TITLE
Dont truncate messages

### ISSUE THREAD

**Issue by Herz3h** [microsoftgraph/msgraph-sdk-php#266]
Is there a way to allow errors to show fully. Whenever there is an exception, I get something like:

```
Client error: `POST https://graph.microsoft.com/v1.0/me/calendars/AAMkADQ0MTkyMDM1LTRhYWQtNGU5NC1iMTNiLWQwMGVkOTc3Njg0YgBGAAAAAADqewFH7jyUQLayRkU-YSm8BwCiRV4wB9ZcTLOUnr6Oobk4AAAAAAEGAACiRV4wB9ZcTLOUnr6Oobk4AABoPrhBAAA=/events` resulted in a `400 Bad Request` response:
{
"error": {
"code": "ErrorPropertyValidationFailure",
"message": "At least one property failed validation. (truncated...)
Exception
``` 

Which is very annoying since I don't know exactly what is wrong. 
[AB#7354](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7354)

**Comment by Herz3h** [comment]
Is anyone reading issues here ?

**Comment by MIchaelMainer** [comment]
@Herz3h We do read the issues, we see your frustration, and feel inadequate that we can't address your issue at this time until we have more humans to do something about it.

**Comment by vadim-bulochnik** [comment]
What is the reason to truncate error messages? It's really not good.

**Comment by Ndiritu** [comment]
@vadim-bulochnik @Herz3h Thanks for reporting this. There's a pending change to fix this up. Feel free to share your thoughts.

**Comment by Ndiritu** [comment]
Our latest release (v1.30.0) wraps the Guzzle BadResponseException in a GraphException which provides the full API response in the exception message.

**Comment by guilliamxavier** [comment]
@Herz3h @vadim-bulochnik: For the record, converting Guzzle BadResponseException to GraphException was a breaking change (the original exception was lost), so in patch release 1.30.1 the BadResponseException is no longer converted to GraphException but the message is un-truncated directly inside the original exception

**Comment by CLG-Brainstorm** [comment]
How do I catch the GraphException?  I'm catching GuzzleHttp\Exception\ClientException with the truncated message still

**Comment by guilliamxavier** [comment]
@CLG-Brainstorm: Don't catch GraphException (unless you are using exactly version 1.30.0, but in that case you should probably update). Catch Guzzle's BadResponseException (or more specific ClientException or ServerException), and, provided you are using a version >= 1.30.1, the message shouldn't be truncated to 120 chars, thanks to #453 (but note that it may still be truncated to e.g. 1024 chars by the logging system)
