### ISSUE TITLE
Exception with code ErrorInvalidRecipients

### ISSUE THREAD

**Issue by emajlo** [microsoftgraph/msgraph-sdk-php#280]
**SDK_VERSION is 1.13.0**

I am getting exception:
```json
Exception: Client error: `POST https://graph.microsoft.com/v1.0/users/{emailaddress}/calendar/events` resulted in a `400 Bad Request` response:
{
  "error": {
    "code": "ErrorInvalidRecipients",
    "message": "At least one recipient isn't valid.",
```

The sent data is:
```json
{
  "subject": "Testing",
  "start": {
    "dateTime": "2020-03-20T10:00",
    "timeZone": "Europe\/Stockholm"
  },
  "end": {
    "dateTime": "2020-03-20T10:30",
    "timeZone": "Europe\/Stockholm"
  },
  "attendees": [
    {
      "emailAddress": {
        "address": "{another_emailaddress}"
      }
    }
  ]
}
```

The odd thing is that it still is creating the event correctly and if I run this same thing from Graph Explorer it works and returns Status code 201. 

It also works if the attendee is the same emailaddress as in the url.
 
[AB#7370](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7370)

**Comment by emajlo** [comment]
Is this something I can expect someone to look into? Or should a do a special solution for this on my own?

**Comment by Ndiritu** [comment]
Works in latest v1 release. Also works in v2 preview
