### ISSUE TITLE
Provide mock guzzle client

### ISSUE THREAD

**Issue by pavlepredic** [microsoftgraph/msgraph-sdk-php#283]
I don't see any obvious way of mocking API responses when using this SDK. The problem is that the guzzle client is created in the `GraphRequest` object, so it can't be provided to the `Graph` object when instantiating. That makes unit testing really difficult. A proposed solution is to:
* Add an optional argument to the `Graph` constructor and the `GraphRequest` constructor, accepting an instance of `\GuzzleHttp\Client`
* Pass the provided client (if any) to the `GraphRequest` when `createRequest` is called
* Return the provided client from `GraphRequest::createGuzzleClient` - if it was provided during construction at all.

Then you could do this in your unit tests:

```
$mockGuzzle = $this->createMock(\GuzzleHttp\Client::class);
//mock the response here or use the mock handler in guzzle
$graph = new Graph($mockGuzzle);
$myClient = new MyClient($graph); 
$myClient->fetchEmails(); //example  method that might be utilizing the SDK to make an API call
```

Apart from this, do you see other workarounds for writing unit tests that utilize this SDK? The solution with a proxy is not really acceptable for unit tests - though it may be just fine for debugging. 
[AB#7363](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7363)

**Comment by MIchaelMainer** [comment]
Hello @pavlepredic - I'd like for us to *eventually* have middleware test handlers ([tracking issue](https://github.com/microsoftgraph/msgraph-sdk-design/issues/26)) for this scenario. We have yet to  schedule it for design and implementation across our client libraries.  

With that said, [Guzzle does provide a middleware hook](http://docs.guzzlephp.org/en/stable/handlers-and-middleware.html) for you to add a test handler that can intercept requests and short-circuit the request by responding with a response that you design.

**Comment by Ndiritu** [comment]
Hello @pavlepredic 

Thank you very much for your patience. 

Our [new SDK version 2.0.0-RC5](https://github.com/microsoftgraph/msgraph-sdk-php/issues/943) allows you to customise the underlying client.

Please feel free to give it a try and share your feedback with us.

Kind regards,

Philip
