### ISSUE TITLE
Error moving message to an archive folder inside In-Place Archive

### ISSUE THREAD

**Issue by FernandoMerino** [microsoftgraph/msgraph-sdk-php#285]
I'm using $graph->createRequest("PUT", "/users/<user_id>/messages/<message_id>/move") with "destinationid" as a folder ID with no problem. But when I'm trying to use the archive folder ID inside an In-place Archive as target, I got this error:

{
  "error": {
    "code": "ErrorItemNotFound",
    "message": "The specified object was not found in the store., The (truncated...)

Despite the error the message was moved but I don't got a message resource as response.

Maybe a Microsoft error only using In-Place Archive folders? 

I'm using Graph API v1.0.

Thank you.

**Comment by MIchaelMainer** [comment]
StackOverflow would be a better place to ask this question. Please post your question to [StackOverflow](https://stackoverflow.com/questions/tagged/microsoft-graph) and tag your post with
the [microsoft-graph] tag. Make sure you include the following information:
1. Tell us what you've tried. Include detailed reproduction steps.
2. Link to the documentation and samples that you've used as reference.
3. Provide an example HTTP request and response that shows the call being made. Make sure you scrub your example of any secrets.
