### ISSUE TITLE
workbookApplication: calculate BUG

### ISSUE THREAD

**Issue by phil2396** [microsoftgraph/msgraph-sdk-php#290]
Hello guys,

please see my question below:

"calculationType": "calculationType-value"

What are the differences between 

-  Recalculate, 
- Full
-  FullRebuild

Also, is it possible to open a temporary worksheet with a sessionID and recalculate it, it seams to be impossible from my attempts.

**Comment by MIchaelMainer** [comment]
This is a good question to ask on StackOverflow. Make sure you tag it with [excel] and [microsoft-graph]. Make sure you include the following information:
1. Tell us what you've tried. Include detailed reproduction steps.
2. Link to the documentation and samples that you've used as reference.
3. Provide an example HTTP request and response that shows the call being made. Make sure you scrub your example of any secrets.
