### ISSUE TITLE
Unable to update "onPremisesExtensionAttributes"

### ISSUE THREAD

**Issue by MichaelBelgium** [microsoftgraph/msgraph-sdk-php#292]
If someone can help or give a reason why this isn't happening, i'd appreciate it.

I want to update users extensionattribute15 but it doesn't let me. I'm getting the error
`unable to update the specified properties for objects that have originated within an external service.`

I've searched the docs for reasons and google but seems this only occurs with adding members in mail-enabled security groups. And i have it when updating users ... like i'm the only one.
The users are NOT `onPremisesSyncEnabled` (value is `null`) so the attributes are not readonly.

An example:
```PHP
$response = $this->graph->createRequest("PATCH", "/users/$emailOrID")
             ->attachBody(json_encode([
                 'onPremisesExtensionAttributes' => [
                     'extensionAttribute15' => "605"
                 ]
             ]))
             ->execute();
```

**Comment by MichaelBelgium** [comment]
If users got added with powershell, would it mean the  `external service` is powershell, and msgraph can't update these?

**Comment by MIchaelMainer** [comment]
Thank you for posting. This question is no specific to the PHP client so I suggest that you post to StackOverflow with the [microsoft-graph] tag. Make sure you include the following information:
1. Tell us what you've tried. Include detailed reproduction steps.
2. Link to the documentation and samples that you've used as reference.
3. Provide an example HTTP request and response that shows the call being made. Make sure you scrub your example of any secrets.
