### ISSUE TITLE
Missing videoConferencing related getters/setters

### ISSUE THREAD

**Issue by Blacksmoke16** [microsoftgraph/msgraph-sdk-php#294]
Based on [this](https://docs.microsoft.com/en-us/graph/outlook-calendar-online-meetings?tabs=java#example-create-and-make-meeting-available-as-an-online-meeting) example, some methods required for videoconferencing are missing from the PHP SDK.

I was able to find to related methods in the [Java SDK](https://github.com/microsoftgraph/msgraph-sdk-java/blob/2fab6676cb50fb414557699825adda764f02d639/src/main/java/com/microsoft/graph/models/extensions/Calendar.java#L109-L115).  The PHP SDK is probably just needs an updated set of types generated to match the other SDKs.

**Comment by MIchaelMainer** [comment]
This should now be available on [packagist in 1.14.0](https://packagist.org/packages/microsoft/microsoft-graph#1.14.0).

Ref: https://github.com/microsoftgraph/msgraph-sdk-php/pull/295

**Comment by Blacksmoke16** [comment]
@MIchaelMainer Thanks!
