### ISSUE TITLE
Update CI to use ADO instead of Travis

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-php#299]
https://github.com/microsoftgraph/msgraph-sdk-php/blob/dev/.travis.yml 
[AB#7361](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7361)

**Comment by MIchaelMainer** [comment]
- [ ] Add validation of models for generated PRs.

**Comment by Ndiritu** [comment]
@MIchaelMainer this was done here https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/blob/dev/.azure-pipelines/generation-templates/php-run-tests.yml
