### ISSUE TITLE
Bug on 412 Http status code

### ISSUE THREAD

**Issue by andrea-wood** [microsoftgraph/msgraph-sdk-php#301]
Hi, using the _**invitation**_ endpoint on Microsoft Graph for a guest user that already exists on the directory I have an internal server error. The http status code returned from Graph Api is 412, that it seems not supported by the library. 

Here the code I'm using:

`
		try {
			
		    $accessToken = $this->getAccessToken(['https://graph.microsoft.com/.default']);

		    $graph = new Graph();
		    $graph->setAccessToken($accessToken);
		    
		    return  $graph->createRequest("POST", "/invitations")
		    			  ->addHeaders(array("Content-Type" => "application/json"))
		    			  ->attachBody([
								"invitedUserDisplayName" => "some values",
								"invitedUserEmailAddress" =>"email",
								"sendInvitationMessage" => false,
								"inviteRedirectUrl" => "https://test.com"
							])
		                  ->setReturnType(Model\Invitation::class)
		                  ->execute();
		} catch (ClientException $e) {
		    if ($e->hasResponse()) {
		        dump(Psr7\str($e->getResponse()));
		    }
		}
		    

`
EDIT:
The bug occurs if the user already exists in the directory but his account was previously blocked.
 
[AB#7368](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7368)

**Comment by Ndiritu** [comment]
4xx responses now throw `BadResponseException` in the latest v1 release and an `ODataError` in the v2 preview. Both exception objects contain the response body.
