### ISSUE TITLE
Move from Travis-CI to Azure DevOps

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-php#304]
[AB#5595](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/5595)

**Comment by MIchaelMainer** [comment]
Add a `compose validate` step.

**Comment by Ndiritu** [comment]
@MIchaelMainer `composer validate` was added by https://github.com/microsoftgraph/msgraph-sdk-php/pull/378
