### ISSUE TITLE
Is it possible to autherize PHP api connection with Microsoft Graph without prompting user for username and password?

### ISSUE THREAD

**Issue by direselign** [microsoftgraph/msgraph-sdk-php#308]
I have written a PHP api that connects to a Microsoft account to add appointments to a calendar, and this works fine. For first time use, the user is required to authenticate with username and password before a token is issued. Is there a way to bypass internally with PHP (passing a username password) without prompting the user to do so?

**Comment by MIchaelMainer** [comment]
You can use one of the application only work flows like client credential flow to enable the application to act without user interaction.

Try this: https://github.com/microsoftgraph/msgraph-sdk-php#authenticate-with-the-microsoft-graph-service
