### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by buiduongthe** [microsoftgraph/msgraph-sdk-php#313]
Dear MS,

I run code on console
Token get OK
My code
`$graph = new Graph();
        $graph->setAccessToken($accessToken);
        $user = $graph->createRequest("GET", "/me")
            ->setReturnType(Model\User::class)
            ->execute();`

Result error?

`Exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `GET https://graph.microsoft.com/v1.0/me` resulted in a `404 Not Found` response:
{
  "error": {
    "code": "Request_ResourceNotFound",
    "message": "Resource '0e6410d1-7768-4505-a857-4dae1a1e4476 (truncated...)"
}`

I want to code example reset password user.

Thanks

**Comment by MIchaelMainer** [comment]
Are you running in the context of a user or an application? How are you authenticating? My guess is that you're using client credential flow and therefore there isn't a context of `/me`.

**Comment by buiduongthe** [comment]
Dear MS,

Step 1: Create account admin api@domain.com
Step 2: Create App run background (client ID, tenant ID, Certificates, Client secrets)
- API Permission  (Azure Active Directory Graph, Microsoft Graph) -> All Read, Write
Step 3: Write code get Token
Step 4: Reset password for other user

thanks

**Comment by MIchaelMainer** [comment]
Instead of using /me, access the user by their id. "/users/{id}". `me` is only used in public clients which you aren't using.
