### ISSUE TITLE
Get nextLink for driveItems pagination

### ISSUE THREAD

**Issue by Herz3h** [microsoftgraph/msgraph-sdk-php#315]
I'm currently using datatables and would like to implement pagination (so far, have been retrieving all the results which is slow with large collections). 

To achieve this, I used the wiki [example](https://github.com/microsoftgraph/msgraph-sdk-php/wiki/Paging-through-Collections) but there is only a `getDeltaLink()` method, no `getNextLink()`. 

Is there any reason as to why the nextLink has no getter in the GraphCollectionRequest ? 

Also with this pagination system, how does one get the previous page since only `nextLink` is returned according to documentation.

**Comment by MIchaelMainer** [comment]
The deltaLink is exposed as it is intended to reused later to check whether there are changes. The nextLink is intended to be used immediately in a loop.

**Comment by Herz3h** [comment]
How would one implement pagination if no nextLink is accessible with the sdk ?

**Comment by MIchaelMainer** [comment]
Try this:

```php
    public function testMailGetNextPage()
    {
        $messageIterator = $this->_client->createCollectionRequest("GET", "/me/messages")
                                         ->setReturnType(Model\Message::class);
        $messages = $messageIterator->getPage();

        while (!$messageIterator->isEnd())
        {
            $messages = $messageIterator->getPage();
        }
        $this->assertNotNull($messages);
    }
```

**Comment by MIchaelMainer** [comment]
Let us know if you have any questions about the sample.

**Comment by Herz3h** [comment]
I'm coming back to this issue. Since currently I'm using your above code but it implies that I have to wait for all the data to be loaded before I can do anything with it.

Here is the code I'm using:

```php
    private function _getDelta($deltaLink = null)
    {
        $route = "/sites/root/drive/root/delta";

        if ($deltaLink)
        {
            $request = $this->client->createCollectionRequest('GET', $deltaLink);
        }
        else
        {
            $request = $this->client->createCollectionRequest('GET', $route)
                            ->setPageSize(999);
        }

        $driveItems = $request->getPage();

        $i = 0;
        while (!$request->isEnd())
        {
            $nextPage = $request->getPage();

            $nextPageData = $nextPage['value'];

            foreach ($nextPageData as $item)
            {
                $driveItems['value'][] = $item;
            }

            $i++;
        }

        if (!is_array($driveItems))
        {
            return [
                'driveItems' => [],
                'deltaLink'  => null,
            ];
        }

        return [
            'driveItems' => $driveItems,
            'deltaLink'  => $request->getDeltaLink()
        ];
    }
```

Problem is, one of our client has 650Go in their sharepoint, and this is not a viable way to do it, as loading that many object in memory is simply not possible. 

So It would be very practical to be able to get the nextLink, so that I can pass it to the function  for each call. Allowing me to do my processing outside this function.

What do you think ?
