### ISSUE TITLE
Creating OnlineMeeting

### ISSUE THREAD

**Issue by sreenumalae** [microsoftgraph/msgraph-sdk-php#318]
Hello Team,

I'm trying to schedule an [OnlineMetting](https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-1.0&tabs=http) through MS Graph API.

```
$onlinemeet->startDateTime = "2020-09-02T14:30:34.2444915";
$onlinemeet->endDateTime = "2020-09-02T15:30:34.2444915";
$onlinemeet->subject = "Test Meeting";
$jso = json_encode($onlinemeet);
```

```
$user = $graph->createRequest("POST", "/me/onlineMeetings")->addHeaders(array("Content-Type" => "application/json"))->attachBody($jso)->setReturnType(User::class) ->execute();
```

**Exception - Client error: `POST https://graph.microsoft.com/beta/me/onlineMeetings` resulted in a `403 Forbidden` response: { "error": { "code": "Forbidden", "message": "", "innerError": { "request-id": "bd43aa57-511e-4 (truncated...)**
While creating an application in azure portal
under API permission i gave permission to access  GraphApi->Delegated Permissions->onlinemeetings.ReadWrite.
Can someone help me with a proper example or proper syntax in PHP.

Thankyou !!..

**Comment by Matt-B50** [comment]
Hi @sreenumalae, did you get a solution to this?  My code is as follows so far:

			$data = [
				'subject' => 'Test Meeting',
				'startDateTime' => '2020-10-12T06:30:00',
				'endDateTime' => '2020-10-12T126:30:00',
			];

			$graphresponse = $graph->createRequest("POST", "/me/onlineMeetings")
				->attachBody($data)
				->setReturnType(Model\OnlineMeeting::class)
				->execute();

Just having fun with permissions as I thought Application permissions were available for OnlineMeetings.  Looks like I'll have to use Delegate permissions

**Comment by Matt-B50** [comment]
Looks like Application permissions are available on beta.  And I need to follow this: https://docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy

 			$graphresponse = $graph->setApiVersion("beta")
				->createRequest("POST", "/users/$meetuserId/onlineMeetings")
				->attachBody($data)
				->setReturnType(BetaModel\OnlineMeeting::class)
				->execute();

I'll follow up if this worksor not.

**Comment by Matt-B50** [comment]
So here's my code:

			$guzzle = new \GuzzleHttp\Client();
			$tenantId= 'xx';
			$clientId= 'xx';
			$clientSecret= 'xx';
			$meetuserId= 'xx';

			$url = 'https://login.microsoftonline.com/' . $tenantId . '/oauth2/token?api-version=beta';
			$token = json_decode($guzzle->post($url, [
				'form_params' => [
					'client_id' => $clientId,
					'client_secret' => $clientSecret,
					'resource' => 'https://graph.microsoft.com/',
					'grant_type' => 'client_credentials',
				],
			])->getBody()->getContents());
			$accessToken = $token->access_token;

			$graph = new Graph();
			$graph->setAccessToken($accessToken);

			$data = [
				'subject' => 'Test Meeting',
				'startDateTime' => '2020-10-12T06:30:00.0000000-00:00',
				'endDateTime' => '2020-10-12T23:30:00.0000000-00:00',
			];

			$graphresponse = $graph->setApiVersion("beta")
				->createRequest("POST", "/users/$meetuserId/onlineMeetings")
				->attachBody($data)
				->setReturnType(BetaModel\OnlineMeeting::class)
				->execute();

I get the following error message: `Error: Class 'Beta\Microsoft\Graph\Model\OnlineMeeting' not found in Microsoft\Graph\Http\GraphResponse->getResponseAsObject() (line 156 of /vendor/microsoft/microsoft-graph/src/Http/GraphResponse.php)`

I've installed the SDK as per the instructions via Composer.  The Beta models found in this repo are not installed.  How do I install them?

**Comment by Matt-B50** [comment]
After setting the access policy as per the previous link and tweaking things, I've finally managed to get online meeting creation working!

			use Microsoft\Graph\Graph;
			use Microsoft\Graph\Model;

			$guzzle = new \GuzzleHttp\Client();

			$tenantId= '...';
			$clientId= '...';
			$clientSecret= '...';
			$meetuserId= '...';

			$url = 'https://login.microsoftonline.com/' . $tenantId . '/oauth2/token?api-version=1.0';
			$token = json_decode($guzzle->post($url, [
				'form_params' => [
					'client_id' => $clientId,
					'client_secret' => $clientSecret,
					'resource' => 'https://graph.microsoft.com/',
					'grant_type' => 'client_credentials',
				],
			])->getBody()->getContents());
			$accessToken = $token->access_token;

			$graph = new Graph();
			$graph->setAccessToken($accessToken);

			$data = [
				'subject' => 'Test Meeting',
				'startDateTime' => '2020-10-12T06:30:00.0000000-00:00',
				'endDateTime' => '2020-10-12T23:30:00.0000000-00:00',
			];

			$graphresponse = $graph->setApiVersion("beta")
				->createRequest("POST", "/users/$meetuserId/onlineMeetings")
				->attachBody($data)
				->setReturnType(Model\OnlineMeeting::class)
				->execute();
