### ISSUE TITLE
Composer Guzzle version constraints

### ISSUE THREAD

**Issue by hubipe** [microsoftgraph/msgraph-sdk-php#324]
Hello,
starting with version 1.17.0 the dependency in composer.json has changed from guzzle ^6.2 to ^7.0. The minimal version of required PHP is still ^7.1. The minimal version of PHP required by guzzle 7.0 is PHP 7.2.5, so effectively this library requires at least PHP version of ^7.2.5.

If there are no incompatible changes, could you please consider allowing using new versions of this library with PHP 7.1 by allowing installing guzzle _^6.2|^7.0_?

Thank you for consideration

**Comment by Mika56** [comment]
I'm having the same issue. Even worse, in my case, this requires me to update the major version of Symfony, which I can't do for more.
Can you allow `^6.0 || ^7.0`? As seen in #311, there's no changes in the usage of Guzzle.
Or better, migrate to [php-http](http://docs.php-http.org/en/latest/) and let us choose the HTTP client of our choice
