### ISSUE TITLE
How to list N events starting from a date+time

### ISSUE THREAD

**Issue by rodrigoguariento** [microsoftgraph/msgraph-sdk-php#325]
Reading https://docs.microsoft.com/pt-br/graph/api/calendar-list-events?view=graph-rest-1.0&tabs=http I couldn't get next N events starting from a date+time, eg.: I'd like to get next 10 events from now. How to do it? Eg.: I have an user who have 10 events per day, and another user with 10 events but each event once a month. I'm using MS Graph API v1.0.

**Comment by MIchaelMainer** [comment]
You will want to use the calendar view functionality. 

https://docs.microsoft.com/en-us/graph/api/user-list-calendarview?view=graph-rest-v1.0&tabs=http
