### ISSUE TITLE
No way to add PSR-3 logger

### ISSUE THREAD

**Issue by exptom** [microsoftgraph/msgraph-sdk-php#328]
It would be very helpful to add a PSR-3 logger to the Guzzle client but I cannot find a way to send options to the guzzle client that is created in GraphRequest.
Is this a feature that you could add?
[AB#5994](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/5994)

**Comment by MIchaelMainer** [comment]
We know we want to expose the Guzzle client to enable both default middleware, and to enable custom middleware like a logger. This is something we plan to do, we haven't scheduled it.

**Comment by MIchaelMainer** [comment]
https://github.com/microsoftgraph/msgraph-sdk-design#sdk-features-support

**Comment by MichaelBelgium** [comment]
I actually had to do this to log every request, made a fork and added `setGuzzleOptions`  and `setHandler` - here's a fork, I could do a PR of [this branch](https://github.com/microsoftgraph/msgraph-sdk-php/compare/dev...MichaelBelgium:dev) if desired

**Comment by isvargasmsft** [comment]
Hello @exptom,

Thank you very much for your patience. Our [new SDK version 2.0.0-RC5](https://github.com/microsoftgraph/msgraph-sdk-php/issues/943) allows you to customize the guzzle client.

Please feel free to give it a try and share your feedback with us.

Kind regards, 

Isaac Vargas
