### ISSUE TITLE
Filter on onPremisesExtensionAttributes

### ISSUE THREAD

**Issue by MichaelBelgium** [microsoftgraph/msgraph-sdk-php#329]
Is filtering on the onPremisesExtensionAttributes object not supported? We store an id into extensionAttribute15 and it'd be so much better if we could directly filter on that field. Now we have to loop through thousands of users and check each extensionAttribute15 if it's x. 

It takes an unacceptable period of time to do that ..

`https://graph.microsoft.com/v1.0/users?$filter=onPremisesExtensionAttributes/extensionAttribute15 eq '118833'`

```
{
    "error": {
        "code": "Request_UnsupportedQuery",
        "message": "Property 'extensionAttribute15' does not exist as a declared property or extension property.",
        "innerError": {
            "date": "2020-09-10T09:11:05",
            "request-id": "2d0a5c8a-a389-4149-b1ce-c3db78fbdfda"
        }
    }
}
```

**Comment by MIchaelMainer** [comment]
I doubt that this is supported. This may represent a feature request. Please post to https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests.

@Licantrop0 

More information about AD search: https://developer.microsoft.com/en-us/office/blogs/build-advanced-queries-with-count-filter-search-and-orderby/

**Comment by Licantrop0** [comment]
@MichaelBelgium it is actually supported using the Advanced Query Capabilities! We recently introduced the support, thanks @MIchaelMainer for linking my blog post :)
[Try your query here in Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%3F%24filter%3DonPremisesExtensionAttributes%2FextensionAttribute15%20eq%20'118833'%26count%3Dtrue&method=GET&version=beta&GraphUrl=https://graph.microsoft.com&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d)

**Comment by MichaelBelgium** [comment]
@Licantrop0 Oh neat! However when will the support come to v1.0 of msgraph? Any ETA?

**Comment by Licantrop0** [comment]
@MichaelBelgium look for announcements at Ignite :)

**Comment by baywet** [comment]
Thanks @Licantrop0 for jumping on the thread. Closing as it's been answered.

**Comment by rjbell4** [comment]
@Licantrop0 This is not working for me.  Even using the `beta` version (instead of `v1.0`), I get the error `Property 'extensionAttribute4' does not exist as a declared property or extension property.`  Am I missing something?  Is something more required than just switching to `beta`?

**Comment by Licantrop0** [comment]
@rjbell4 you need to add $count=true in the querystring and ConsistencyLevel=eventual in the request header, let me know if works.

**Comment by rjbell4** [comment]
@Licantrop0 Thanks -- that does indeed work!
