### ISSUE TITLE
$event->getRecurrence() results in Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by pboese** [microsoftgraph/msgraph-sdk-php#354]
When I call `$event->getRecurrence()` on a `Model\Event` instance and the event is not recurring (null), PHP throws an uncatchable error:

> Invalid argument supplied for foreach()

This happens in v1.16 (Laravel 6.0) 
[AB#7369](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7369)

**Comment by MIchaelMainer** [comment]
Please reopen if this is still an issue. If you reopen this issue, please provide a code example to reproduce the error .
