### ISSUE TITLE
RecurrenceRange start and end dates were serialized into wrong format, resulting in a "UnableToDeserializePostBody" error

### ISSUE THREAD

**Issue by Lntnam** [microsoftgraph/msgraph-sdk-php#355]
https://github.com/microsoftgraph/msgraph-sdk-php/blob/885c715ad952063a30a9044a6c4ba01ed889a671/src/Model/RecurrenceRange.php#L56

The `RecurrenceRange::setStartDate()` and `RecurrenceRange::setEndDate()` both expect a DateTime object.
Those objects will then be formatted with `DateTime::RFC3339` in the `Entity::jsonSerialize()`.

However the document [here](https://docs.microsoft.com/en-us/graph/outlook-schedule-recurring-events#examples-8) is expecting a date-only value (`Y-m-d`).

Not sure if it's related but I'm receiving `UnableToDeserializePostBody` whenever I try to create recurring events. Bellow is the code snippet to add recurring pattern to the event:

```php
    $pattern = new RecurrencePattern();
    $pattern->setType(new RecurrencePatternType(RecurrencePatternType::DAILY));
    $pattern->setInterval(1);

    $range = new RecurrenceRange();
    $range->setType(new RecurrenceRangeType(RecurrenceRangeType::END_DATE));
    $range->setStartDate(DateTime::createFromImmutable($eventDate));
    $range->setEndDate(DateTime::createFromImmutable($endDate));

    $recurrence = new PatternedRecurrence();
    $recurrence->setPattern($pattern);
    $recurrence->setRange($range);

    $event->setRecurrence($recurrence);
```

Request body:
```JSON
{
  "subject": "Test",
  "start": {
    "dateTime": "2020-12-18T13:12:36",
    "timeZone": "America/New_York"
  },
  "end": {
    "dateTime": "2020-12-18T14:12:36",
    "timeZone": "America/New_York"
  },
  "location": {
    "displayName": "Test Location"
  },
  "body": {
    "content": "Test creating recurring event.",
    "contentType": "html"
  },
  "isOnlineMeeting": true,
  "onlineMeetingProvider": "teamsForBusiness",
  "recurrence": {
    "pattern": {
      "type": "daily",
      "interval": 1
    },
    "range": {
      "type": "endDate",
      "startDate": "2020-12-18T13:12:36-05:00",
      "endDate": "2020-12-25T13:12:36-05:00"
    }
  }
}
``` 
[AB#7366](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7366)

**Comment by isvargasmsft** [comment]
Hello @Lntnam 

Thank you very much for your patience. This issue is resolved in our [new SDK version 2.0.0-RC5](https://github.com/microsoftgraph/msgraph-sdk-php/issues/943). 

Please feel free to give it a try and share your feedback with us.

Kind regards, 

Isaac Vargas
