### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by Jarzon** [microsoftgraph/msgraph-sdk-php#359]
Would be nice to support PHP 8.

From what I can see, there is no PHP 8 breaking changes affecting the project.
If I find anything I can post it here.

Adding "php": "^8.0 || ^7.1", to composer.json would fix this issue.

Thanks 
[AB#6803](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6803)

**Comment by Jarzon** [comment]
Travis-CI can run PHP 8 now : https://travis-ci.community/t/php-8-0-missing/10132/26

**Comment by Josje92** [comment]
Bump! Would love this

**Comment by andrii-boiko** [comment]
Do you need any help here?
@ddyett
