### ISSUE TITLE
Ability to specify timeout for the download method

### ISSUE THREAD

**Issue by Herz3h** [microsoftgraph/msgraph-sdk-php#360]
Currently, calling the download method with a specified timeout, does not respect the timeout specified:

```php        
        $route = "/sites/root/drive/items/$id/content?format=pdf";

        $graphClient->createRequest('GET', $route)
                     ->setTimeout($timeout)
                     ->download($localFilePath);
```

Would it be possible to respect the timeout specified like it is the case for [execute](https://github.com/microsoftgraph/msgraph-sdk-php/blob/dev/src/Http/GraphRequest.php#L270) ? Cause this route takes often way too long for converting a small docx (< 2Mo). It often takes more than 2 minutes to convert....... and other times 7sec.

**Comment by Herz3h** [comment]
Thank you  @MIchaelMainer !

**Comment by MIchaelMainer** [comment]
This is available now in `dev-dev`.
