### ISSUE TITLE
Add member to team returns unknown error

### ISSUE THREAD

**Issue by Matt-B50** [microsoftgraph/msgraph-sdk-php#363]
Hi, I am trying to call 'Add member to team':  https://docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&tabs=http

I have the correct application permissions set up (TeamMember.ReadWrite.All).

When I post with the following code:

```
// add $member to team - POST /teams/{teamsId}/members
$data = [
	'@odata.type' => "#microsoft.graph.aadUserConversationMember",
	'user@odata.bind' => "https://graph.microsoft.com/v1.0/users('$memberID')",
];

$graphresponse = $graph
	->setApiVersion("v1.0")
	->createRequest("POST", "/teams/" . $teamID . "/members")
	->attachBody($data)
	->execute();
```

I get a GuzzleException error:
```
stdClass Object
(
    [error] => stdClass Object
        (
            [code] => Forbidden
            [message] => An unknown error has occurred.
            [innerError] => stdClass Object
                (
                    [date] => 2020-12-10T06:24:30
                    [request-id] => 8bf573c4-d834-45e2-8543-fe1ba608a4ee
                    [client-request-id] => 8bf573c4-d834-45e2-8543-fe1ba608a4ee
                )
        )
)
```

I can do the same using MS Graph Explorer with no errors.  I can also list members from my PHP script and from MS Graph Explorer, so I don't believe it is a permissions issue.

Can anyone help please?

**Comment by MIchaelMainer** [comment]
I'd start with comparing the request sent by Graph Explorer with the request sent by your application. That will likely provide a clue of where the issue is. I just issued a successful request from Graph Explorer like:

```http
{
    "@odata.type": "#microsoft.graph.aadUserConversationMember",
    "roles": [
        "owner"
    ],
    "user@odata.bind": "https://graph.microsoft.com/v1.0/users/5cae63f5-0216-4766-8ca3-84d5e288e796"
}
```

**Comment by Matt-B50** [comment]
Thanks, but you can see from my code I'm submitting exactly the same
request on the app and in graph explorer.  Why do I get the error in PHP
and not in explorer?

Can you issue the same request successfully in PHP?

**Comment by MIchaelMainer** [comment]
Yes, I just tried this out and it worked successfully:

```php
		$graphresponse = $client
			->createRequest("POST", "/teams/c495b752-a082-47b5-8e6b-0d8298bab3e8/members")
			->attachBody($data)
			->setReturnType(Model\AadUserConversationMember::class)
			->execute();
```

I'd expect that your code should work. Is there anything special about your tenant?

**Comment by Matt-B50** [comment]
Hi Michael

Nothing special that I'm aware of... anything I should check?

I wasn't using ->setReturnType(Model\AadUserConversationMember::class) but
I still get the error with that added to my code.

kind regards

Matt Barton

**Comment by Matt-B50** [comment]
I'm adding guests to the team - so I don't include 
					`'roles' => ['owner']`
in $data.  If I do I get a different error message as expected "Guests cannot be team owners"

I'm running this on application permissions, which the docs say should be fine, so I don't understand why it's coming back as 'forbidden' - that would indicate a permissions issue to me.  Were you using delegate permissions?

**Comment by Matt-B50** [comment]
Looks like this is relevant: https://stackoverflow.com/questions/65221062/add-team-member-via-graph-api-response-403

**Comment by MIchaelMainer** [comment]
I was using application permissions (client credential) when I successfully added an account as an `owner` and `member`. I don't have a guest account to add, but when I tried with a user account, it appears I got past token validation with the following 400 response:

```php
{
  "error": {
    "code": "BadRequest",
    "message": "Cannot add user '5cae63f5-0216-4766-8ca3-84d5e288e796' as a team guest. User is not a guest.",
    "innerError": {
      "date": "2020-12-21T17:27:06",
      "request-id": "209bed72-3528-4d66-9d43-4130136797ef",
      "client-request-id": "209bed72-3528-4d66-9d43-4130136797ef"
    }
  }
}
```
I don't know enough about the Teams API to be much help on this. 
The tenant I'm using was created using https://developer.microsoft.com/en-US/microsoft-365/dev-program. I created a client application in the Azure portal. Did you make sure that an admin has consented to the scopes in the app registration? I know I forget to do this sometimes.

**Comment by Matt-B50** [comment]
Ok, refactored my code to implement authorisation for delegated permissions when needed, and looks like I've moved past this.  I now have some futher permissions issues to unpick, but closing this issue.

https://stackoverflow.com/questions/65221062/add-team-member-via-graph-api-response-403 is correct, delegated permissions are needed to add guest users - a fact that microsoft haven't documented clearly.
