### ISSUE TITLE
Missing Enum in DeviceEnrollmentType (Beta)

### ISSUE THREAD

**Issue by tomw-ucb** [microsoftgraph/msgraph-sdk-php#375]
Hi MS team,

Recently we have enrolled our HoloLens 2 onto Intune and our application could not handle the enrollment type.
We are using msgraph-sdk-php v1.25.0

The class _Beta\Microsoft\Graph\Model\DeviceEnrollmentType_ is missing the enumeration value for **windowsAzureADJoinUsingDeviceAuth**

Can you please add this enum value ?

Thank you in advance,

Tom 
[AB#7841](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7841)

**Comment by MIchaelMainer** [comment]
This will be in the next release. It is currently available in dev. 

https://github.com/microsoftgraph/msgraph-sdk-php/blob/dev/src/Beta/Microsoft/Graph/Model/DeviceEnrollmentType.php

**Comment by tomw-ucb** [comment]
Hi @MIchaelMainer 

The class does contain a value for "windowsAzureADJoin", but it does not contain a value for "windowsAzureADJoinUsingDeviceAuth".

KR Tom

**Comment by MIchaelMainer** [comment]
I'm sorry that I missed that windowsAzureADJoinUsingDeviceAuth was missing. That enum is neither documented nor contained in the metadata https://graph.microsoft.com/beta/$metadata. What is your source for that missing enum value? Are you seeing it in a response?

https://docs.microsoft.com/en-us/graph/api/resources/intune-shared-deviceenrollmenttype?view=graph-rest-beta

**Comment by tomw-ucb** [comment]
Yes, the Graph API (beta) returns the attached response on the endpoint : https://graph.microsoft.com/beta/deviceManagement/managedDevices/{{managedDeviceId}}

[ManagedDevice_Details_HoloLens2.json.txt](https://github.com/microsoftgraph/msgraph-sdk-php/files/5895394/ManagedDevice_Details_HoloLens2.json.txt)

**Comment by zengin** [comment]
This is fixed in version 1.27.0 as of now:

https://github.com/microsoftgraph/msgraph-sdk-php/blame/1.27.0/src/Beta/Microsoft/Graph/Model/DeviceEnrollmentType.php#L42
