### ISSUE TITLE
How can i download range with microsoft graph?

### ISSUE THREAD

**Issue by vpcomo** [microsoftgraph/msgraph-sdk-php#386]
I'm tring download file to my server - but my server is timeout (Out of memory (allocated 477716480) (tried to allocate 473518912 bytes)) and i had tried function download() but it only save 200kb.
Example 1: 
$getInfo = $graph->createRequest('GET', '/me/drive/items/XXX') ->execute() ;
$downloadUrl = $getInfo->getBody()['@microsoft.graph.downloadUrl'];
dd(file_get_contents($downloadUrl)); (error Out of memory)

Example 1: 
$getInfo = $graph->createRequest('GET', '/me/drive/items/XXX')->download(public_path().'/ABC.mp4') ; (File only 200kb)

How can i download range with microsoft graph? 
[AB#8162](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8162)

**Comment by MIchaelMainer** [comment]
https://docs.microsoft.com/en-us/graph/api/driveitem-get-content?view=graph-rest-1.0&tabs=http

**Comment by SilasKenneth** [comment]
@vpcomo do you get any errors when you use the `download()` function? Also note that when using the `download()` function, the second argument for the `createRequest()` should `/me/drive/items/XXX/contents`
