### ISSUE TITLE
Microsoft Graph Api - Can we Move Emails between two different emails id?

### ISSUE THREAD

**Issue by TussharTikoo** [microsoftgraph/msgraph-sdk-php#388]
As I am using Microsoft Graph API v1 to automate my emails functionality. But I need to move some emails to different email id,  I  would say from Parent email id to child email id. As I receive emails on Parent emails id  inbox then depending on message I need to move that particular email to child email id folders. Can I automate moving part with Microsoft graph. 
[AB#8193](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8193)

**Comment by MIchaelMainer** [comment]
You certainly can. Each message has a parentfolderid that you can use to move an item. Information and more links to information are found in this document:

https://docs.microsoft.com/en-us/graph/api/resources/message?view=graph-rest-1.0
