### ISSUE TITLE
Calling `getEndDate` on a `RecurrenceRange` results in an error the second time

### ISSUE THREAD

**Issue by fbcouch** [microsoftgraph/msgraph-sdk-php#390]
PHP Version 7.3.25
Microsoft Graph versions tested: 1.13.0, 1.26.0

To reproduce:

1. Get an `Model\Event` with a recurrence rule as `$event`
2. Call `$event->getRecurrence()->getRange()->getEndDate()`
3. Call `$event->getRecurrence()->getRange()->getEndDate()` again, observe error:

> TypeError: DateTime::__construct() expects parameter 1 to be string, object given
> vendor/microsoft/microsoft-graph/src/Model/RecurrenceRange.php:107

The problem appears to be that line 107 constructs a `\DateTime` and saves that to the prop dict, but the `is_a` test on line 104 is testing for `Microsoft\Graph\Model\\DateTime` rather than `\DateTime` 
[AB#8201](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8201)

**Comment by zengin** [comment]
The code points to `\DateTime` since this PR #303 (which is for version 1.15)

@fbcouch, because you mention two Microsoft Graph versions: 1.13 and 1.26, does the occur on both versions or only on the first?

It is expected to hit this error in versions earlier than 1.15.

**Comment by fbcouch** [comment]
Hm. Well, I *thought* I tested 1.26, but maybe composer didn't actually update the files or something, because that is what I would have expected the fix to be (and I opened that file in vendor locally and didn't see it updated).
