### ISSUE TITLE
Unable to retrieve tenant service info.

### ISSUE THREAD

**Issue by alessiovietri** [microsoftgraph/msgraph-sdk-php#404]
I'm trying to access my OneDrive using this package to upload and download files. Everything worked fine using a test account, but when I switched to my real account (same code, different IDs) I got this error:

> Client error: `GET https://graph.microsoft.com/beta/users/-----/drive/root/children` resulted in a `400 Bad Request` response: Unable to retrieve tenant service info.

This is the code I'm using:

```
$tenantId = '-----';
$clientId = '-----';
$clientSecret = '-----';
$guzzle = new \GuzzleHttp\Client();
$url = 'https://login.microsoftonline.com/' . $tenantId . '/oauth2/token?api-version=beta';
$token = json_decode($guzzle->post($url, [
        'form_params' => [
        'client_id' => $clientId,
        'client_secret' => $clientSecret,
        'resource' => 'https://graph.microsoft.com/',
        'grant_type' => 'client_credentials',
    ],
])->getBody()->getContents());
$accessToken = $token->access_token;
$graph = new \Microsoft\Graph\Graph();
$graph->setBaseUrl("https://graph.microsoft.com/")
    ->setApiVersion("beta")
    ->setAccessToken($accessToken);
...
```

I already posted a question on [Microsoft docs](https://docs.microsoft.com/en-us/answers/questions/284884/msgraph-unable-to-retrieve-tenant-service-info.html?childToView=290404) and they told me to submit an issue here. There I asked if this was related to Office 365 Membership, but the answer has been negative about this.

Any suggestion to fix this? 
[AB#8384](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8384)

**Comment by MIchaelMainer** [comment]
Can you make any other requests against that same user? For example, does this work (set the userId):

```php
        $graph->setAccessToken($accessToken);
        $user = $graph->setApiVersion("beta")
                      ->createRequest("GET", "/$userId")
                      ->setReturnType(BetaModel\User::class)
                      ->execute();
```

Can you verify that the same permissions are set on the test account app registration as the real account  app registration?
Can you provide us with request-id from the error response?

**Comment by alessiovietri** [comment]
The permissions are the same, I've checked them many times. With this piece of code i get:

`"message": "Invalid request."`

Anyway, I got this answer from the forum:

> From the GitHub doc that you followed - Get started with the PHP Connect Sample, there's another link to a PHP Connect Sample (which is being archived and replaced), but it states that you need:
> 
> Either a Microsoft account or Office 365 for Business account. You can sign up for an Office 365 Developer subscription that includes the resources that you need to start building Office 365 apps.
> 
> PHP 5.6^ or 7
> 
> Composer, a dependency manager for PHP

So I think it could only be a subscription problem

**Comment by MIchaelMainer** [comment]
Did you (or your tenant admin) create a different app registration so that you have a different tenantId, clientId, and client secret, for your real tenant? 

Since this worked with your test account, closing this issue as this is likely not an client library issue.
