### ISSUE TITLE
How does the core PHP SDK handle the generated models for types disambiguated from PHP keywords

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-php#411]
CSDL entities List and Print share the same name with PHP keywords. The generator disambiguates from the keywords by prepending "Graph" to the generated type name. We need to make sure we understand the impact (if any) on the serialization/deserialization. 
[AB#8475](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8475)

**Comment by Ndiritu** [comment]
Version 2 disambiguates these models by prefixing "Escaped" to the name i.e. `EscapedList`, `EscapedPrint` however during serialization & deserialization `list` and `print` are used as the key names in the payload
