### ISSUE TITLE
Fix calling of classes from different namespace

### ISSUE THREAD

**Issue by SilasKenneth** [microsoftgraph/msgraph-sdk-php#424]
Currently all `getXXX()` methods that make calls to class in other namespaces in the SDK fail to resolve the classes due to missing backslash at the beginning of the class instantiation, for instance,

```php
  function getXXX(){
        return new NameSP\ClassName($argument);
   }
``` 
should be
```php
  function getXXX(){
        return new \NameSP\ClassName($argument);
   }
``` 
Sample code with the issue.
https://github.com/microsoftgraph/msgraph-sdk-php/blob/5e4332208618c80b678db614edf25fc0e24e5b4b/src/CallRecords/Model/CallRecord.php#L164 
[AB#8649](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8649)

**Comment by MIchaelMainer** [comment]
Resolved, thank you @SilasKenneth
