### ISSUE TITLE
CallRecord->getOrganizer can return an invalid IdentitySet

### ISSUE THREAD

**Issue by Tanuel** [microsoftgraph/msgraph-sdk-php#432]
It is possible for the value of the organizer property of a CallRecord api response to be null.
```
object(Microsoft\Graph\CallRecords\Model\CallRecord)#848 (1) {
  ["_propDict":protected]=>
  array(11) {
    ["@odata.context"] => string(77) "https://graph.microsoft.com/v1.0/$metadata#communications/callRecords/$entity"
    ["id"] => string(36) "<id>"
   ....
    ["organizer"] => NULL
   ....
}
```

So now `CallRecord->getOrganizer` can return an IdentitySet that will be initialized with a **null** value instead of an **array**.

IdentitySet (with the inherited constructor from Entity) expects the constructor parameter to be an array and this is problematic because then other methods inside the IdentitySet will throw errors when called 

![image](https://user-images.githubusercontent.com/28950300/112846141-02bf6280-90a6-11eb-9cb9-fc95b504089b.png)

see [CallRecords.php](https://github.com/microsoftgraph/msgraph-sdk-php/blob/dev/src/CallRecords/Model/CallRecord.php#L158-L169)

so the possible solution here would probably be to change it to something like `!empty($this->_propDict["organizer"])` in the if clause, so it will actually return null if no organizer is set instead of an invalid IdentitySet

```
public function getOrganizer()
{
    if (!empty($this->_propDict["organizer"])) {
        if (is_a($this->_propDict["organizer"], "Microsoft\Graph\Model\IdentitySet")) {
            return $this->_propDict["organizer"];
        } else {
            $this->_propDict["organizer"] = new \Microsoft\Graph\Model\IdentitySet($this->_propDict["organizer"]);
            return $this->_propDict["organizer"];
        }
    }
    return null;
}
``` 
[AB#8759](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8759)

**Comment by SilasKenneth** [comment]
Hi @Tanuel,

Thanks for taking your time to raise the issue. Since the `CallRecord.php` file is generated, we will be addressing the issue from [microsoftgraph/MSGraph-SDK-Code-Generator](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator) repo.

**Comment by SilasKenneth** [comment]
Hi @Tanuel, thanks again for raising the issue, closing the issue since the bug has been fixed in the latest release.
