### ISSUE TITLE
$event->getSensitivity throws an error when sensitivity = 'private'

### ISSUE THREAD

**Issue by EirikWulff** [microsoftgraph/msgraph-sdk-php#44]
It would seem that the Sensitivity class lacks a value:

PHP Fatal error:  Uncaught Microsoft\Graph\Exception\GraphException: [0]: Invalid enum value private

**Comment by EirikWulff** [comment]
I was able to get it to work by changing 
`const GRAPHPRIVATE = 2;` to `const GRAPHPRIVATE = 'private';` in Model/Sensitivity.php

**Comment by cbales** [comment]
Good catch. It looks like reserved word enum values aren't being set correctly.
