### ISSUE TITLE
how to get owners form application/servicePrincipals

### ISSUE THREAD

**Issue by lordisp** [microsoftgraph/msgraph-sdk-php#454]
I've tried a couple of variant but run out of ideas. Has anyone a tipp for me?

```php
$applications = $graph->createRequest("GET", "/applications/xxx")
            ->setReturnType(Model\Application::class)
            ->execute();
```
try to get owners:
```php
$application->getOwners() <<< empty even I verified that this app has owners
```
 
I like to create a list of applications with its owners

[AB#9157](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9157)

**Comment by Ndiritu** [comment]
Hi @lordisp 

To get the owners, you'd need to expand the relationship between Applications/Service Principals and owners in your URL like this:
```
/applications/xxx?$expand=owners
```
More on `$expand` and OData in general here (https://www.odata.org/getting-started/basic-tutorial/#expand)
Hope this helps?

**Comment by lordisp** [comment]
Hi @Ndiritu ,

excellent 🥳 with this I can refactor my own sdk which makes my life miles easier!

Cheers!
