### ISSUE TITLE
Proxy settings Graph API turn off SSL verification

### ISSUE THREAD

**Issue by PatrickRose** [microsoftgraph/msgraph-sdk-php#460]
In our production environment, all outbound HTTP requests have to be sent via our internal proxy for security reasons.

If we apply our proxy settings, when `\Microsoft\Graph\Http\GraphRequest::createGuzzleClient` is run the SSL verification is turned off:

```php
    protected function createGuzzleClient()
    {
        $clientSettings = [
            'base_uri' => $this->baseUrl,
            'http_errors' => $this->http_errors,
            'headers' => $this->headers
        ];
        if ($this->proxyPort !== null) {
            $clientSettings['verify'] = false;
            $clientSettings['proxy'] = $this->proxyPort;
        }
        $client = new Client($clientSettings);

        return $client;
    }
```

I can see that the normal usage would be adding Fiddler or similar which _would_ require the SSL verification to be turned off (because you're intentionally adding a MITM), but in our case the proxy won't cause an SSL failure.

Would you accept a PR to make it so that we could turn SSL verification on? I was thinking something like:

 * `\Microsoft\Graph\Graph::setProxyPort` should have an additional param for SSL verification (defaulting to false to prevent a BC break)
 * This gets passed to the `GraphCollectionRequest` and `GraphRequest` constructors, and `\Microsoft\Graph\Http\GraphRequest::createGuzzleClient` uses it 
[AB#9228](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9228)

**Comment by SilasKenneth** [comment]
Hello @PatrickRose thanks for raising the issue. There is work in place to make it possible to specify a custom http client with custom config. For accepting PR, YES, we highly welcome contributions to the repo.
