### ISSUE TITLE
Onedrive Business

### ISSUE THREAD

**Issue by raphcadiz** [microsoftgraph/msgraph-sdk-php#47]
Any samples how I can implement this on onedrive

**Comment by cbales** [comment]
There are some [functional test cases](https://github.com/microsoftgraph/msgraph-sdk-php/blob/dev/tests/Functional/OnedriveTest.php) that can serve as samples for OneDrive. Is there a specific scenario you are looking for help with?

**Comment by raphcadiz** [comment]
I have something like this but I'm not able to make it work.

```
$item = $graph->createCollectionRequest("get", "/me/drive/items/1f0ceb1b5de1646c393db8ea8697bc22f")
				->setReturnType(Model\User::class)
				->execute();
return $item;
```

I got error like this.
```
ClientException in RequestException.php line 111:
Client error: `GET https://graph.microsoft.com/v1.0/me/drive/items/1f0ceb1b5de1646c393db8ea8697bc22f` resulted in a `400 Bad Request` response:
{
"error": {
"code": "invalidRequest",
"message": "The request is malformed or incorrect.",
"innerErro (truncated...)

```

**Comment by cbales** [comment]
Have you tried this request in [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer)? You can ask general questions about using the library on StackOverflow with the tag [microsoft-graph](https://stackoverflow.com/questions/tagged/microsoft-graph).

**Comment by lhyx** [comment]
Hi,

The endpoint url for onedrive for business is different.
see https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/direct-endpoint-differences

**Comment by cbales** [comment]
This SDK is only for the Graph API. It does not support the OneDrive API. However, OneDrive for Business is accessible through Graph.

**Comment by raphcadiz** [comment]
@cbales I'm using Onedrive business, I get the sample PHP code from https://developer.microsoft.com but unfortunately I'm not able to make it work with other HTTP request like the one I mention above

**Comment by lhyx** [comment]
Hi,

I'm using this sdk with onedrive for business and it works fine.
You should only use a different endpoint url in the form of https://{tenant}-my.sharepoint.com/_api/v2.0/ to receive an access token and to make calls to the onedrive api.

**Comment by raphcadiz** [comment]
@lhyx did you use some ready to use PHP wrapper? May I know what it is?

**Comment by lhyx** [comment]
Be sure to register your app and give it the correct rights at https://apps.dev.microsoft.com
you need thenetworg/oauth2-azure for the authentication.

`
composer require thenetworg/oauth2-azure

`

Like I said you have to use a different url:
`
$provider = new \TheNetworg\OAuth2\Client\Provider\Azure([
            'clientId'          => 'your_client_id',
            'clientSecret'      => 'your_client_secret',
            'redirectUri'       => 'your_url',
        ]);

$provider->urlAPI = "https://{tenant}-my.sharepoint.com/_api/v2.0/"
$provider->resource = "https://{tenant}-my.sharepoint.com/";

$authUrl = $provider->getAuthorizationUrl();
`
redirect the user to the auth url and get your access token:
`
$token = $provider->getAccessToken('authorization_code', [
                'code' => $_GET['code'],
                'resource' => $provider->resource,
]);

`
I created an app folder for my application and this is how I get the contents:
`       
$graph = new Graph();
$graph->setAccessToken($token);
$graph->setBaseUrl("https://{tenant}-my.sharepoint.com/");
$graph->setApiVersion("_api/v2.0/");
 $item = $graph->createRequest("GET", "drive/special/approot?expand=children")
->setReturnType(Model\DriveItem::class)
 ->execute();
`

Hope this helped :)
