### ISSUE TITLE
Get a specific mail

### ISSUE THREAD

**Issue by chiysom** [microsoftgraph/msgraph-sdk-php#479]
How can i get content for a particular mail message with it's ID? 
[AB#9446](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9446)

**Comment by Ndiritu** [comment]
Hi @chiysom

Here's a snippet to get the content of a message for the currently signed in user:
```php
# ... initialise a Graph object appropriately.

$mailMesssage = $graph->createRequest("GET", "/me/messages/[messageId]")
                      ->setReturnType(Message::class)
                      ->execute();

$content = $mailMessage->getBody()->getContent();
```

Some things to note:
- Ensure you have the correct permissions to access a mail messages (https://docs.microsoft.com/en-us/graph/permissions-reference#mail-permissions)
- Also note that the Id of a message changes if the message is moved to a different folder (https://docs.microsoft.com/en-us/graph/outlook-immutable-id)
- To directly fetch the MIME content of a mail message append `$value` to the endpoint
