### ISSUE TITLE
Get the conversationI/ID of sent mail

### ISSUE THREAD

**Issue by Herz3h** [microsoftgraph/msgraph-sdk-php#48]
Hello,

I'm actually sending a mail using the /me/sendmail endpoint, but in the graph documentation, it says server doesn't send back any response. So is there a way to get the ID or ConversationID of the sent mail ? Or do i have to create the message first as a draft then send it ?

Thanks in advance.

**Comment by cbales** [comment]
Since this is a question about the API and not the SDK, I would recommend that you route these types of questions through StackOverflow with the tag [microsoftgraph]

**Comment by Herz3h** [comment]
Reopening this because i've looked into microsoft graph and it turns out i have to Create the message first and then send it in order to get the id/conversationId of the message. So i've tried to implement this : 

```php
public function createAsync(Model\Message $message){

        $route= "/me/messages";
        $body= $message->jsonSerialize();
        return $this->client
            ->createRequest('POST', $route, true)
            ->attachBody($body)
            ->executeAsync();
    }


    public function sendAsync(Model\Message $message){

        $route= "/me/sendmail";
        $body= ["Message"=>$message->jsonSerialize()];
        return $this->client
            ->createRequest('POST', $route, true)
            ->attachBody($body)
            ->execute();
    }


    public function createAndSendAsync(Model\Message $message)
    {
	    return $this->createAsync($message)->then(function($response) {
		    $returnedMessage = $response->getResponseAsObject(Model\Message::class);
		    return $this->sendAsync($returnedMessage);
	    });
    }
```


But it fails in sendAsync, because the message send has "@odata.context" and "@odata.etag". Here is server response for /me/sendmail :
`The annotation 'odata.context' was found. This annotati (truncated...)`

**Comment by cbales** [comment]
Unfortunately, you cannot reuse the returned object to POST again. This is because of exactly what you are seeing - there will be additional data (transient properties) that get serialized. The correct way to do this is to create a new object with the data you need from the first object.
This pattern becomes especially important in PATCH operations where you only want to send values that have changed to the service.

**Comment by Herz3h** [comment]
Okay I understand now. I got it working thanks.

**Comment by mandersondesign** [comment]
@Herz3h do you have your updated, working code for this? I am curious myself on this! Thanks.
