### ISSUE TITLE
Model Constructor Design

### ISSUE THREAD

**Issue by noahheck** [microsoftgraph/msgraph-sdk-php#5]
Many (All ?) classes within the `Microsoft\Graph\Model` namespace extend `Microsoft\Graph\Model\Entity`. Each has the following private property and constructor:

```php
private $_propDict;

public function __construct($propDict = array())
{
    parent::__construct($propDict);
    $this->_propDict = $propDict;
    return $this;
}
```

At the same time, the `Microsoft\Graph\Model\Entity` also contains the private `$_propDict` property and a similar constructor:

```php
private $_propDict;

public function __construct($propDict = array())
{
    $this->_propDict = $propDict
    return $this;
}
```

The `return` statement from the constructor does nothing, as the purpose of the constructor is to instantiate the object, the return value is essentially ignored. Therefore, all `return` statements from can be removed.

---

I haven't had a chance to look at all `Model`s, but the current management of the `$_propDict` property and the `__construct` functions is a bit confusing. If a `Model` subclass doesn't declare it's own constructor, the parent's constructor will be invoked:

```php
class BaseClass
{
	protected $values;

	public function __construct($values)
	{
		$this->values = $values;
	}
}

class ChildClass extends BaseClass
{
	public function getValues()
	{
		return $this->values;
	}
}

$object = new ChildClass(['stuff', 'stuff2']);

print_r($object->getValues()); // Array('stuff', 'stuff2')
```

The current behavior of the `Model`s though will create 2 full copies of the `$propDict` property whose values will change independent of each other:
```php

class BaseClass
{
	private $values;

	public function __construct($values)
	{
		$this->values = $values;
	}

	public function getParentValues()
	{
		return $this->values;
	}
}

class ChildClass extends BaseClass
{
	private $values;

	public function __construct($values)
	{
		parent::__construct($values);

		$this->values = array_merge($values, ['stuff3']);
	}

	public function getChildValues()
	{
		return $this->values;
	}
}

$object = new ChildClass(['stuff', 'stuff2']);

print_r($object->getParentValues()); // Array('stuff', 'stuff2')
print_r($object->getChildValues());  // Array('stuff', 'stuff2', 'stuff3')
```
If there isn't a specific design reason for the current behavior, we change the visibility of the `$_propDict` property of the `Entity` class to `protected` then remove that property and the constructor of each of the sub-classes.

**Comment by cbales** [comment]
You're totally right. Thanks for catching this redundancy.
