### ISSUE TITLE
Missing getters in Location model (beta API)

### ISSUE THREAD

**Issue by kjfdebruin** [microsoftgraph/msgraph-sdk-php#50]
A typical resource/room contains the following (beta API):
```
Location {#381 ▼
  #_propDict: array:7 [▼
    "displayName" => "Room Name"
    "locationUri" => "room@example.com"
    "locationType" => "conferenceRoom"
    "uniqueId" => "room@example.com"
    "uniqueIdType" => "directory"
    "address" => array:6 [▶]
    "coordinates" => []
  ]
}
```

However, the Location model only contains getters for 

- displayName
- locationEmailAddress (returns empty)
- address

**Comment by cbales** [comment]
The library is generated and only has models for v1.0 as of our most recent release, September 2017.

If you would like to see beta models in the SDK, you can reopen and we will track that request here.

**Comment by kjfdebruin** [comment]
Thanks @cbales - understood. Would it perhaps make sense if the beta models are on a beta or dev branch/tag?
