### ISSUE TITLE
Get User ID upon Create

### ISSUE THREAD

**Issue by marvoh** [microsoftgraph/msgraph-sdk-php#51]
Hi,

Which function do I use to retrieve user ID upon creation since getId() is not defined?

**Comment by cbales** [comment]
This should be exposed through its inheritance path (`User` extends `DirectoryObject` which extends `Entity`).

Are you writing back to the post object after creation?

**Comment by marvoh** [comment]
I will not write back to the object but I needed to save the assigned Id on my end for records purposes

**Comment by cbales** [comment]
You will need to save the response from Graph and get the ID from that returned object. Feel free to open up a question on StackOverflow with the tag [microsoftgraph] if you have any more questions on how to do this.
