### ISSUE TITLE
Add upload item code sample

### ISSUE THREAD

**Issue by roinochieng** [microsoftgraph/msgraph-sdk-php#523]
[AB#9729](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9729)

**Comment by Ndiritu** [comment]
Added to v2-preview [repo samples](https://github.com/microsoftgraph/msgraph-sdk-php/blob/feat/2.0.0/docs/Examples.md#upload-an-item)
