### ISSUE TITLE
Support for Beta models

### ISSUE THREAD

**Issue by cbales** [microsoftgraph/msgraph-sdk-php#53]
As requested by @kjfdebruin in #50

**Comment by cbales** [comment]
Added beta models to their own branch, [beta](https://github.com/microsoftgraph/msgraph-sdk-php/tree/beta), and wrote a [wiki page](https://github.com/microsoftgraph/msgraph-sdk-php/wiki/Using-Beta-Models) on using beta models

**Comment by kjfdebruin** [comment]
Thanks @cbales!
