### ISSUE TITLE
Key check on Entity::getODataType

### ISSUE THREAD

**Issue by alex-code** [microsoftgraph/msgraph-sdk-php#538]
I'm downloading some emails and using `Message::getODataType()`  to detect certain types (i.e #microsoft.graph.eventMessageResponse) but I get an error that `@odata.type` is an `Undefined index` for normal emails.

I can check for the key using `Message::getProperties()` but I feel adding an `array_key_exists` check to `Entity::getODataType()` would be better and would match the other getter methods. 
[AB#10001](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10001)

**Comment by Ndiritu** [comment]
Hi @alex-code 
Thanks for pointing this out. Your proposal makes sense.
Would you like to make this contribution? 😊
