### ISSUE TITLE
Paging issue when paging to page X instead of next

### ISSUE THREAD

**Issue by fabianderijk** [microsoftgraph/msgraph-sdk-php#554]
I'm using the SDK for searching groups and showing these results to the user. We know we can page to the next page, but we want to be able to let the user skip some pages and go from page 1 to (for example) page 3 and back.

This is not possible via the SDK AFAIK, and the /groups endpoint doesn't work with the $skip parameter.

Is there any method / parameter I can use instead? 
[AB#10282](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10282)

**Comment by Ndiritu** [comment]
Hi @fabianderijk, sorry for the delayed response. I am not sure there's a workaround for this.
@MIchaelMainer any thoughts?

**Comment by MIchaelMainer** [comment]
Hello @fabianderijk 

The service API doesn't support an option to request specific page ranges of data for groups. We would need $skip to support this. Most scenarios are supported by paging through the result set and then do client-side paging for the end user.
