### ISSUE TITLE
object return instead of array when call getMeetingTimeSuggestions under MeetingTimeSuggestionResult

### ISSUE THREAD

**Issue by jp-Telus** [microsoftgraph/msgraph-sdk-php#557]
I called the FindMeetingTime API ( /me/findMeetingTimes ) and got the list of suggestion result returned, 

Here is the code:

        $findMeetingEventsUrl = '/me/findMeetingTimes';
        $results = $graph->createRequest('POST', $findMeetingEventsUrl)
            ->addHeaders(['Prefer'=> 'outlook.timezone="Pacific Standard Time"'])
            ->attachBody($newEvent)
            ->setReturnType(Model\MeetingTimeSuggestionsResult::class)
            ->execute();

When I call the getMeetingTimeSuggestions, I only get get an 'object' ("MeetingTimeSuggtesions") instead of array of "MeetingTimeSuggtesions". I expect to get the collections from this call. Do I miss something? Thank you.

       Error
       Cannot use object of type Microsoft\Graph\Model\MeetingTimeSuggestion as array

Source: https://github.com/microsoftgraph/msgraph-sdk-php/blob/dev/src/Model/MeetingTimeSuggestionsResult.php
 
[AB#10302](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10302)

**Comment by SilasKenneth** [comment]
Hello @jp-Telus, thanks for reporting the issue and sorry for the inconveniencies caused. There is a fix which ready for this on [MSGraph-SDK-Code-Generator](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/541). Once this is merged, I will update this issue.

**Comment by SilasKenneth** [comment]
Related to #76 #97
