### ISSUE TITLE
sync mails delta same message ids

### ISSUE THREAD

**Issue by lhyx** [microsoftgraph/msgraph-sdk-php#56]
Hi,

I ran into a problem when I was trying to sync messages.
The ids of the messages in the first 2 pages are exactly the same. 
In all the other pages the the ids are unique.

But the id of the first message of the first page == the id of the first message of the second page
the id of the second message of the first page == the id of the second message of the second page
...

Could this be a bug in the library ?
Here's the code I use to sync the messages:

```
try{
            $graph = new Graph();
            $graph->setAccessToken($token);
            if($deltaLink == false){
                $deltaPageRequest = $graph->createCollectionRequest("GET", "/me/mailFolders/$folder_id/messages/delta")
                    ->setReturnType(Model\Message::class);
            }else{
                $deltaPageRequest = $graph->createCollectionRequest("GET", $deltaLink)
                ->setReturnType(Model\Message::class);
            }  
        }catch(\Exception $e){
            error_log($e->getMessage());
            return array();
        }  

        while (!$deltaPageRequest->isEnd()) {
            $items = $deltaPageRequest->getPage();
            foreach ($items as $item) {
                //here the ids of the messages in the first 2 pages are exactly the same
                $mails[$item->getId()] = $this->parseMail($item);
            }
        }
```

**Comment by cbales** [comment]
Could you try the same request in [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) to see if it is a service or a client bug?

**Comment by lhyx** [comment]
I tried it in the graph explorer but there all the ids seem to be unique.

**Comment by lhyx** [comment]
Hi,

After further research it seems I just have some messages in my mailbox that have the exact same id.
The bug doesn't occur for the 2 first pages in the delta request like i first thought.

And it's not a client bug. The ids are the same in the graph explorer as well.

Is the id of the message not unique ? The messages are in the same folder and have the exact same id. The messages have nothing to do with each other. They are messages with totally different persons.

**Comment by cbales** [comment]
Very strange. Could you post this to StackOverflow for me? You can add the tags [microsoft-graph] and [outlook]. This will ensure that the relevant team follows up with you. Feel free to include the SO link here.

**Comment by lhyx** [comment]
SO link: https://stackoverflow.com/questions/47924610/msgraph-messages-same-ids

**Comment by lhyx** [comment]
Message ids are case sensitive. I'm using mysql wich is case insensitive by default.
So not a bug but a problem with my code.

This fixed the problem:
```WHERE BINARY id=:id```

Thanks for the help.
