### ISSUE TITLE
SubscribedSku inconsistency

### ISSUE THREAD

**Issue by sips-richard** [microsoftgraph/msgraph-sdk-php#570]
On the `SubscribedSku` model `getPrepaidUnits()` contains hydration logic to return a `LicenseUnitsDetail` model for accessing the data, however `getServicePlans()` returns an array of arrays rather than an array of `ServicePlanInfo` models. Additionally the docblock for `setServicePlans()` says it accepts `ServicePlanInfo` rather than an array of `ServicePlanInfo` models, and obviously differs from its getter. 
[AB#10449](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10449)

**Comment by SilasKenneth** [comment]
Hi @sips-richard, sorry for the inconvenience caused. There is fix  on the way([#541](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/541)) to address the issue with collection type properties.
This relates to #76 #97. Will update this when the fix is merged.

**Comment by SilasKenneth** [comment]
Hi @sips-richard, sorry for the inconvenience caused. There is fix  on the way([#541](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/541)) to address the issue with collection type properties.
This relates to #76 #97. Will update this when the fix is merged.

**Comment by Ndiritu** [comment]
Was resolved.
