### ISSUE TITLE
No documentation found

### ISSUE THREAD

**Issue by ritterjo** [microsoftgraph/msgraph-sdk-php#571]
Neither the link offered in the readme (https://github.com/microsoftgraph/msgraph-sdk-php/blob/dev/docs/index.html) nor the link in the wiki (https://github.com/microsoftgraph/msgraph-sdk-php/tree/dev/docs) lead to a valid page. Both lead to a "404 Page not found" Page. Would be great to have the documentation somwhere available.
Thanks Jonas 
[AB#10455](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10455)

**Comment by Ndiritu** [comment]
@ritterjo thanks for reaching out. We acknowledge and apologise that our docs are not the greatest at the moment. We will be working on this soon.

Are the samples & setup steps in the README helpful? Is there anything in particular you're looking for?

**Comment by ritterjo** [comment]
Hi @Ndiritu, thank you for your response. The examples where helpfull for the fist steps, yes thanks for that. But as soon as I wanted to use other objects I got stuck. I was just searching for the list of available objects, their dependencies and their methods and signatures. Therefore it would be enough to just have the documentation generated be PHPDocumentor as mentioned on the wiki page https://github.com/microsoftgraph/msgraph-sdk-php/wiki/Documentation ... my solution for now was to download the repo and run phpDocumentor ... 
Regards
Jonas

**Comment by matthewbecker1990** [comment]
![image](https://user-images.githubusercontent.com/6112221/128813265-57a19a55-9e08-48ce-b277-d56477cb0f6d.png)

**Comment by Ndiritu** [comment]
@ritterjo @matthewbecker1990 Docs have been added to the latest release `1.37,0`
