### ISSUE TITLE
403 Forbidden - Access Denied Error

### ISSUE THREAD

**Issue by Sagar1219** [microsoftgraph/msgraph-sdk-php#583]
I am trying to read inbox messages but getting the below error : 

`Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://graph.microsoft.com/v1.0/me/messages` resulted in a `403 Forbidden` response: {"error":{"code":"ErrorAccessDenied","message":"Access is denied. Check credentials and try again."}} in httpdocs/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113 Stack trace: #0 httpdocs/vendor/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), NULL, Array, NULL) #1 httpdocs/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 httpdocs/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL) #3 httpdocs/vendor/guzzlehttp/prom in httpdocs/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113`

This is the snippet that I am using : 

```
$sendApiRequest = new \GuzzleHttp\Client();
$url = 'https://login.microsoftonline.com/'.TENANT_ID.'/oauth2/v2.0/token';
$data = array("form_params"=> [
        'client_id'=> CLIENT_ID,
        'scope' => SCOPE,
        'grant_type' => 'client_credentials',
        'client_secret'=>CLIENT_SECRET,
    ]);
$response  = $sendApiRequest->post($url,$data)->getBody()->getContents();
$response  = json_decode($response,true); 
$access_token = $response["access_token"];

$graph = new Graph();
$graph->setAccessToken($access_token);
$msgs = $graph->createCollectionRequest("GET",'/me/messages')
            ->setReturnType(Model\Message::class)
            ->execute();
```

My permissions looks like this : 

![Screenshot 2021-08-12 152954](https://user-images.githubusercontent.com/14037958/129178213-8ac17820-4334-445d-8e81-e61c4d40fd48.png)
 
[AB#10650](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10650)

**Comment by Ndiritu** [comment]
Hi @Sagar1219,

I suspect this is being caused by an auth issue.

You should be able to access the messages by calling `/users/{[username]@[tenant]}/messages` - [Docs link](https://docs.microsoft.com/en-us/graph/api/user-list-messages?view=graph-rest-1.0&tabs=http#http-request)

To use `/me/...` your application needs a signed-in user. The auth flow for this depends on what type of app you're building
Please see these [docs](https://docs.microsoft.com/en-us/graph/auth/auth-concepts#next-steps)

Please let me know if this works.

**Comment by Sagar1219** [comment]
Hi @Ndiritu 

I polled the below API and getting result:
URL : https://graph.microsoft.com/v1.0/users
Response : 
`
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users",
    "value": [
        {
            "@odata.id": "https://graph.microsoft.com/v2/dc61fe8f-b4bc-4df0-993a-8d9647fd172c/directoryObjects/78b31819-c09d-4f2c-979c-48dfba7e52b4/Microsoft.DirectoryServices.User",
            "businessPhones": [],
            "displayName": "Sagarika",
            "givenName": "Sagarika",
            "jobTitle": null,
            "mail": null,
            "mobilePhone": null,
            "officeLocation": null,
            "preferredLanguage": null,
            "surname": "Swarup",
            "userPrincipalName": "sagarika.swarup.cipl_outlook.com#EXT#@ceimlessdev.onmicrosoft.com",
            "id": "78b31819-c09d-4f2c-979c-48dfba7e52b4"
        }
    ]
}
`

Now check the result of the below API polling as you suggested :

URL : https://graph.microsoft.com/v1.0/users/sagarika.swarup.cipl_outlook.com#EXT#@ceimlessdev.onmicrosoft.com/messages 
Response : 

`
{
    "error": {
        "code": "Request_ResourceNotFound",
        "message": "Resource 'sagarika.swarup.cipl_outlook.com' does not exist or one of its queried reference-property objects are not present.",
        "innerError": {
            "date": "2021-08-15T10:40:15",
            "request-id": "0a0d3748-47a5-4d69-a227-1bd1d011e06b",
            "client-request-id": "0a0d3748-47a5-4d69-a227-1bd1d011e06b"
        }
    }
}
`

Also, checked with another API just in case : 

URL: https://graph.microsoft.com/v1.0/users/sagarika.swarup.cipl_outlook.com#EXT#@ceimlessdev.onmicrosoft.com/drive

Got the same result as above.

Please tell me what I am missing here?

**Comment by Ndiritu** [comment]
@Sagar1219 sorry for the late response.

You'd need to replace the `#` with `%23` as mentioned in [the docs](https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http#http-request)

**Comment by Ndiritu** [comment]
No further correspondence from customer

**Comment by Sagar1219** [comment]
Thanks everyone. This issue has been resolved.
