### ISSUE TITLE
Add Code Coverage tracking using SonarCloud

### ISSUE THREAD

**Issue by Ndiritu** [microsoftgraph/msgraph-sdk-php#585]
https://github.com/microsoftgraph/msgraph-sdk-php-core/pull/5 add code coverage tracking to the Core library.

This can be improved by making Code Coverage analysis a stand-alone PR validation step. This would need consideration of existing 3rd party open source & proprietary tools vs custom scripting to do this

Would also be a bonus to add a coverage badge to our README 
[AB#10694](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10694)

**Comment by Ndiritu** [comment]
SonarCloud was recommended during Michael's compliance work.

**Comment by SilasKenneth** [comment]
Yes, I have added a coverage badge to other repositories. I'll be adding it to core once the repo is added to SonarCloud.
