### ISSUE TITLE
Open Extensions on mail Message

### ISSUE THREAD

**Issue by Herz3h** [microsoftgraph/msgraph-sdk-php#59]
Hello,

I'm trying to add Open Extension to a mail message. 

After reading Microsoft Graph documentation about OpenExtensions, I understand that I have to add this to my json when creating/sending my message : 

```
{
// Message body here
"extensions": 
    {
        "@odata.type":"microsoft.graph.openTypeExtension",
        "extensionName": "com.mydomain.myextensioname",
        "mydatakey": "mydata"
    }
}
``` 

However since I'm using this SDK, I'm not sure if this can be done with the SDK. For instance I see that there is a setExtension() method on the Message model, and there is an OpenTypeExtension class, but it only takes an extensionName.

So if adding custom data with Open Extensions is possible with this SDK, where do I add my custom data ? 

Thanks.

**Comment by cbales** [comment]
You should be able to add your data manually to the Extension object:

```php
$extension = new Model\Extension(array("theme" => "dark", "extensionName" => "Extension 1"));
```

 You can refer to the [OpenTypeTest.php](https://github.com/microsoftgraph/msgraph-sdk-php/blob/dev/tests/Functional/OpenTypeTest.php) to see an example of this in action. You can omit setting the API version since open extensions are now in v1.0.

**Comment by Herz3h** [comment]
Coming back this, as I forgot to update issue. Here is the working code I use in case someone has same need as I had :        
 ```
$customProperty = new Model\SingleValueLegacyExtendedProperty();
$namespaceGuid = "f5939744-0f22-4f03-b33c-f18a8acfa20b"; // Random GUID I picked from this repository
$mapiPropertyType = "String "; 
$propertyName = "MyPropertyName";
$propertyId = $mapiPropertyType . "{" . $namespaceGuid . "} Name " . $propertyName;
$customProperty->setId($propertyId);
$customProperty->setValue($internetMessageId);
$extendedValueCollection[] = $customProperty;

$route = "/me/messages/$messageId";
        $message = new Model\Message();
        $message->setSingleValueExtendedProperties($extendedValueCollection);
        return $this->client
            ->createRequest('PATCH', $route, true)
            ->attachBody($message)
            ->execute();

```
