### ISSUE TITLE
Add multiple member and Generation Team code

### ISSUE THREAD

**Issue by minhvn** [microsoftgraph/msgraph-sdk-php#610]
Dear all, 
Can help me way how to add multiple member at the one request, Im see each request only for one member.
And, How can add settings general team code.
Many thanks.
Minh

**Comment by Ndiritu** [comment]
@minhvn adding multiple members within one request as shown in the [docs](https://learn.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-1.0&tabs=http#example-2-add-multiple-members-to-a-group-in-a-single-request) is NOT currently supported. 

Work to support `@odata.bind` is being tracked under #137.

Kindly clarify the second part of your question...
"And, How can add settings general team code."

**Comment by Ndiritu** [comment]
closing as duplicate of #137
