### ISSUE TITLE
UploadSession example

### ISSUE THREAD

**Issue by Herz3h** [microsoftgraph/msgraph-sdk-php#62]
Hello,

I'm trying to [upload files ](https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/driveitem_createuploadsession)to OneDrive, but I don't see any example of UploadSession in this repo even tho the UploadSession model exists. 

Could you provide an example please ? 

Thanks

**Comment by MIchaelMainer** [comment]
I'm sorry to say that we don't have an example for this API at this point. Please post questions like this to StackOverflow with the microsoftgraph tag. 

In case it helps, here's the commit in the .Net client library where we implemented large file uploads.
microsoftgraph/msgraph-sdk-dotnet@7c037cf#diff-374daffefc443a2b383da1d332b730c6

**Comment by Herz3h** [comment]
I managed to do this, will post code later. 

Also, posting on stackoverflow doesn't seem to get me any answer, so...

**Comment by vijayrana99** [comment]
@Herz3h How did you managed to make it work for Upload? Can you share some code example?

**Comment by Herz3h** [comment]
Here is the code I've been using: 

```php
private function uploadLargeFile(string $localFilePath, string $remoteFilePath, $conflictBehavior, $timeout)
    {
        $remoteFilePath = $this->formatPath($remoteFilePath);
        $remoteFilePath = $this->prependRootFolder($remoteFilePath);
        $route = "$this->prefix/drive/root:$remoteFilePath:/createUploadSession";

        $data = [
            'item' => [
                '@microsoft.graph.conflictBehavior' => $conflictBehavior,
            ]
        ];

        /** @var Model\UploadSession $uploadSession */
        $uploadSession = $this->client->createRequest('POST', $route, true)
            ->setReturnType(Model\UploadSession::class)
            ->attachBody($data)
            ->execute();


        $fileContent = file_get_contents($localFilePath);
        $fileSize = filesize($localFilePath);
        $uploadHeaders = [
            'Content-Length' => "$fileSize",
            'Content-Range'  => 'bytes 0-' . ($fileSize - 1) . DIRECTORY_SEPARATOR . $fileSize
        ];


        $uploadUrl = $uploadSession->getUploadUrl();
        $item = $this->client->createRequest('PUT', $uploadUrl, true)
            ->attachBody($fileContent)
            ->addHeaders($uploadHeaders)
            ->setReturnType(Model\DriveItem::class)
            ->setTimeout($timeout)
            ->execute();

        return $item;
    }
```

**Comment by vijayrana99** [comment]
@Herz3h Thank You. I will definitely give it a try
