### ISSUE TITLE
File download throws exception on fclose

### ISSUE THREAD

**Issue by Herz3h** [microsoftgraph/msgraph-sdk-php#63]
Hello,

I have an issue where [this line ](https://github.com/microsoftgraph/msgraph-sdk-php/blob/master/src/Http/GraphRequest.php#L339) throws an exception : 

`Warning: fclose(): supplied argument is not a valid stream resource
`

This seems to be fixed in the [dev branch](https://github.com/microsoftgraph/msgraph-sdk-php/blob/master/src/Http/GraphRequest.php#L340) with that is_resource check. 

Problem being, that I have installed this package with composer and i have the 1.1.1 version. When is the dev branch getting pushed to composer ? Or what would be a good way to workaround this for the time being ?

**Comment by cbales** [comment]
Sorry to hear that this has been blocking you. We are publishing a block of changes in a few weeks and will include all of the bugfixes in dev as part of this push. In the meantime, you can make the change locally to your vendor/microsoft/microsoft-graph file

**Comment by Herz3h** [comment]
Alright thanks for the infos, I'll just change it locally until it gets released.
