### ISSUE TITLE
@odata.nextLink question - How to get list of all users (not only the first 100)

### ISSUE THREAD

**Issue by milanlatinovic** [microsoftgraph/msgraph-sdk-php#64]
Hi Caitlin,

Firstly, my name is Milan and I work for a company called TimeTac. I am working on synchronization service between Microsoft Azure (using Graph API) and our TimeTac system. At one point, I found out about your project 'Microsoft Graph SDK PHP' and I decided to test it out.

Most importantly, thank you for your effort! This library works very well and I managed to accomplish most of what I needed, but I believe I find an issue (or bug), so I wanted to ask you about this. Let me describe it shortly:

When I use /users to fetch all the users I get first 100 of users (because endpoint returns paginated results. Also in that response, there is a field called @odata.nextLink, where I should be able to read a link to get next 100 of users, etc.

I use this part of the code to get a list of the users:
$users = $graph->createRequest("GET", "/users")
    ->setReturnType(Model\User::class)
    ->execute();
This code will return first 100 of users, but I see no way to get @odata.nextLink in order to read all of them. My questions are:

1. Should the SDK API be aware of nextLink field and return all data to me? 
2. If not, what can I do to get @odata.nextLink at the same time when I executeRequest and get a list of the users?

To clarify, my final goal is to get array $users which have all users (not only the first 100, as it currently does). What would be the best approach to accomplish this with your SDK?

p.s. If I was using Guzzle alone (without your SDK) I would get whole response and find @odata.nextLink field, then create some kind of while(@odata.nextLink) structure to iterate through all the users, but I'm not sure how to do it here, because I'm not getting $response, but a $users array. 

I was reading through documentation and comments inside your code, but I haven't found a suitable solution. Any help would be appreciated.

Kind regards,

**Comment by cbales** [comment]
Have you tried using a [CollectionRequest](https://github.com/microsoftgraph/msgraph-sdk-php/wiki/Example-calls#get-a-collection-of-items) instead of a regular request object?

```php
$userIterator = $graph->createCollectionRequest("GET", "/users")
			        ->setReturnType(Model\User::class)
			        ->setPageSize(100);
$users = $userIterator->getPage();

foreach ($users as $user){
	$userArray[] = $user->getDisplayName();
}
```

**Comment by cbales** [comment]
Since there is some confusion around how to page through collections in this SDK, I added a [wiki page](https://github.com/microsoftgraph/msgraph-sdk-php/wiki/Paging-through-Collections) devoted to this instead of cramming it into the examples page. Do you think this helps?

**Comment by daveismyname** [comment]
@milanlatinovic I went the guzzle route mainly due to not getting a response to my issue. I have today but I've already moved away from the SDK so how I'm getting the records is like this:

```
$limit = 25;
$offset = 50;
$skip = request('next', 0);

$messageQueryParams = array (
    //"\$select" => "subject,receivedDateTime,from",
    "\$orderby" => "displayName",
    "\$skip" => $skip,
    "\$top" => $limit,
    "\$count" => "true",
);

$contacts = Api::get('me/contacts?'.http_build_query($messageQueryParams));

$previous = null;
$next = null;
$total = $contacts['@odata.count'];
if (isset($contacts['@odata.nextLink'])) {
    $first = explode('$skip=', $contacts['@odata.nextLink']);
    $skip = explode('&', $first[1]);
    $previous = $skip[0]-$offset;
    $next = $skip[0];

    if ($previous < 0) {
        $previous = 0;
    }

    if ($next == $total) {
        $next = null;
    }
}
```

The Api::get is calling a class where I have guzzle setup for reusability:

```
class Api
{
    protected static $baseUrl = 'https://graph.microsoft.com/beta/';

    public static function __callstatic($function, $args) {

        $options = ['get', 'post', 'patch', 'delete'];
        $path = (isset($args[0])) ? $args[0] : null;
        $data = (isset($args[1])) ? $args[1] : null;

        if (in_array($function, $options)) {
            return self::guzzle($function, $path, $data);
        }
    }

    protected static function guzzle($type, $request, $data = []) {

        $client = new \GuzzleHttp\Client;
        $tokenCache = new Token();

        $response = $client->$type(self::$baseUrl.$request, [
            'headers' => [
                'Authorization' => $tokenCache->getAccessToken(),
                'content-type' => 'application/json',
            ],
            'body' => json_encode($data),
        ]);

        return json_decode($response->getBody()->getContents(), true);
    }
```

You might not want to do this way and stick with the SDK but it's an option.

**Comment by milanlatinovic** [comment]
@cbales thank you for your quick answer, I really appreciate it.

I have tried CollectionRequest as you proposed and it seems like I'm getting a proper results now. (It is a very large collection so I'll have to examine its contents some more to make sure that all pages are properly included).

Related to your code sample, I changed it a bit to be able to create an unique array with all the results. After reading trough your class I found isEnd() function and combined it with getPage() to iterate trough everything.

Right now, that part of the code looks like this:

          $userIterator = $graph->createCollectionRequest("GET", "/users")
                ->setReturnType(Model\User::class)
                ->setPageSize(100);

           while (!$userIterator->isEnd()) {
                $users = array_merge($users,$userIterator->getPage());
            }

Maybe you want to add this part with while() iterator to your documentation as well, just to make it more clear that whole array (with all of the results) can be created easily.

@daveismyname thanks for the idea! Yes, this seems like a very nice approach to handle pagination issue using just Guzzle. Since my work is not related to Microsoft API only, and I do plan to use Guzzle quite a bit, I will use this/your approach in my pure-Guzzle parts of the code. I especially like the part with Api class for the re-usability. 

So, thank you both, I believe that this tread will be helpful to the other users of SDK as well, we can mark this issue as resolved now. :) If I have any more useful materials related to this subject I will add it in future.

**Comment by chilipepper987** [comment]
The solution works great. Just want to note that calling ->setPageSize(100); will break the request if $top is already part of the query string. The API balks if its set twice.

**Comment by jozeflambrecht** [comment]
@milanlatinovic Thank you for your code example.

I can only use 

`while (!$userIterator->isEnd()) {
...
}`

when I do not use `->setPageSize(100)` in the query. When I use `->setPageSize(100)`, I only get the first page.

Thanks again for sharing!
