### ISSUE TITLE
Download file or retrieve document information from DocumentID

### ISSUE THREAD

**Issue by mhuckaby21** [microsoftgraph/msgraph-sdk-php#640]
Is it possible to download a document and to retrieve document information from the document ID (for example: https://sitename.sharepoint.com/_layouts/15/DocIdRedir.aspx?ID=DOCPREFIX-2102552153-44)

**Comment by Ndiritu** [comment]
Kindly refer to https://learn.microsoft.com/en-us/answers/questions/601256/downloading-docuemtn-form-sharepoint-documents-usi.html
