### ISSUE TITLE
userPrincipalName and displayName not showing correctly

### ISSUE THREAD

**Issue by deanobaldwin** [microsoftgraph/msgraph-sdk-php#643]
I've been using the office365ActiveUserDetail query in my PHP application and that has been working without issue. I have, today, discovered that the userPrincipalName and displayName are now showing digits instead of names (I've obfuscated the output) when I run my code:

> [userPrincipalName] => 624F6624C7156A901903535xxxxxx
> [displayName] => 096CA25213B52FDED896B9Dxxxxxxx

I haven't changed anything in my code and cannot find a bug related to this. No matter what tenant I connect to, I get the same output whereas I used to see the user's name/display name. My code was originally using version 1.25 of the Microsoft-graph PHP library and I upgraded to 1.40 this morning but am still seeing the same output. 

Any ideas?

Thanks,
Dean

**Comment by Ndiritu** [comment]
@deanobaldwin kindly confirm if this is the request you're making? https://learn.microsoft.com/en-us/graph/api/reportroot-getoffice365activeuserdetail?view=graph-rest-1.0

**Comment by Ndiritu** [comment]
Closing since there's no feedback from customer.
