### ISSUE TITLE
Improve support for Enum Flags

### ISSUE THREAD

**Issue by tomw-ucb** [microsoftgraph/msgraph-sdk-php#649]
Dear MS team,

We have a few win32LobApps (Beta model) in our Intune environment, where we can not access the **applicableArchitectures** property, due that it does not recognize the enumeration value **"x86,x64"**

Involved classes :
Beta\Microsoft\Graph\Model\Beta\Microsoft\Win32LobApp
Beta\Microsoft\Graph\Model\Beta\Microsoft\Graph\Model

In the attachments you can find a returned managed app data : [ManagedApp_#microsoft.graph.win32LobApp.json.txt](https://github.com/microsoftgraph/msgraph-sdk-php/files/7355744/ManagedApp_.microsoft.graph.win32LobApp.json.txt)
 
Kind Regards

Tom Werkhoven

**Comment by Ndiritu** [comment]
Resolved in 2.0
