### ISSUE TITLE
otherMails

### ISSUE THREAD

**Issue by michael-morris** [microsoftgraph/msgraph-sdk-php#65]
Is there access to otherMails field while creating a user?
I can't seem to find this

**Comment by cbales** [comment]
Can you be more specific and provide a link to the functionality you are looking for in the documentation? This is not something exposed via the API that I can find.

**Comment by michael-morris** [comment]
Sorry, I just realized it's apart of  the Azure graph API. it's for setting the additional e-mail field for alternative verification.

**Comment by cbales** [comment]
Sorry to hear that it's not yet at parity with what you are looking for
