### ISSUE TITLE
📢 Try out the version 2.0.0 preview release📢

### ISSUE THREAD

**Issue by Ndiritu** [microsoftgraph/msgraph-sdk-php#681]
The Microsoft Graph PHP SDK v2.0.0 is available for preview now!

A number of new features, improvements and breaking bug fixes have been  added including:
- [Bug Fix] Model getters expected to return a collection of entities now work as expected.
- Support for PSR-18 and HTTPlug compliant HTTP client libraries
- Moved Beta models to the Microsoft Graph Beta SDK.
- Strongly typed method parameters and return type declarations

See the [Upgrade Guide](https://github.com/microsoftgraph/msgraph-sdk-php/blob/feat/2.0.0/UPGRADING.md) for more comprehensive details on changes made in version 2.0.0.

We'd really appreciate your feedback. Feel free to create issues on this repository and contribute off the `feat/2.0.0` branch.

To try out this preview version:
```
{
    "minimum-stability": "RC",
    "require": {
        "microsoft/microsoft-graph": "^2.0.0-RC1",
    }
}
```
OR
```
{
    "require": {
        "microsoft/microsoft-graph": "^2.0.0-RC1",
        "microsoft/microsoft-graph-core": "@RC"
    }
}
```

In addition, we'd love to engage with you more as we build future versions by tagging you on future announcements/questions. This initial list was extracted from our contributors, issue creators and those who've interacted with the issues in any way over the past year. If you're not currently tagged and would like to be added in future issues, please 👍🏾 this issue and to be removed from this list, please 👎🏾 this issue.

@Thomas-Rosenkrans-Vestergaard,@cedx,@jasverix,@noahheck,@vpcomo,@Matt-B50,@marcmaalouly,@baj84,@nadeem706,@lambasoft,@fanonwue,@Trynomial-Solutions,@landall,@Sagar1219,@Koenvh1,@anvanza,@tomw-ucb,@jeremy-vvf,@fabianderijk,@dan-silver,@sips-richard,@mgrinspan,@hassanacto,@mvdschot,@lawrenceong001,@mankowitz,@boredom2,@PatrickRose,@pboese,@pk-informatics,@TussharTikoo,@gorets,@risototh,@Zombaya,@iampoul,@waynehaffenden,@chiysom,@edvinysz,@wsenjer,@tolbon,@minhvn,@craigpaul,@deanobaldwin,@jp-Telus,@alessiovietri,@ritterjo,@fbcouch,@tdondich
@osalabs,@Jarzon

**Comment by Ndiritu** [comment]
@deleugpn,@elgranchuy,@Josje92,@alex-code,@saulens22,@eturnq,@Tanuel,@nokafor,@Herz3h,@hubipe,@Sam-Othman,@Levure,@lordisp,@Huskynarr,@andrii-boiko,@elijahchancey,@ificator,@curry684,@irworks,@tomsix,@matthewbecker1990,@krizalys,@guilliamxavier,@Lntnam,@fibis,@mhuckaby21,@MiDniGG,@MCorbo7,@Zeit42,@samuelsantaera,@ronnyjss

**Comment by deleugpn** [comment]
While I appreciate being personally notified about this, I assume that is a little in vain. People integrating with Microsoft often works at an enterprise level application and we had to move forward somewhere. We ended up using the FetchXml layer around the Dataverse and our integration is already done.

**Comment by curry684** [comment]
I actually started a new project quite recently and am in a position to switch to RC. Will do so happily.

Must say I'm surprised there's still no really good handling for `null` results from what I see. Specifically, querying `/users/{id}/manager` will return a 404 (correctly) for the CEO in any organization. Is there any reasonable way to handle this apart from catching the `GraphClientException` and inspecting the return code? Even though this implies using exceptions for regular expected program flow, which is of course bad practice by any standard?

**Comment by Ndiritu** [comment]
> While I appreciate being personally notified about this, I assume that is a little in vain. People integrating with Microsoft often works at an enterprise level application and we had to move forward somewhere. We ended up using the FetchXml layer around the Dataverse and our integration is already done.
> 
> Best of luck on the release!. I truly hope it's easier to integrate for future projects

Thanks for your feedback @deleugpn.

We'd love to hear what your pain-points were while considering this SDK.

**Comment by curry684** [comment]
Upgrading was a breeze, upgrade guide works fine, barely had to change any code except for the changed exceptions. Application is working as before (syncing AD users, groups and their memberships to a local database).

I say good work  :)
