### ISSUE TITLE
Investigate demand for request builders

### ISSUE THREAD

**Issue by Ndiritu** [microsoftgraph/msgraph-sdk-php#690]
Kiota provides a fluent request builder pattern for building URLs to various graph entities 

e.g. To get a user's messages 

WITHOUT request builders (as is the current case):
----------------------------------------------------------
```
$graph->createRequest('/users/{userId}/messages)->setReturnType(Message::class)->execute();
```

A customer has to explicitly set the URL string and the return type, meaning they potentially check the Graph API reference docs to know what endpoint to call & what type of object to expect in return & search the SDK for the model.

Using request builders
--------------------------
```
$messages = $graphClient->usersById({userId})->messages()->get();
```
Here, a developer doesn't need to use the raw URL and the developer knows in advance that a Message object is returned by the messages() method

**Comment by Ndiritu** [comment]
From what I see, Fluent builder interfaces are not explicitly discouraged e.g. in the Python case.

The pattern is used in a bunch of popular libraries e.g. [Laravel's Eloquent ORM](https://laravel.com/docs/5.0/eloquent) to build queries.

I think request builders would be beneficial for the SDK to prevent manually setting return types etc. We also already use method chaining in our current v1 and v2 preview releases as a pattern e.g. `$graph->createRequest()->addHeaders()->addBody()->execute();`

**Comment by MIchaelMainer** [comment]
Let's do it!
