### ISSUE TITLE
Investigate viability of building Kiota PHP for PHP 8

### ISSUE THREAD

**Issue by Ndiritu** [microsoftgraph/msgraph-sdk-php#693]
Potential benefits:
- [ ] Enums

**Comment by MIchaelMainer** [comment]
Note that I don't know if PHP8 enums support enum flags.

**Comment by Ndiritu** [comment]
It’s still early to build for PHP 8 as our minimum required version. According to Packagist in May ’21, [~ 85% of apps are still using PHP 7](https://blog.packagist.com/php-versions-stats-2021-1-edition/).
 
The PHP SDK still lags in terms of feature parity with other languages. Requiring PHP 8 would potentially lock out more customers from new features yet to be added.

A proposal however is made to support PHP 7.4 as a minimum requirement. V2 Preview release requires PHP 7.3. According to Packagist, PHP 7.4 is the MOST used PHP version with almost half of the apps worldwide using it (~45% adoption).

In addition, our current SDK would still work for a PHP 8 customer since we DON’T use any breaking features.

**Comment by Ndiritu** [comment]
Interesting to note that about 50% of customers are on PHP 7.4 and 25% on PHP 8- https://packagist.org/packages/microsoft/microsoft-graph/php-stats

**Comment by Ndiritu** [comment]
Please re-open if there are any more thoughts on this

**Comment by Ndiritu** [comment]
> Note that I don't know if PHP8 enums support enum flags.

Realised I didn't address this + missed the notification/conversation on #649.
No, PHP 8 Enums don't support flags. We'd potentially need to create a custom `EnumFlag` type.
