### ISSUE TITLE
Creating custom onlinemeeting in calendar event

### ISSUE THREAD

**Issue by rodrigoguariento** [microsoftgraph/msgraph-sdk-php#707]
Dear ones, our platform is connected with our customer(company) calendar at Microsoft (using Graph, this SDK). This customer has a Webex account, but his Webex does not sync with Microsoft. In this scenario, I tried to create an event in the user's Microsoft calendar with custom conference data (online meeting) using the Webex Personal Room link, and I couldn't find any reference from Microsoft on how to do this.

https://docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-1.0&tabs=http#http-request

**Comment by MIchaelMainer** [comment]
Note: I don't have inside information about how this should be done. This is what I'd try if I were you.

I suggest that you add create template HTML for the event body that makes it clear that the meeting is hosted via WebEx. You'll want to inject the link to the WebEx meeting into the template and then apply the template to the event body. All attendees of the meeting will have the same link. This is what gets injected for Teams meetings:

![image](https://user-images.githubusercontent.com/8527305/141835833-00572f78-5dd0-4d0f-bf69-08141f0066e3.png)

While you're at it, you might as well set isOnlineMeeting to true, and set onlineMeetingProvider to unknown on the [event](https://docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0) properties. I don't know what value you get from these, but in case there is, you might as well set them.

**Comment by rodrigoguariento** [comment]
Thanks @MIchaelMainer , I tried:

```
$event->setIsOnlineMeeting(true);
$event->setOnlineMeetingProvider('unknown');
$event->setOnlineMeetingUrl('https://my-company.webex.com/meet/rodrigoguariento99');
```

But a link with MicrosoftTeams is generated into the event. When I setIsOnlineMeeting(false) the setOnlineMeetingProvider and setOnlineMeetingUrl is ignored.

I would really like to know how to create a custom "joinWebUrl" ( https://docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0 ).

**Comment by MIchaelMainer** [comment]
@rodrigoguariento I think the docs say that OnlineMeetingUrl is read only. In fact, I see that it isn't actually set in my Teams meetings. 

I see now what you're trying to do with the joinWebUrl. That property is read-only. I'm not sure you'll be able to set that property. I suggest that you ask your question on [Microsoft Q & A](https://docs.microsoft.com/en-us/answers/search.html?c=&includeChildren=&f=&type=question+OR+idea+OR+kbentry+OR+answer+OR+topic+OR+user&redirect=search%2Fsearch&sort=relevance&q=microsoft-graph-*) as we are not experts on that API. Please post a link to your question on Microsoft Q & A here in this issue.

You can still set the information in the body of the event.
