### ISSUE TITLE
Return type will change on some methods

### ISSUE THREAD

**Issue by flohw** [microsoftgraph/msgraph-sdk-php#742]
Hi Team,

I am encountering an error during my tests. I am mocking the UploadSession object for the `getUploadUrl` method.

I get the following error:
`
During inheritance of JsonSerializable: Uncaught Return type of Microsoft\Graph\Model\Entity::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice`
(I am running phpunit under symfony framework so the notice is transformed to a fatal error)

Adding the `#[\ReturnTypeWillChange]` attribute on the method would fix the problem. Maybe there are other part of the code where this change is needed.

I am running these tests with php 8.1

Thank you

**Comment by flohw** [comment]
Seems to be on my side. The symfony deprecation helper was enabled so it transforms notices to fatal errors.

Maybe it would still be a good idea to make some changes to be more future proof on that code?

I let you close this issue if it's not relevant.

I also provided a PR to fix this in case you want.

Thank you

**Comment by ihr-it-projekt** [comment]
See https://github.com/microsoftgraph/msgraph-sdk-php/pull/862
