### ISSUE TITLE
Php 8.1 deprecation warning

### ISSUE THREAD

**Issue by olischmidt123** [microsoftgraph/msgraph-sdk-php#753]
Just updated to php 8.1 and noticed some deprecation warning:

PHP Deprecated:  Return type of Microsoft\Graph\Model\Entity::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in vendor/microsoft/microsoft-graph/src/Model/Entity.php on line 119

**Comment by ihr-it-projekt** [comment]
i have open already a PR for this kind of issue: https://github.com/microsoftgraph/msgraph-sdk-php/pull/862

**Comment by nikolaypronchev** [comment]
Hi! Template generation fixed in [this PR](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/759). As i don't see any other PHP8.1 compatibility problems, we need only to re-generate models. Is Are they generated automatically on MSGraph-SDK-Code-Generator update?

**Comment by Ndiritu** [comment]
They'll be re-generated automatically next week Tuesday and we can merge them into next week's release. Thanks again for fixing this.

**Comment by ihr-it-projekt** [comment]
Thx you also from my side. :-)

**Comment by Ndiritu** [comment]
Resolved in latest release
