### ISSUE TITLE
Problem authentication  & permission

### ISSUE THREAD

**Issue by ardyanto** [microsoftgraph/msgraph-sdk-php#781]
I try to upload file

	$graph = new Graph();
        $graph->setAccessToken($accessToken);
		
        $graph->createRequest("PUT", "/v1.0/me/drive/root:/Documents/test.xlsx:/content")
              ->upload("C:/laragon/www/onedrive/test.xlsx");

I got an error :

"error":{"code":"BadRequest","message":"/me request is only valid with delegated authentication flow."

how to fix it?

**Comment by Ndiritu** [comment]
@ardyanto Using `\me` in your URL requires a user to sign in on your application.

If your application has been granted "Application Permissions" on the Azure Portal, then replace [`\me` in your URL with `\users\{user@yourtenant.com}`](https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http#http-request)

Kindly have a look at [our Authentication docs](https://docs.microsoft.com/en-us/graph/auth/auth-concepts) for more.

**Comment by ardyanto** [comment]
@Ndiritu thanks for you response.. 

I ready replace \me with \user\{id tenannt}

but i got error : 

{"code":"BadRequest","message":"Unable to retrieve tenant service info." }

**Comment by Ndiritu** [comment]
@ardyanto please refer to a similar issue that was created earlier [here](https://docs.microsoft.com/en-us/answers/questions/284884/msgraph-unable-to-retrieve-tenant-service-info.html) to see if the recommended steps solve your problem

**Comment by Ndiritu** [comment]
Resolved
