### ISSUE TITLE
Creating an event works, but how can you update events?

### ISSUE THREAD

**Issue by basementmedia2** [microsoftgraph/msgraph-sdk-php#787]
Hi,

the following code works fine and generates a new event in my calendar:

```
<?php
require_once __DIR__ . '/vendor/autoload.php';
 
// Include the Microsoft Graph classes
use Microsoft\Graph\Graph;
use Microsoft\Graph\Model;
$tenantId="myTenantId";
$clientId="myClientID";
$clientSecret="mySecret";

$guzzle = new \GuzzleHttp\Client();
$url = 'https://login.microsoftonline.com/' . $tenantId . '/oauth2/token?api-version=1.0';
$token = json_decode($guzzle->post($url, [
    'form_params' => [
        'client_id' => $clientId,
        'client_secret' => $clientSecret,
        'resource' => 'https://graph.microsoft.com/',
        'grant_type' => 'client_credentials',
    ],
])->getBody()->getContents());

$accessToken = $token->access_token;
$graph = new Graph();
$graph->setAccessToken($accessToken);

$attendees = [];
array_push($attendees, [
  'emailAddress' => [
  'address' => 'my@email.de',
  'name' => 'myname'
  ],
   'type' => 'required'
]);
$newEvent = [
    'subject' => 'Test',
    'isAllDay' => true,
    'attendees' => $attendees,
    'start' => [
      'dateTime' => '2022-02-09T00:00:00',
      'timeZone' => 'W. Europe Standard Time'
    ],
    'end' => [
      'dateTime' => '2022-02-10T00:00:00',
      'timeZone' => 'W. Europe Standard Time'
    ],
    
    'location' => [
        'displayName' => 'Some room'
    ],
    'body' => [
      "contentType" => "HTML",
      "content" => "<p>That's a test</p>"
    ]
  ];

$response = $graph->createRequest('POST', '/users/my@email.de/calendar/events')
  ->attachBody($newEvent)
  ->setReturnType(Model\Event::class)
  ->execute();

$outlook_id=$response->getId();

?>
```

But the following does not work (code is directly placed below the code above and outlook_id is generated correctly:

```
$newEvent = [
  'subject' => 'Test UPDATED'
];

$response = $graph->createRequest('POST', '/users/my@email.de/calendar/events/'.$outlook_id)
  ->attachBody($newEvent)
  ->setReturnType(Model\Event::class)
  ->execute();

$outlook_id=$response->getId();
```
The following fault message is generated:

`Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://graph.microsoft.com/v1.0/users/my@email.de/calendar/events/AAMkAGE4NmI2MmZkLWJjNzktNDBmMS1hZGY4LWIxMzBjNmY4MWI3OQBGAAAAAAAlT71tgzMxT4lEEyvGxik9BwDrnNWima7tSIuOg9AgCoUfAAAAAAENAADrnNWima7tSIuOg9AgCoUfAABJ7ehrAAA=` resulted in a `405 Method Not Allowed` response: {"error":{"code":"ErrorInvalidRequest","message":"The OData request is not supported."}} in /some/path/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113 Stack trace: #0 /some/path/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 /some/path/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 /some/path/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::c in /some/path/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113`

Can someone help please ;-(
Do i use the wrong endpoint?
Are there additional permissions to be set for updating events?

Best wishes
Daniel

**Comment by Ndiritu** [comment]
@basementmedia2 you'd need to make a `PATCH` request and not a `POST` ([Reference docs](https://docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&tabs=http#http-request))

**Comment by basementmedia2** [comment]
Hi,

do you have a PHP-example for PATCH-request?
I only find examples for other language-types.

I tried just to replace POST with PATCH 

```
$newEvent = [
  'subject' => 'Test UPDATED'
];

$response = $graph->createRequest('PATCH', '/users/my@email.de/calendar/events/'.$outlook_id)
  ->attachBody($newEvent)
  ->setReturnType(Model\Event::class)
  ->execute();

$outlook_id=$response->getId();
```

but this just changed the wording of the fault message to :

`Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `PATCH https://graph.microsoft.com/v1.0/users/my@email.de/calendar/events` resulted in a `405 Method Not Allowed` response: {"error":{"code":"ErrorInvalidRequest","message":"The OData request is not supported."}}`


Also google doesnt know an example ;-(
PHP is not really documented well from microsoft side.

Best wishes
Daniel

**Comment by Ndiritu** [comment]
@basementmedia2 for patch requests you change the request method in `createRequest()` as you have done above.

Looking at the Client error you've shared, the PATCH request URL doesn't contain the event Id. Confirm the contents of `$outlook_id` are correct.

**Comment by basementmedia2** [comment]
Hi,

sorry, this is embarrassing ;-(
I had of course forgotten the ID as a parameter. 
Now it works. 

Best thanks for your help and have a nice day to yo

**Comment by Ndiritu** [comment]
No worries.
