### ISSUE TITLE
How to get the Sensitivity of an event

### ISSUE THREAD

**Issue by basementmedia2** [microsoftgraph/msgraph-sdk-php#806]
Hi,

with the following code i get the sensitivity of all events for a given date range:

<?php

// Require our 3rd party libraries such as Oauth2
require_once __DIR__ . '/vendor/autoload.php';

// Include the Microsoft Graph classes
use Microsoft\Graph\Graph;
use Microsoft\Graph\Model;
$tenantId="myID";
$clientId="myID";
$clientSecret="myID";

$guzzle = new \GuzzleHttp\Client();
$url = 'https://login.microsoftonline.com/' . $tenantId . '/oauth2/token?api-version=1.0';
$token = json_decode($guzzle->post($url, [
    'form_params' => [
        'client_id' => $clientId,
        'client_secret' => $clientSecret,
        'resource' => 'https://graph.microsoft.com/',
        'grant_type' => 'client_credentials',
    ],
])->getBody()->getContents());

$accessToken = $token->access_token;
$graph = new Graph();
$graph->setAccessToken($accessToken);

$datum="2022-03-02";
$datum_start=$datum."T00:00:00";
$datum_end=$datum."T23:59:00";

$termine = $graph->createRequest("GET", "/users/myemail@somedomain.de/calendarView?startdatetime=".$datum_start."&enddatetime=".$datum_end)
->addHeaders(array(
    'Prefer'        => 'outlook.timezone="W. Europe Standard Time"'
))
->setReturnType(Model\Event::class)
->execute();
   
$termine_outlook[] = new stdClass;
$i=0;
foreach ($termine as $termin) {
    $sensitivity=$termin->getSensitivity();
    print_r($sensitivity); Works!
    echo "<hr>";
}
?>

But how can i get the String value (e.g. "private").
My try was 

$string=$sensitivity->getValue(); // Does not work
$string=$sensitivity->value; // Does not work.

Can you help me once again with this beginner question ?

Best wishes
Daniel

**Comment by SilasKenneth** [comment]
Hi @basementmedia2,
Thanks for taking your time to try the SDK. To get the value try.
```php
$string=$sensitivity->value();
```
instead of 
```php 
$string=$sensitivity->value;
 ```
 ___
Regards
Kenneth.

**Comment by basementmedia2** [comment]
Hi Kenneth,

works perfectly, thank you ;-)

Best wishes and a nice day/week
Daniel
