### ISSUE TITLE
Downloading the contents of a DriveItem

### ISSUE THREAD

**Issue by jayant1993** [microsoftgraph/msgraph-sdk-php#82]
As per the documentation we can download the file using `->download('C:/item.pdf');` but I want the public url or contents or the file like blob. 
Can I get any suggestion?
Thanks

**Comment by MIchaelMainer** [comment]
Thank you for your question about the Microsoft Graph. Please post your questions to StackOverflow with the microsoftgraph tag. After you've posted your question on StackOverflow, please provide a link here back to your post. That way, the question will be found by more people -- plus it gives back to the dev community on StackOverflow. 

Make sure you include the following information in your post on StackOverflow:
* What you've tried, your repro steps
* A trace of both the request and response
* Any error messages
* Any settings
