### ISSUE TITLE
Use of undefined constant CURL_VERSION_HTTP2 in vendor/microsoft/microsoft-graph/src/Http/GraphRequest.php on line 548

### ISSUE THREAD

**Issue by galiganu** [microsoftgraph/msgraph-sdk-php#827]
Hi 

I get "Use of undefined constant CURL_VERSION_HTTP2 in vendor/microsoft/microsoft-graph/src/Http/GraphRequest.php on line 548" with version 1.57.0 (PHP v7.4.28, cURL v7.29.0).

Thanks
galiganu

**Comment by galiganu** [comment]
I see on php manual php.net/manual/en/curl.constants.php this:
CURL_VERSION_HTTP2 (int) HTTP2 support built-in. Available since cURL 7.33.0

**Comment by Ndiritu** [comment]
Thanks for raising this @galiganu & sorry for the inconvenience caused. Should be releasing a patch later today
