### ISSUE TITLE
Installing SDK Issue

### ISSUE THREAD

**Issue by edsonromerop** [microsoftgraph/msgraph-sdk-php#83]
Hi, I have this problem installing the SDK using composer:

_[InvalidArgumentException]
  Could not find a version of package tangent-solutions/powerbi-sdk matching your minimum-stability (stable). Require
   it with an explicit version constraint allowing its desired stability._

What can I do to resolve this?

Thank you!

**Comment by MIchaelMainer** [comment]
This is the Microsoft Graph client library, not tangent-solutions/powerbi-sdk. I'm sure the maintainers of that client would be more helpful.

**Comment by edsonromerop** [comment]
Thank you, my mistake, this is my first issue posted on GitHub.
