### ISSUE TITLE
The specified object was not found in the store when updating photo

### ISSUE THREAD

**Issue by ricardomartos** [microsoftgraph/msgraph-sdk-php#84]
Hello.

I'm trying to update a signed user profile photo with the Laravel PHP Microsoft package, but im getting this error again and again:
```html
`Client error: `PUT https://graph.microsoft.com/v1.0/me/photo/$value` resulted in a `404 Not Found` response:\n
{\r\n
  "error": {\r\n
    "code": "ErrorItemNotFound",\r\n
    "message": "The specified object was not found in the store., No  (truncated...)\n`
```

This is my code:

```php
public function updatePhoto($photo){
        $image = Image::make($photo);
        $image->encode('png');
        $tokenCache = new \App\TokenStore\TokenCache;
        $graph = new Graph();
        $graph->setAccessToken($tokenCache->getAccessToken());
        $update = $graph->createRequest("PUT", "/me/photo/\$value")
             ->addHeaders(array("Content-Type" => "image/png"))
             ->attachBody($image)
             ->execute();
    }
```

The documentation is very general and I don't know what I'm doing wrong.

**Comment by MIchaelMainer** [comment]
Thank you for reporting this issue. I don't think this is a client library issue.

Are you able to request the user's photo?
Are you using an organization, education, or Microsoft (outlook.com, hotmail.com, etc) account? 

Microsoft accounts are not supported with the update API.

**Comment by MIchaelMainer** [comment]
Close due to no response. If this is in error, please reopen and respond to the latest questions

**Comment by Ranjeet4android** [comment]
{
    "error": {
        "code": "ErrorItemNotFound",
        "message": "The specified object was not found in the store.",
        "innerError": {
            "request-id": "c74e057f-cb21-4d78-b6e2-63bd1a7e0cb1",
            "date": "2020-04-23T11:10:08"
        }
    }
}
