### ISSUE TITLE
Wrong folder name src/Beta/Microsoft/Graph/SecurityNamespace ... PSR-4 autoloading notice

### ISSUE THREAD

**Issue by profa2000** [microsoftgraph/msgraph-sdk-php#842]
Hi guys,
In version 1.53.0 you added new folder named **SecurityNamespace** to src/Beta/Microsoft/Graph/.
All classes in this folder have **namespace Beta\Microsoft\Graph\Security\Model**,
As you can see, in the namespace **Security** is used but folder is **SecurityNamespace**. I believe that you accidentally gave the wrong name to the folder.
This mistake causes the composer notices about PSR-4 autoloading.
This is the list of notices I get. Note, I am using still composer 1.10.25 and it says that those classes will not be loaded anymore in composer v2.
`
Deprecation Notice: Class Beta\Microsoft\Graph\Security\Model\AddContentFooterAction located in ./vendor/microsoft/microsoft-graph/src/Beta/Microsoft/Graph/SecurityNamespace/Model/AddContentFooterAction.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Beta\Microsoft\Graph\Security\Model\VerificationResult located in ./vendor/microsoft/microsoft-graph/src/Beta/Microsoft/Graph/SecurityNamespace/Model/VerificationResult.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Beta\Microsoft\Graph\Security\Model\InformationProtectionAction located in ./vendor/microsoft/microsoft-graph/src/Beta/Microsoft/Graph/SecurityNamespace/Model/InformationProtectionAction.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Beta\Microsoft\Graph\Security\Model\BufferDecryptionResult located in ./vendor/microsoft/microsoft-graph/src/Beta/Microsoft/Graph/SecurityNamespace/Model/BufferDecryptionResult.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Beta\Microsoft\Graph\Security\Model\ContentState located in ./vendor/microsoft/microsoft-graph/src/Beta/Microsoft/Graph/SecurityNamespace/Model/ContentState.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Beta\Microsoft\Graph\Security\Model\ContentAlignment located in ./vendor/microsoft/microsoft-graph/src/Beta/Microsoft/Graph/SecurityNamespace/Model/ContentAlignment.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Beta\Microsoft\Graph\Security\Model\SensitivityLabel located in ./vendor/microsoft/microsoft-graph/src/Beta/Microsoft/Graph/SecurityNamespace/Model/SensitivityLabel.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Beta\Microsoft\Graph\Security\Model\AssignmentMethod located in ./vendor/microsoft/microsoft-graph/src/Beta/Microsoft/Graph/SecurityNamespace/Model/AssignmentMethod.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Beta\Microsoft\Graph\Security\Model\RemoveContentFooterAction located in ./vendor/microsoft/microsoft-graph/src/Beta/Microsoft/Graph/SecurityNamespace/Model/RemoveContentFooterAction.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Beta\Microsoft\Graph\Security\Model\ContentInfo located in ./vendor/microsoft/microsoft-graph/src/Beta/Microsoft/Graph/SecurityNamespace/Model/ContentInfo.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Beta\Microsoft\Graph\Security\Model\BufferEncryptionResult located in ./vendor/microsoft/microsoft-graph/src/Beta/Microsoft/Graph/SecurityNamespace/Model/BufferEncryptionResult.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Beta\Microsoft\Graph\Security\Model\ClassificationResult located in ./vendor/microsoft/microsoft-graph/src/Beta/Microsoft/Graph/SecurityNamespace/Model/ClassificationResult.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Beta\Microsoft\Graph\Security\Model\AddContentHeaderAction located in ./vendor/microsoft/microsoft-graph/src/Beta/Microsoft/Graph/SecurityNamespace/Model/AddContentHeaderAction.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Beta\Microsoft\Graph\Security\Model\ActionSource located in ./vendor/microsoft/microsoft-graph/src/Beta/Microsoft/Graph/SecurityNamespace/Model/ActionSource.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Beta\Microsoft\Graph\Security\Model\AddWatermarkAction located in ./vendor/microsoft/microsoft-graph/src/Beta/Microsoft/Graph/SecurityNamespace/Model/AddWatermarkAction.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Beta\Microsoft\Graph\Security\Model\LabelingOptions located in ./vendor/microsoft/microsoft-graph/src/Beta/Microsoft/Graph/SecurityNamespace/Model/LabelingOptions.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Beta\Microsoft\Graph\Security\Model\InformationProtection located in ./vendor/microsoft/microsoft-graph/src/Beta/Microsoft/Graph/SecurityNamespace/Model/InformationProtection.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Beta\Microsoft\Graph\Security\Model\KeyValuePair located in ./vendor/microsoft/microsoft-graph/src/Beta/Microsoft/Graph/SecurityNamespace/Model/KeyValuePair.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Beta\Microsoft\Graph\Security\Model\DowngradeJustification located in ./vendor/microsoft/microsoft-graph/src/Beta/Microsoft/Graph/SecurityNamespace/Model/DowngradeJustification.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Beta\Microsoft\Graph\Security\Model\RemoveWatermarkAction located in ./vendor/microsoft/microsoft-graph/src/Beta/Microsoft/Graph/SecurityNamespace/Model/RemoveWatermarkAction.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Beta\Microsoft\Graph\Security\Model\JustifyAction located in ./vendor/microsoft/microsoft-graph/src/Beta/Microsoft/Graph/SecurityNamespace/Model/JustifyAction.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Beta\Microsoft\Graph\Security\Model\RemoveProtectionAction located in ./vendor/microsoft/microsoft-graph/src/Beta/Microsoft/Graph/SecurityNamespace/Model/RemoveProtectionAction.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Beta\Microsoft\Graph\Security\Model\MetadataAction located in ./vendor/microsoft/microsoft-graph/src/Beta/Microsoft/Graph/SecurityNamespace/Model/MetadataAction.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Beta\Microsoft\Graph\Security\Model\ProtectDoNotForwardAction located in ./vendor/microsoft/microsoft-graph/src/Beta/Microsoft/Graph/SecurityNamespace/Model/ProtectDoNotForwardAction.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Beta\Microsoft\Graph\Security\Model\RecommendLabelAction located in ./vendor/microsoft/microsoft-graph/src/Beta/Microsoft/Graph/SecurityNamespace/Model/RecommendLabelAction.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Beta\Microsoft\Graph\Security\Model\CustomAction located in ./vendor/microsoft/microsoft-graph/src/Beta/Microsoft/Graph/SecurityNamespace/Model/CustomAction.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Beta\Microsoft\Graph\Security\Model\Security located in ./vendor/microsoft/microsoft-graph/src/Beta/Microsoft/Graph/SecurityNamespace/Model/Security.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Beta\Microsoft\Graph\Security\Model\ContentLabel located in ./vendor/microsoft/microsoft-graph/src/Beta/Microsoft/Graph/SecurityNamespace/Model/ContentLabel.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Beta\Microsoft\Graph\Security\Model\ApplyLabelAction located in ./vendor/microsoft/microsoft-graph/src/Beta/Microsoft/Graph/SecurityNamespace/Model/ApplyLabelAction.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Beta\Microsoft\Graph\Security\Model\RemoveContentHeaderAction located in ./vendor/microsoft/microsoft-graph/src/Beta/Microsoft/Graph/SecurityNamespace/Model/RemoveContentHeaderAction.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Beta\Microsoft\Graph\Security\Model\SigningResult located in ./vendor/microsoft/microsoft-graph/src/Beta/Microsoft/Graph/SecurityNamespace/Model/SigningResult.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Beta\Microsoft\Graph\Security\Model\ProtectAdhocAction located in ./vendor/microsoft/microsoft-graph/src/Beta/Microsoft/Graph/SecurityNamespace/Model/ProtectAdhocAction.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Beta\Microsoft\Graph\Security\Model\InformationProtectionPolicySetting located in ./vendor/microsoft/microsoft-graph/src/Beta/Microsoft/Graph/SecurityNamespace/Model/InformationProtectionPolicySetting.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Beta\Microsoft\Graph\Security\Model\ProtectByTemplateAction located in ./vendor/microsoft/microsoft-graph/src/Beta/Microsoft/Graph/SecurityNamespace/Model/ProtectByTemplateAction.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Beta\Microsoft\Graph\Security\Model\WatermarkLayout located in ./vendor/microsoft/microsoft-graph/src/Beta/Microsoft/Graph/SecurityNamespace/Model/WatermarkLayout.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
`

**Comment by Ndiritu** [comment]
Thanks for creating this @profa2000 
Closing as it's related to #791
