### ISSUE TITLE
How to get lastModifiedDateTime in West European Time?

### ISSUE THREAD

**Issue by basementmedia2** [microsoftgraph/msgraph-sdk-php#859]
Hi,

although i add timezone headers for Western European Time i get UTC-Time for lastModifiedDateTime:

```
$datum="2022-04-13";
$datum_start=$datum."T00:00:00";
$datum_end=$datum."T23:59:00";

$termine = $graph->createRequest("GET", "/users/my@email.de/calendarView?startdatetime=".$datum_start."&enddatetime=".$datum_end)
->addHeaders(array(
    'Prefer'        => 'outlook.timezone="W. Europe Standard Time"'
))
->setReturnType(Model\Event::class)
->execute();
   
$termine_outlook[] = new stdClass;

foreach ($termine as $termin) {
    $lastEdit=$termin->getLastModifiedDateTime()->format('Y-m-d H-i-s');
    echo$lastEdit;
}
```

Do you have an idea whats the reason?

Best wishes
Daniel

**Comment by Ndiritu** [comment]
Interesting issue.

From the [docs](https://docs.microsoft.com/en-us/graph/api/calendar-list-calendarview?view=graph-rest-1.0&tabs=http#request-headers) only the `start` and `end` properties of the event will be returned in the preferred timezone.

Not exactly sure but looking at the event property types, `lastModifiedDateTime` is of type `DateTimeOffset` which by definition is always represented in UTC, while `start` and `end` are of a custom Graph type `DateTimeTimeZone` which allows more flexibility.

Looks like you'd have to convert from UTC manually

**Comment by basementmedia2** [comment]
Thank  you. Ok i will manually convert.

Best regards
Daniel
