### ISSUE TITLE
An error occurred in the data store when I list versions of a driveItem

### ISSUE THREAD

**Issue by landall** [microsoftgraph/msgraph-sdk-php#863]
{"error":{"code":"generalException","message":"An error occurred in the data store.","innerError":{"date":"2022-04-17T19:00:29","request-id":"2a98a91a-e595-485d-8da1-f30fc72bc2c9","client-request-id":"2a98a91a-e595-485d-8da1-f30fc72bc2c9"}}}

I can see the versions list in Windows Explorer.

Why does this happen and what should I do now?

**Comment by Ndiritu** [comment]
Hi @landall 
This appears to be an issue with the service. This repository is specific to the PHP client library. Questions about the service API or configuration should be posted to Microsoft Q&A and tagged with one of [microsoft-graph-*](https://docs.microsoft.com/en-us/answers/search.html?c=&includeChildren=&f=&type=question+OR+idea+OR+kbentry+OR+answer+OR+topic+OR+user&redirect=search%2Fsearch&sort=relevance&q=microsoft-graph-*) tags.
