### ISSUE TITLE
Bump minimum supported PHP version

### ISSUE THREAD

**Issue by Ndiritu** [microsoftgraph/msgraph-sdk-php#867]
We're currently supporting PHP 7.3 in the v1 SDK which is no longer receiving active/security support.

https://www.php.net/supported-versions.php

We should at least bump up to PHP 7.4 which is no longer in active support but at least should receive security updates until Nov '22.

**Comment by isvargasmsft** [comment]
Let's keep up with the language. Even if we don't have to, I'd prefer to avoid any issues caused by unsupported versions of the language. @shemogumbe what do you think?

**Comment by Ndiritu** [comment]
duplicate of https://github.com/microsoft/kiota/issues/1526
