### ISSUE TITLE
in the phpdoc for Contact, the types of array valued fields are specified as singletons

### ISSUE THREAD

**Issue by chilipepper987** [microsoftgraph/msgraph-sdk-php#87]
ex,
```
   /** 
    * Sets the emailAddresses
    * The contact's email addresses.
    *
    * @param EmailAddress $val The emailAddresses
    *
    * @return Contact
    */
    public function setEmailAddresses($val)
    {
	$this->_propDict["emailAddresses"] = $val;
        return $this;
    }
```

should have
`    * @param EmailAddress[] $val The emailAddresses`
so the ide knows its an array. Currently the API fails if you pass it a single EmailAddress (expected), and then the IDE yells at you when you correctly pass it an array (annoying), not just annoying but also I'm relying on the phpdoc to tell me the correct format of the parameter to this method, and its telling me the wrong thing, which is a problem. Also applies to `setImAddresses`, `setHomePhones`, `setBusinessPhones`, `setChildren`,
 
[AB#7590](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7590)

**Comment by deepak2016** [comment]
834678
Thank for reporting the issue. We will pick this one as soon as possible

**Comment by Ndiritu** [comment]
This is fixed in the v2 preview release https://github.com/microsoftgraph/msgraph-sdk-php/issues/681
