### ISSUE TITLE
Get profile photo contents

### ISSUE THREAD

**Issue by jbrooksuk** [microsoftgraph/msgraph-sdk-php#88]
Any time I request the `/me/photo/$value` resource, the client returns an empty array `[]`. Am I doing something wrong?

**Comment by jbrooksuk** [comment]
I've figured it out. You need to use the `download` method instead of `execute`.

**Comment by PatchworkBoy** [comment]
Depends what you're trying to accomplish...

**Comment by jbrooksuk** [comment]
Ah-ha! `getRawBody` was what I was after in the end. Thanks.

**Comment by Jugurtha13** [comment]
> $photo = $photo->getRawBody();

2 days I've been looking for... thank you for your help

**Comment by jordm** [comment]
> $photo = $photo->getRawBody();

The size of the Stream from this line comes back as null for me (response 200). I'm also using endpoint "/users/{id}/photo/\$value".

I can confirm a avatar exists for the user id, any ideas?

**Comment by MIchaelMainer** [comment]
@jordm  Are you using the v1.0 or beta endpoint? Do you experience this issue on both of those endpoints?

**Comment by jordm** [comment]
@MIchaelMainer Yes, both endpoints give response below:

![image](https://user-images.githubusercontent.com/33763959/123994745-a832ec80-d99b-11eb-99de-1cb355c71b3f.png)

**Comment by MIchaelMainer** [comment]
@jordm Please confirm that if you use [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer), that this user doesn't return a photo. If Graph Explorer returns a photo, please open a new issue, and link to this issue. Make sure you provide repro steps.
