### ISSUE TITLE
Inconsistency between camel case and snake case in getters and setters

### ISSUE THREAD

**Issue by fyem** [microsoftgraph/msgraph-sdk-php#9]
In some of the models the getters use camel case for the property array but the setters use snake case. One of the examples would be the DateTimeTimeZone Model. This does not create any issues when fetching data but leads to problems when trying to create these objects to attach them to requests.

**Comment by cbales** [comment]
Yeah that's a pretty bad user experience. These are all generated by another project, so I'll make changes there and then commit the updated models back.

**Comment by cbales** [comment]
This will go out with the next major release of the library
