### ISSUE TITLE
Issues installing in Laravel via composer

### ISSUE THREAD

**Issue by s2925534** [microsoftgraph/msgraph-sdk-php#90]
When I try to install in my project I get this. I have try everything but nothing works. Thanks,

Can you please explain this:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package tangent-solutions/powerbi-sdk could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

**Comment by PatchworkBoy** [comment]
This isn't a dependency of the graph-sdk... nor any of the graph-sdk's dependencies. The problem therefore is not with the graph-sdk

```
# composer require microsoft/microsoft-graph
Using version ^1.3 for microsoft/microsoft-graph
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 5 installs, 0 updates, 0 removals
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.4.2): Loading from cache
  - Installing guzzlehttp/guzzle (6.3.3): Loading from cache
  - Installing microsoft/microsoft-graph (1.3.1): Downloading (100%)         
guzzlehttp/guzzle suggests installing psr/log (Required for using the Log middleware)
Writing lock file
Generating autoload files
#
```

**Comment by MIchaelMainer** [comment]
@PatchworkBoy Thank you for addressing this and providing some guidance. I'm closing this issue.
