### ISSUE TITLE
Breaking change in 1.66.0 (added return type on overridable method jsonSerialize)

### ISSUE THREAD

**Issue by guilliamxavier** [microsoftgraph/msgraph-sdk-php#919]
Updating from <=1.65.0 [really 1.64.0] to >=1.66.0 [really 1.69.0] (automatically by a `composer update`) broke our app. Relevant part:

```php
class FilteredEntity extends Microsoft\Graph\Model\Entity
{
    /* ... */

    public function jsonSerialize()
    {
        /* ... */
    }
}
```

now causes a PHP Fatal error:
> Declaration of FilteredEntity::jsonSerialize() must be compatible with Microsoft\Graph\Model\Entity::jsonSerialize(): array

Tracked down to #899 (actually https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/759)

I understand the desire to avoid the deprecation notice introduced in PHP 8.1 (and a future error in PHP 9), but sorry, that's a [non-documented] **breaking change** in a *non-major* release! Please compare:
- with 1.65.0: https://3v4l.org/TgIRr
- with 1.66.0: https://3v4l.org/LuoZu

To support both PHP 7.3+ and 8.0+ (without BC break), [I think] that change should be reverted, and do this instead:

```diff
+    #[\ReturnTypeWillChange]
     public function jsonSerialize()
```

(result: https://3v4l.org/B152Q),
and re-do the real change in a future version (major, or possibly minor but bumping php dependency to ^8.1).

**Comment by Ndiritu** [comment]
Thanks for reporting this @guilliamxavier and apologies for the breaking change. Didn't anticipate an override scenario when determining backward compatibility.

Will push the patch this week.
