### ISSUE TITLE
Current issues with snippet generation

### ISSUE THREAD

**Issue by SilasKenneth** [microsoftgraph/msgraph-sdk-php#927]
Current Snippets with issues.
- [Issue 1](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/includes/snippets/php/create-directoryobject-from-device-2-php-snippets.md)
- [Issue 2](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/includes/snippets/php/create-homerealmdiscoverypolicy-from-homerealmdiscoverypolicies-php-snippets.md)
      
     - [ ] Missing body when body should be there. [Post Home Realm](https://docs.microsoft.com/en-us/graph/api/homerealmdiscoverypolicy-post-homerealmdiscoverypolicies?view=graph-rest-1.0&tabs=http#request)
- [Issue 3](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/includes/snippets/php/create-list-php-snippets.md)

     - [x] PHP Reserved words are never escaped when referring to classes. e.g `new List()` should be `new EscapedList()`.
- [Issue 4](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/includes/snippets/php/create-unifiedroleassignmentmultiple-from-rbacapplication-cloudpc-php-snippets.md)
     - [x] Array parameters are never correctly handled.
---
#### Wrongly handled types
 - [Case 1 - Duration](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/includes/snippets/php/create-privilegedapproval-from-privilegedapproval-php-snippets.md)
---

#### Worth Including in tests.

- [ ] [Test How request body class name is decided](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/includes/snippets/php/create-or-get-onlinemeeting-1-php-snippets.md)

**Comment by baywet** [comment]
@SilasKenneth is this still relevant? should we close it?

**Comment by afriadishariff-lab** [comment]
> Current Snippets with issues.
> - [Issue 1](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/includes/snippets/php/create-directoryobject-from-device-2-php-snippets.md)
> - [Issue 2](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/includes/snippets/php/create-homerealmdiscoverypolicy-from-homerealmdiscoverypolicies-php-snippets.md)
>       
>      - [ ] Missing body when body should be there. [Post Home Realm](https://docs.microsoft.com/en-us/graph/api/homerealmdiscoverypolicy-post-homerealmdiscoverypolicies?view=graph-rest-1.0&tabs=http#request)
> - [Issue 3](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/includes/snippets/php/create-list-php-snippets.md)
> 
>      - [x] PHP Reserved words are never escaped when referring to classes. e.g `new List()` should be `new EscapedList()`.
> - [Issue 4](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/includes/snippets/php/create-unifiedroleassignmentmultiple-from-rbacapplication-cloudpc-php-snippets.md)
>      - [x] Array parameters are never correctly handled.
> ---
> #### Wrongly handled types
>  - [Case 1 - Duration](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/includes/snippets/php/create-privilegedapproval-from-privilegedapproval-php-snippets.md)
> ---
> 
> #### Worth Including in tests.
> 
> - [ ] [Test How request body class name is decided](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/includes/snippets/php/create-or-get-onlinemeeting-1-php-snippets.md)

Translate
