### ISSUE TITLE
Batch request

### ISSUE THREAD

**Issue by JValck** [microsoftgraph/msgraph-sdk-php#93]
How does one execute a batch request with the currently provided library?
The docs don't give any example.

**Comment by MIchaelMainer** [comment]
We don't have a batch helper so you'll need to form the request body yourself.  Use the information here for more information on how to 
https://developer.microsoft.com/en-us/graph/docs/concepts/json_batching

```
$batchBody = // TODO an array of batch requests

$graph->createRequest("POST", "/$batch")
       	  ->attachBody($batchBody)
	  ->execute();
```

**Comment by Herz3h** [comment]
Sorry to reopen this, but I'm trying to achieve the same thing. 

Is there a way to get the JSON that would be sent for a single request with php sdk so that I could create my batch array with it ?

**Comment by Herz3h** [comment]
Never mind, I simply do this : 

```
$batchRequest['requets'][] = [
'id' => $id, // Generate random id here, to identify request's reponse later when the server answers
'method' => 'POST',
'url' => "me/calendars/$calendarId/events", // Change this as needed
'body' => $event->jsonSerialize();
]
json_encode($batchRequest, JSON_UNESCAPED_SLASHES);
```
