### ISSUE TITLE
2.0.0-RC5 Announcement | Known Issues

### ISSUE THREAD

**Issue by Ndiritu** [microsoftgraph/msgraph-sdk-php#943]
This release contains model bug fixes and the following improvements:
- Authentication Provider that handles token fetching and refresh behind the scenes for you:
```php

use Microsoft\Kiota\Authentication\Oauth\AuthorizationCodeContext;
use Microsoft\Kiota\Authentication\PhpLeagueAuthenticationProvider;

$tokenRequestContext = new AuthorizationCodeContext(
    'tenantId',
    'clientId',
    'clientSecret',
    'authCode',
    'redirectUri'
);
$scopes = ['User.Read', 'Mail.Read'];
$authProvider = new PhpLeagueAuthenticationProvider($tokenRequestContext, $scopes);
```

- A fluent API design:
```php
$messages = $graphServiceClient->usersById(USER_ID)->messages()->get()->wait();
```

More details in the [Upgrade Guide](https://aka.ms/graph/sdk/php/preview/upgrade) and [README](https://aka.ms/graph/sdk/php/preview/readme)

Please try out this version and let us know what you think:
```shell
{
    "require": {
        "microsoft/microsoft-graph": "^2.0.0-RC5",
        "microsoft/microsoft-graph-core": "@RC"
    }
}
```

This version was generated using a new OpenAPI-based SDK generator called [Kiota](https://microsoft.github.io/kiota/).

## Known Issues
- [ ] #912 . To get the response payload please use the [`NativeResponseHandler`](https://github.com/microsoftgraph/msgraph-sdk-php/blob/feat/kiota-preview/docs/Examples.md#get-the-raw-response)
- [x] #939
- [x] #979 

@MIchaelMainer,@Zombaya,@tdondich,@baywet,@SilasKenneth,@nokafor,@Dillonsmart,@anvanza,@dan-silver,@noahheck,@curry684,@guilliamxavier,@landall,@andrii-boiko,@Levure,@tolbon,@Jelle-S,@osalabs,@zengin,@ronnyjss, @fabianderijk, @alex-code, @craigpaul, @minhvn, @katalin2003, @basementmedia2, @ianef, @Deadpikle, @N-M, @Dakoni4400, 
@isvargasmsft

**Comment by guilliamxavier** [comment]
You might want to re-do https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/759 (i.e. revert https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/772) in the 2.0 dev branch (before the 2.0.0 release) and add it to the breaking changes (like https://github.com/microsoftgraph/msgraph-sdk-php/pull/658 which BTW should also mention that parameter/return type declarations have been added to all methods)

**Comment by Ndiritu** [comment]
Moving forward, 2.0 will not be using `jsonSerialize()` and thanks, will added the parameter/return type declarations changes to the Upgrade guide

**Comment by Ndiritu** [comment]
As of [2.0.0-RC9](https://github.com/microsoftgraph/msgraph-sdk-php/releases/tag/2.0.0-RC9), PATCH requests return the deserialized response body

**Comment by Ndiritu** [comment]
2.0.0 is out now. https://devblogs.microsoft.com/microsoft365dev/write-high-quality-code-with-the-microsoft-graph-php-sdk-v2/
