### ISSUE TITLE
Obsolete $request in constructor?

### ISSUE THREAD

**Issue by JValck** [microsoftgraph/msgraph-sdk-php#95]
What's the purpose of the `$request` parameter in the [constructor of the `GraphResponse`](https://github.com/microsoftgraph/msgraph-sdk-php/blob/dev/src/Http/GraphResponse.php#L67)?
The request isn't used in the other class methods.

**Comment by MIchaelMainer** [comment]
Good question. It was added in the initial commit. You are correct, it is not used. I don't know what was the intention. We'll have to leave it in as it would be a breaking change. I was thinking that we could overload the constructor, alas, [PHP doesn't allow](https://stackoverflow.com/questions/2169448/why-cant-i-overload-constructors-in-php) that. 

https://o365exchange.visualstudio.com/O365%20Core/_workitems/edit/856717
