### ISSUE TITLE
Improve request configuration pattern

### ISSUE THREAD

**Issue by Ndiritu** [microsoftgraph/msgraph-sdk-php#952]
_Challenge_: It can be difficult to know which request configuration object and query parameter object to import. It also doesn't feel as fluent to type.

_Developer realises that they can configure the GET request_
![image](https://user-images.githubusercontent.com/10958912/179890728-e4bac017-22ef-4ebf-9e77-4a13657f6588.png)

_Developer creates config object but has to figure out which object to import_
![image](https://user-images.githubusercontent.com/10958912/179890956-df2d5c7a-fc4b-4151-bdd5-b22d2419ed13.png)

_Developer goes through the same when creating the query parameter object_
![image](https://user-images.githubusercontent.com/10958912/179892842-732ab4b9-8a01-4c0c-a493-0ed14aca3770.png)

_Final code_
![image](https://user-images.githubusercontent.com/10958912/179893021-e6e3a82c-e107-4a77-b5e7-0bc9e305d202.png)

In v1, the developer would add query parameters to the URL directly and pass headers:
```php
$response = $graphClient->createRequest('GET', '/users/user-id/messages?$select=subject,body&$top=10')
                                          ->addHeaders(['Prefer' => 'outlook.body-content-type=text'])
                                          ->execute();

```
Perhaps our initial Kiota design would be more fluent?
```php

$response = $graphServiceClient->usersById('user-id')->messages()->select(['subject', 'body'])->top(10)->get(['Prefer' => 'outlook.body-content-type=text']);

```

**Comment by isvargasmsft** [comment]
Awesome, thank you very much for this explanation Philip.

**Comment by sebastienlevert** [comment]
The experience is very similar to what we had with JavaScript / TypeScript. Here are my thoughts : 

- This is not an enjoyable experience for developers. It's confusing and honestly, unnecessary.
- I understand that each "*GetRequestConfiguration" is "unique" as it adds the features of Graph (support of select, top, etc. based on the underlying endpoint and the OpenAPI description). It explains it, but I don't think it justifies this complexity.
- The fluent style approach is great and simplifies the discoverability / usage of the API. Just the config object makes it very cluttered.

My thoughts (with my limited knowledge of PHP) would lead to use an anonymous object. Can we do something like this in PHP?

```php
$response = $graphServiceClient->usersById('user-id')->messages()->get({
	'queryParameters' => {
		'top' => 2,
	    'select' => ['subject', 'body']
	},
	'headers' => [
		'Prefer' => 'outlook.body-content-type=text'
	]
});
```

Very pseudo-code-y, but is there a way we can use this structure? This would remove the need to explicitly import. Thoughts?

**Comment by 36864** [comment]
> My thoughts (with my limited knowledge of PHP) would lead to use an anonymous object. Can we do something like this in PHP?

In PHP you'd probably use associative arrays for this. Pretty much the same syntax you described, except with square brackets instead of curly brackets.

There is another pattern that I see often in which the developer passes a callable as a parameter to a function, and that callable receives the appropriate configuration object. Something like the following:
```php
$response = $graphServiceClient->usersById('user-id')->messages()->get(function($config) {
    $config->top = 2;
    $config->select = ['subject', 'body'];
    $config->headers = [ 'Prefer' => 'outlook.body-content-type=text'];
});
```
These approaches don't have to be mutually exclusive. There's no concept of "overloading" in PHP, but it can be emulated by inspecting the types of received arguments.

**Comment by Ndiritu** [comment]
Thanks for the feedback & suggestions @36864. Will work on this early next month.

**Comment by Ndiritu** [comment]
@baywet @isvargasmsft @shemogumbe @SilasKenneth any thoughts?

**Comment by baywet** [comment]
Kiota doesn't have any prescriptive style for the request configuration parameters:
- Dotnet uses [a callback with optional parameters](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/ca242c237f27c1af73bb9b8d64241239c68313a3/src/Microsoft.Graph/Generated/Users/UsersRequestBuilder.cs#L129).
- Java uses [callback parameters with overloads](https://github.com/microsoftgraph/msgraph-sdk-java/blob/0fd0d55c5843acdd2db6628a50481b5062c2f556/src/main/java/com/microsoft/graph/users/UsersRequestBuilder.java#L173)
- Go uses [simple parameters without overloads](https://github.com/microsoftgraph/msgraph-sdk-go/blob/4ee316d57cd51c159232b778bf82a6e678e44095/users/users_request_builder.go#L125).
- JS/TS has ongoing work to figure out the best combo (probably optional parameters, with JSON notation for the request body).

If PHP wants to use a callback for the request configuration (options, query parameters, headers), go for it (that's a decision for Isaac to make as a PM). Keep in mind two things:
- The parameters format should be the same across the experience (executor methods, generator methods, batching...)
- We'll want to choose a single parameters experience to avoid duplicating efforts on our end for now.

**Comment by Ndiritu** [comment]
PHPDoc doesn't have a way to define the "shape" of an array. However, static analysis tools (PHPStan, Psalm) and PHPStorm (Jetbrains paid PHP IDE) seem to have agreed on a standard for this:

```php
/**
 * @param array{headers: array<string, string>, top: int, count: true, requestOptions: array<string, RequestOption>} $config
 */
function post(array $config) {}
```

(Auto-completion experience on PHPStorm)
![image](https://user-images.githubusercontent.com/10958912/205001432-61365291-b99a-46e2-a842-f1a104a1caa0.png)


VsCode doesn't have native auto-completion support & the most popular auto-completion extension[(Intelephense)](https://github.com/bmewburn/vscode-intelephense/issues/249) are yet to implement this.

I'd argue that we could still use arrays since it's a common config pattern in PHP e.g. [Guzzle client](https://github.com/guzzle/guzzle/blob/master/src/Client.php#L26). 

Developers without auto-completion support from PHPStorm can rely on static analysis tools to catch errors before runtime.

Also, should we nest the query parameters under a `queryParameters` key or not?

**Comment by baywet** [comment]
Thanks for doing the investigation work.

Do we have publicly available data that states what IDEs PHP devs are generally using? (back in my days it was notepad++ with a few plugins, but hopefully that's not the case anymore 😉 )
(I just want to make sure we're not making a decision that's going to alienate a big percentage of our audience)

> Also, should we nest the query parameters under a queryParameters key or not?

Yes, it's only a matter of time before somebody has a query parameter named headers or options and everything goes off the rails.

**Comment by Ndiritu** [comment]
Couldn't find any data other than [JetBrains' report](https://www.jetbrains.com/lp/devecosystem-2021/php/#PHP_which-editor-ide-do-you-mostly-use-for-php-development) which is biased. I would guess VS Code has a strong user base seeing that it comes second.

Thanks for clarifying on the query params key.

**Comment by baywet** [comment]
Thanks for sharing this. 1% are still using notepad++ 🤣
Another interesting aspect of this survey is the fact that the vast majority of developers are not using static analysis, so we can't bank on that either (c.f. your previous comment).

So, to recap, auto-completion story for PHP request configuration is poor at best right now. Switching to array + this specific format of PHP docs would make it better for some people (PHP storm, the few using static analysis tools, potentially vs code users assuming it gets implemented), but would it make it worse for others?

**Comment by Ndiritu** [comment]
Took a fresh look at this. I think an ideal experience should feel intuitive/fluid and reduce the chances of errors.

Using the array format (esp if you're not using PHPStorm) has poor auto-completion which may lead to typos when setting array keys. Devs can only discover these errors during runtime. Also, they'll have to reference the function docs to know which query params are enabled etc. 

### I'd recommend sticking to the request config classes because:
### 1. We could improve the request config class experience by adding constructors arguments and leveraging PHP 8's Named Arguments. 

This would prevent having to create the object before the executing the request e.g.
```php

$config = new MessagesRequestBuilderGetRequestConfiguration();
$config->queryParameters = new MessagesRequestBuilderGetQueryParameters();
$config->queryParameters->top = 10;

$messages = $client->usersById($userId)->messages()->get($config)->wait();
```

And allow us to initialise the object inline while leveraging PHP 8's [named arguments](https://www.php.net/manual/en/functions.arguments.php#functions.named-arguments)
```php

$messages = $graphServiceClient->usersById(USER_ID)->messages()->get(new MessagesRequestBuilderGetRequestConfiguration(
        queryParameters: new MessagesRequestBuilderGetQueryParameters(
            select: [],
            top: 10
        )
    ));
```


### 2. The auto-completion experience still requires a dev to figure out the right class to import BUT alerts the developer of an error immediately:

- _discovering you can configure the request_
![image](https://user-images.githubusercontent.com/10958912/213392862-2373007a-b540-46fb-8b29-455fcb3a7dd4.png)

- _importing the right request config class_ (Some pain)
![image](https://user-images.githubusercontent.com/10958912/213393233-6c8fd342-cb2c-4e5d-9aaf-f39f44c65101.png)

- _using named arguments to only set query parameters_
![image](https://user-images.githubusercontent.com/10958912/213393847-35b1723f-1129-40df-bf26-a5078c79dc5b.png)

- _importing the right query parameters class_ (Some pain)
![image](https://user-images.githubusercontent.com/10958912/213394204-702f681d-fe60-4674-83c1-9e8b888fc0b4.png)

- _setting query param values via named arguments leveraging autocompletion_
![image](https://user-images.githubusercontent.com/10958912/213394464-37149766-d332-4969-b5fd-3ad7d74ac479.png)

It may be worth noting that the suggested imports in PHPStorm are more accurate to the desired classes. Hopefully with time the PHP VsCode plugin is improved.

_PHPStorm auto-completion_
![image](https://user-images.githubusercontent.com/10958912/213396218-06806726-9a44-42c1-b790-9bf7d1194e4a.png)

**But in case the wrong class is imported, the developer is aware immediately:**
![image](https://user-images.githubusercontent.com/10958912/213400636-5c14c45a-3f13-418e-a882-9f1d5be61498.png)

**Comment by Ndiritu** [comment]
What do you think @baywet @SilasKenneth @isvargasmsft @shemogumbe ?

**Comment by SilasKenneth** [comment]
Hi @Ndiritu, thanks for providing the detailed approaches to getting a better request configuration experience. 
I feel confident having the constructors will help a lot with improving the developer experience, this should be very helpful for people using PHP < 8.0. Users with PHP >= 8 will have the added advantage of named arguments.

What do you think about having a method in the request config class that helps with creating a QueryParameters object for us so we don't have to know the right class for the query parameter or even import it? 
### Example
---
```php
$config = new MessagesRequestBuilderGetRequestConfiguration(
         options: [$option],
         headers: ['Header-Name' => 'HeaderValue'],
         queryParameters: MessagesRequestBuilderGetRequestConfiguration::newQueryParameters(
                   select: ['content', 'subject']
              )
         );
```

**Comment by Ndiritu** [comment]
@SilasKenneth I like that idea! Less room for errors.

**Comment by Ndiritu** [comment]
@baywet the constructors...
PHP 8 promotes constructor arguments to class properties. Ordinary constructors would still work
```php

class UsersRequestBuilderGetRequestConfiguration 
    {
        public function __construct(
            public ?array $headers = null,
            public ?array $options = null,
            public ?UsersRequestBuilderGetQueryParameters $queryParameters = null
        ) {
            $this->headers = $headers;
            $this->options = $options;
            $this->queryParameters = $queryParameters;
        }
    }
```

**Comment by baywet** [comment]
Thanks for sharing this. Do you need to assign the parameter to the property considering the parameter is an auto-property as far as I can tell? Would we even still need to declare the properties? (this would effectively mitigate some of the size increase but we should consider the impact on doc comments).

(so just this )

```PHP
class UsersRequestBuilderGetRequestConfiguration 
    {
        public function __construct(
            public ?array $headers = null,
            public ?array $options = null,
            public ?UsersRequestBuilderGetQueryParameters $queryParameters = null
        ) {
        }
    }
```

**Comment by Ndiritu** [comment]
You're right actually. No need to do the assignments. We wouldn't need to declare properties and doc comments would still be available as far as I know.

```php
/**
 * Undocumented function
 *
 * @param array|null $headers
 * @param array|null $options
 * @param UsersRequestBuilderGetQueryParameters|null $queryParameters
 */
public function __construct(
    public ?array $headers = null,
    public ?array $options = null,
    public ?UsersRequestBuilderGetQueryParameters $queryParameters = null
) {}
```

**Comment by SilasKenneth** [comment]
For the impact of static methods on size, I think it is going to be there but not that big since we only add the static method to Configuration classes with the `QueryParameters` property.
