### ISSUE TITLE
API returns same response some time.

### ISSUE THREAD

**Issue by ketanvekariya** [microsoftgraph/msgraph-sdk-php#96]
Hi  run cronjob which fetch workspace and dump into mysql database. I also set log for all the workspace i got from response.

sometimes api response are the same( i mean it will not get updated workspace) until i open file and re upload it on server its start working.

I check file permission but that was not issued. I check log but updated workspace are not in response, but when i echo the response it display and reupload to server its display.

I dont find issue either this issue is cause by cache or something else

**Comment by ketanvekariya** [comment]
Now issue is that i will work like a charm but sometime its stop working. if i just open file and re upload file without and change then its works fine

**Comment by ketanvekariya** [comment]
I used "https://github.com/TangentSolutions/PowerBI-SDK-PHP" this SDK

**Comment by PatchworkBoy** [comment]
You need to raise the issue on that SDK's GitHub page. This is for a completely different SDK.

**Comment by MIchaelMainer** [comment]
Closing this as the question is about another SDK.
