### ISSUE TITLE
Improvement: expanded relations to objects

### ISSUE THREAD

**Issue by JValck** [microsoftgraph/msgraph-sdk-php#97]
When we query the graph and expand the a relationship, for example `/sites/root?$expand=sites` the return value type of [`getSites`](https://github.com/microsoftgraph/msgraph-sdk-php/blob/dev/src/Model/Site.php#L347) will be an array and not an array of `Site` objects.

This is just an example, the same counts for other expanded relationships (`/drive/root?$exapend=children`, ...). I'm aware that this is a breaking change. 
[AB#7584](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7584)

**Comment by MIchaelMainer** [comment]
Thank you for bringing this to our attention. 
896643

**Comment by MIchaelMainer** [comment]
related to #76

**Comment by Ndiritu** [comment]
Fixed in v2 preview release https://github.com/microsoftgraph/msgraph-sdk-php/issues/681

**Comment by isvargasmsft** [comment]
Hello @JValck  

Thank you very much for your patience. This issue is resolved in our [new SDK version 2.0.0-RC5](https://github.com/microsoftgraph/msgraph-sdk-php/issues/943). 

Please feel free to give it a try and share your feedback with us.

Kind regards, 

Isaac Vargas
