### ISSUE TITLE
Retrieve then update pattern of partially populated objects?

### ISSUE THREAD

**Issue by wizhippo** [microsoftgraph/msgraph-sdk-php#977]
For example a retrieved user only contains a subset the user prosperities.

Is it best to create then modify an empty User object to perform a patch or is it ok to change the retrieved user object and supply it to patch?

Concern is that the retrieved user only is populated with a subset of properties and the rest are null, will the unretrieved properties be patched to null? 

Or are nulls ignored? And if so how do you unset a value?

**Comment by Ndiritu** [comment]
@wizhippo 

If you're using version `1.x` of our SDK all scenarios you've outlined should work as expected. The retrieved User will be deserialized to an object containing only a subset of properties that you can update and add the same object to your PATCH request body

Our v2 RCs ignore nulls causing a bug where you can't unset a value. Thanks for pointing this out. We'll need to review this further.

**Comment by Ndiritu** [comment]
What version of the SDK are you using?

**Comment by wizhippo** [comment]
Thanks for confirming.  I'm trying out v2 and have noticed the behavior will nulls.  Glad to see it will be addressed.

**Comment by Ndiritu** [comment]
@wizhippo this has been resolved in 2.0.0-RC12.

You should be able to patch a partially-populated object without having to create a new instance.
