### ISSUE TITLE
Save attachments with multipart/signed

### ISSUE THREAD

**Issue by KodaCHC** [microsoftgraph/msgraph-sdk-php#980]
Is it possible to save attachments(encrypt complete mail) that come signed (multipart/signed)?

**Comment by Ndiritu** [comment]
@KodaCHC what do you mean by "save"? Is this fetching the attachment from an email? Or Adding the attachment to an email?

**Comment by KodaCHC** [comment]
Sorry. I mean fetching from email

**Comment by Ndiritu** [comment]
Might this [docs link](https://learn.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-1.0&tabs=http) be useful?
You can also append `/$value` to your endpoint to fetch the raw contents of the attachment
